### ISSUE TITLE
sqlite3.OperationalError: table lnurlp.pay_links has no column named fiat_base_multiplier

### ISSUE THREAD

**Issue by ChuckNorrison** [lnbits/lnbits#1047]
Iam running lnbits 0.9.1 on my raspiblitz and if i try to add a lnurlp, i get a 500 Internal Server Error. The lnbits journal results with

> Oct 09 18:48:47 raspberrypi sh[13815]: 2022-10-09 18:48:47.02 | ERROR | handled error
> Oct 09 18:48:47 raspberrypi sh[13815]: 2022-10-09 18:48:47.02 | ERROR | ERROR:
> Oct 09 18:48:47 raspberrypi sh[13815]: Traceback (most recent call last):
> Oct 09 18:48:47 raspberrypi sh[13815]:   File "/home/lnbits/lnbits/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
> Oct 09 18:48:47 raspberrypi sh[13815]:     self.dialect.do_execute(
> Oct 09 18:48:47 raspberrypi sh[13815]:   File "/home/lnbits/lnbits/venv/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
> Oct 09 18:48:47 raspberrypi sh[13815]:     cursor.execute(statement, parameters)
> Oct 09 18:48:47 raspberrypi sh[13815]: sqlite3.OperationalError: table lnurlp.pay_links has no column named fiat_base_multiplier
> Oct 09 18:48:47 raspberrypi sh[13815]: The above exception was the direct cause of the following exception:
> Oct 09 18:48:47 raspberrypi sh[13815]: Traceback (most recent call last):
> Oct 09 18:48:47 raspberrypi sh[13815]:   File "/home/lnbits/lnbits/venv/lib/python3.9/site-packages/starlette/middleware/errors.py", line 162, in __call__
> Oct 09 18:48:47 raspberrypi sh[13815]:     await self.app(scope, receive, _send)
> Oct 09 18:48:47 raspberrypi sh[13815]:   File "/home/lnbits/lnbits/venv/lib/python3.9/site-packages/starlette/middleware/gzip.py", line 24, in __call__
> Oct 09 18:48:47 raspberrypi sh[13815]:     await responder(scope, receive, send)
> Oct 09 18:48:47 raspberrypi sh[13815]:   File "/home/lnbits/lnbits/venv/lib/python3.9/site-packages/starlette/middleware/gzip.py", line 43, in __call__
> Oct 09 18:48:47 raspberrypi sh[13815]:     await self.app(scope, receive, self.send_with_gzip)
> Oct 09 18:48:47 raspberrypi sh[13815]:   File "/home/lnbits/lnbits/venv/lib/python3.9/site-packages/starlette/middleware/cors.py", line 92, in __call__
> Oct 09 18:48:47 raspberrypi sh[13815]:     await self.simple_response(scope, receive, send, request_headers=headers)
> Oct 09 18:48:47 raspberrypi sh[13815]:   File "/home/lnbits/lnbits/venv/lib/python3.9/site-packages/starlette/middleware/cors.py", line 147, in simple_response
> Oct 09 18:48:47 raspberrypi sh[13815]:     await self.app(scope, receive, send)
> Oct 09 18:48:47 raspberrypi sh[13815]:   File "/home/lnbits/lnbits/venv/lib/python3.9/site-packages/starlette/exceptions.py", line 93, in __call__
> Oct 09 18:48:47 raspberrypi sh[13815]:     raise exc
> Oct 09 18:48:47 raspberrypi sh[13815]:   File "/home/lnbits/lnbits/venv/lib/python3.9/site-packages/starlette/exceptions.py", line 82, in __call__
> Oct 09 18:48:47 raspberrypi sh[13815]:     await self.app(scope, receive, sender)
> Oct 09 18:48:47 raspberrypi sh[13815]:   File "/home/lnbits/lnbits/venv/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
> Oct 09 18:48:47 raspberrypi sh[13815]:     raise e
> Oct 09 18:48:47 raspberrypi sh[13815]:   File "/home/lnbits/lnbits/venv/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
> Oct 09 18:48:47 raspberrypi sh[13815]:     await self.app(scope, receive, send)
> Oct 09 18:48:47 raspberrypi sh[13815]:   File "/home/lnbits/lnbits/venv/lib/python3.9/site-packages/starlette/routing.py", line 670, in __call__
> Oct 09 18:48:47 raspberrypi sh[13815]:     await route.handle(scope, receive, send)
> Oct 09 18:48:47 raspberrypi sh[13815]:   File "/home/lnbits/lnbits/venv/lib/python3.9/site-packages/starlette/routing.py", line 266, in handle
> Oct 09 18:48:47 raspberrypi sh[13815]:     await self.app(scope, receive, send)
> Oct 09 18:48:47 raspberrypi sh[13815]:   File "/home/lnbits/lnbits/venv/lib/python3.9/site-packages/starlette/routing.py", line 65, in app
> Oct 09 18:48:47 raspberrypi sh[13815]:     response = await func(request)
> Oct 09 18:48:47 raspberrypi sh[13815]:   File "/home/lnbits/lnbits/venv/lib/python3.9/site-packages/fastapi/routing.py", line 227, in app
> Oct 09 18:48:47 raspberrypi sh[13815]:     raw_response = await run_endpoint_function(
> Oct 09 18:48:47 raspberrypi sh[13815]:   File "/home/lnbits/lnbits/venv/lib/python3.9/site-packages/fastapi/routing.py", line 160, in run_endpoint_function
> Oct 09 18:48:47 raspberrypi sh[13815]:     return await dependant.call(**values)
> Oct 09 18:48:47 raspberrypi sh[13815]:   File "./lnbits/extensions/lnurlp/views_api.py", line 120, in api_link_create_or_update
> Oct 09 18:48:47 raspberrypi sh[13815]:     link = await create_pay_link(data, wallet_id=wallet.wallet.id)
> Oct 09 18:48:47 raspberrypi sh[13815]:   File "./lnbits/extensions/lnurlp/crud.py", line 14, in create_pay_link
> Oct 09 18:48:47 raspberrypi sh[13815]:     result = await (method)(
> Oct 09 18:48:47 raspberrypi sh[13815]:   File "./lnbits/db.py", line 189, in execute
> Oct 09 18:48:47 raspberrypi sh[13815]:     return await conn.execute(query, values)
> Oct 09 18:48:47 raspberrypi sh[13815]:   File "./lnbits/db.py", line 81, in execute
> Oct 09 18:48:47 raspberrypi sh[13815]:     return await self.conn.execute(self.rewrite_query(query), values)
> Oct 09 18:48:47 raspberrypi sh[13815]:   File "/home/lnbits/lnbits/venv/lib/python3.9/site-packages/sqlalchemy_aio/base.py", line 291, in execute
> Oct 09 18:48:47 raspberrypi sh[13815]:     rp = await self._run_in_thread(
> Oct 09 18:48:47 raspberrypi sh[13815]:   File "/home/lnbits/lnbits/venv/lib/python3.9/site-packages/sqlalchemy_aio/base.py", line 234, in _run_in_thread
> Oct 09 18:48:47 raspberrypi sh[13815]:     return await _self._worker.run(_func, args, kwargs)
> Oct 09 18:48:47 raspberrypi sh[13815]:   File "/home/lnbits/lnbits/venv/lib/python3.9/site-packages/sqlalchemy_aio/asyncio.py", line 70, in run
> Oct 09 18:48:47 raspberrypi sh[13815]:     return request.response.unwrap()
> Oct 09 18:48:47 raspberrypi sh[13815]:   File "/home/lnbits/lnbits/venv/lib/python3.9/site-packages/outcome/_impl.py", line 138, in unwrap
> Oct 09 18:48:47 raspberrypi sh[13815]:     raise captured_error
> Oct 09 18:48:47 raspberrypi sh[13815]:   File "/home/lnbits/lnbits/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1003, in execute
> Oct 09 18:48:47 raspberrypi sh[13815]:     return self._execute_text(object_, multiparams, params)
> Oct 09 18:48:47 raspberrypi sh[13815]:   File "/home/lnbits/lnbits/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1172, in _execute_text
> Oct 09 18:48:47 raspberrypi sh[13815]:     ret = self._execute_context(
> Oct 09 18:48:47 raspberrypi sh[13815]:   File "/home/lnbits/lnbits/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1316, in _execute_context
> Oct 09 18:48:47 raspberrypi sh[13815]:     self._handle_dbapi_exception(
> Oct 09 18:48:47 raspberrypi sh[13815]:   File "/home/lnbits/lnbits/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1510, in _handle_dbapi_exception
> Oct 09 18:48:47 raspberrypi sh[13815]:     util.raise_(
> Oct 09 18:48:47 raspberrypi sh[13815]:   File "/home/lnbits/lnbits/venv/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
> Oct 09 18:48:47 raspberrypi sh[13815]:     raise exception
> Oct 09 18:48:47 raspberrypi sh[13815]:   File "/home/lnbits/lnbits/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
> Oct 09 18:48:47 raspberrypi sh[13815]:     self.dialect.do_execute(
> Oct 09 18:48:47 raspberrypi sh[13815]:   File "/home/lnbits/lnbits/venv/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
> Oct 09 18:48:47 raspberrypi sh[13815]:     cursor.execute(statement, parameters)
> Oct 09 18:48:47 raspberrypi sh[13815]: sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) table lnurlp.pay_links has no column named fiat_base_multiplier
> Oct 09 18:48:47 raspberrypi sh[13815]: [SQL:
> Oct 09 18:48:47 raspberrypi sh[13815]:         INSERT INTO lnurlp.pay_links (
> Oct 09 18:48:47 raspberrypi sh[13815]:             wallet,
> Oct 09 18:48:47 raspberrypi sh[13815]:             description,
> Oct 09 18:48:47 raspberrypi sh[13815]:             min,
> Oct 09 18:48:47 raspberrypi sh[13815]:             max,
> Oct 09 18:48:47 raspberrypi sh[13815]:             served_meta,
> Oct 09 18:48:47 raspberrypi sh[13815]:             served_pr,
> Oct 09 18:48:47 raspberrypi sh[13815]:             webhook_url,
> Oct 09 18:48:47 raspberrypi sh[13815]:             success_text,
> Oct 09 18:48:47 raspberrypi sh[13815]:             success_url,
> Oct 09 18:48:47 raspberrypi sh[13815]:             comment_chars,
> Oct 09 18:48:47 raspberrypi sh[13815]:             currency,
> Oct 09 18:48:47 raspberrypi sh[13815]:             fiat_base_multiplier
> Oct 09 18:48:47 raspberrypi sh[13815]:         )
> Oct 09 18:48:47 raspberrypi sh[13815]:         VALUES (?, ?, ?, ?, 0, 0, ?, ?, ?, ?, ?, ?)
> Oct 09 18:48:47 raspberrypi sh[13815]:         
> Oct 09 18:48:47 raspberrypi sh[13815]:         ]
> Oct 09 18:48:47 raspberrypi sh[13815]: [parameters: ('02fxxx6b0cxxx8d7bd3855xxx71adde1', 'test lnurlp', 500.0, 500.0, None, None, None, 0, None, 100)]
> Oct 09 18:48:47 raspberrypi sh[13815]: (Background on this error at: http://sqlalche.me/e/13/e3q8)
> Oct 09 18:48:47 raspberrypi sh[13815]: 2022-10-09 18:48:47.02 | ERROR | Exception in ASGI application
> Oct 09 18:48:47 raspberrypi sh[13815]: 2022-10-09 18:48:47.02 | INFO | 193.9.112.122:0 - "POST /lnurlp/api/v1/links HTTP/1.0" 500

**Comment by ChuckNorrison** [comment]
Was able to fix my database

> sudo -u lnbits sqlite3 ext_lnurlp.sqlite3 
> SQLite version 3.34.1 2021-01-20 14:10:07
> Enter ".help" for usage hints.
> sqlite> .tables
> pay_links
> sqlite> ALTER TABLE pay_links ADD COLUMN fiat_base_multiplier INTEGER DEFAULT 1;
