### ISSUE TITLE
httpx.RemoteProtocolError: peer closed connection without sending complete message body (incomplete chunked read) 

### ISSUE THREAD

**Issue by HamishMacEwan** [lnbits/lnbits#1061]
This error is occurring repeatedly every 90 seconds or so:

```
File "/home/user/.cache/pypoetry/virtualenvs/lnbits-c9dgov88-py3.9/lib/python3.9/site-packages/httpx/_transports/default.py", line 77, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.RemoteProtocolError: peer closed connection without sending complete message body (incomplete chunked read)
```

There are also errors arising from handling the error.  Here's the screen shot:
![WindowsTerminal_7kOWFJkIrA](https://user-images.githubusercontent.com/388061/196853634-99280699-3cb4-4f65-82b0-8d9e806dc1a0.png)

If any more information is useful, happy to provide.  

This is lnbits-legend running on a VPS with NGINX and Let's Encrypt certification.  Just the way Option 1 (Poetry) made it.

**Comment by callebtc** [comment]
Thanks for reporting. This looks like a bug in the lnbits wallet backend. Are you using the demo server for that? It might have to do with the reverse proxy running on that server as well. Will investigate.

**Comment by HamishMacEwan** [comment]
```
LNBITS_BACKEND_WALLET_CLASS=LNbitsWallet
# LnbitsWallet
LNBITS_ENDPOINT=https://[redacted].macewan.nz:5001
```

That endpoint is the `DarthCoin 0.9.4` release running on @tehelsper's `myNodeBTC v0.3.03`.  It's behind `nginx` and in a Docker container.  

The reverse proxy configuration is:
```
server {
    listen 5001 ssl;
    server_name lnbits;

    include /etc/nginx/mynode/mynode_ssl_params.conf;
    include /home/bitcoin/trash/LNbitsStuff/mynode.local_ssl_cert_key.conf;

    access_log /var/log/nginx/access_lnbits.log;
    error_log /var/log/nginx/error_lnbits.log;

#    location /static {
#        root /opt/mynode/lnbits/lnbits;
#    }

    location / {
        proxy_pass http://127.0.0.1:5000;

        include /etc/nginx/mynode/mynode_ssl_proxy_params.conf;
    }

}
```
The /etc/nginx/mynode/ files are at https://github.com/mynodebtc/mynode/tree/master/rootfs/standard/etc/nginx/mynode

The local customisation, /home/bitcoin/trash/LNbitsStuff/mynode.local_ssl_cert_key.conf contains:
```
# Set myNode.local.macewan.nz HTTPS Cert and Key
ssl_certificate /home/bitcoin/trash/LNbitsStuff/mynode.local.hitch.pem;
ssl_certificate_key /home/bitcoin/trash/LNbitsStuff/mynode.local.hitch.pem;
```

Hope that helps.  It's tragic to watch the app puke, and puke on a puke handling routine every 90s.  Eventually it chokes and dies.  Not inflicting a systemd service unit on it till it can stand up a bit better.  

IF there's any additional information at either client or funding end you require, please advise.

**Comment by HamishMacEwan** [comment]
`LNBITS_ENDPOINT=https://2b21057be1.d.voltageapp.io`

Replaced the funding backend with an LNbits account running on a Voltage.cloud lite node and all the error messages have vanished.

**Comment by HamishMacEwan** [comment]
This is the log from the `DarthCoin 0.9.4` release running on @tehelsper's `myNodeBTC v0.3.03`. 

```
Oct 24 09:53:05 myNode lnbits[8540]: 2022-10-23 20:53:05.26 | ERROR | Exception in ASGI application
Oct 24 09:53:05 myNode lnbits[8540]: ValueError: I/O operation on closed file
Oct 24 09:53:05 myNode lnbits[8540]:     raise ValueError("I/O operation on closed file")
Oct 24 09:53:05 myNode lnbits[8540]:   File "/usr/local/lib/python3.9/_compression.py", line 14, in _check_not_closed
Oct 24 09:53:05 myNode lnbits[8540]:     self._check_not_closed()
Oct 24 09:53:05 myNode lnbits[8540]:   File "/usr/local/lib/python3.9/gzip.py", line 272, in write
Oct 24 09:53:05 myNode lnbits[8540]:     self.gzip_file.write(body)
Oct 24 09:53:05 myNode lnbits[8540]:   File "/usr/local/lib/python3.9/site-packages/starlette/middleware/gzip.py", line 93, in send_with_gzip
Oct 24 09:53:05 myNode lnbits[8540]:     await send(message)
Oct 24 09:53:05 myNode lnbits[8540]:   File "/usr/local/lib/python3.9/site-packages/starlette/exceptions.py", line 79, in sender
Oct 24 09:53:05 myNode lnbits[8540]:     await send({"type": "http.response.body", "body": ping, "more_body": True})
Oct 24 09:53:05 myNode lnbits[8540]:   File "/usr/local/lib/python3.9/site-packages/sse_starlette/sse.py", line 259, in _ping
Oct 24 09:53:05 myNode lnbits[8540]:     await self._ping_task
Oct 24 09:53:05 myNode lnbits[8540]:   File "/usr/local/lib/python3.9/site-packages/sse_starlette/sse.py", line 216, in wait
Oct 24 09:53:05 myNode lnbits[8540]:     await self.wait()
Oct 24 09:53:05 myNode lnbits[8540]:   File "/usr/local/lib/python3.9/site-packages/sse_starlette/sse.py", line 182, in __call__
Oct 24 09:53:05 myNode lnbits[8540]:     await response(scope, receive, send)
Oct 24 09:53:05 myNode lnbits[8540]:   File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 68, in app
Oct 24 09:53:05 myNode lnbits[8540]:     await self.app(scope, receive, send)
Oct 24 09:53:05 myNode lnbits[8540]:   File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 266, in handle
Oct 24 09:53:05 myNode lnbits[8540]:     await route.handle(scope, receive, send)
Oct 24 09:53:05 myNode lnbits[8540]:   File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 670, in __call__
Oct 24 09:53:05 myNode lnbits[8540]:     await self.app(scope, receive, send)
Oct 24 09:53:05 myNode lnbits[8540]:   File "/usr/local/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
Oct 24 09:53:05 myNode lnbits[8540]:     raise e
Oct 24 09:53:05 myNode lnbits[8540]:   File "/usr/local/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
Oct 24 09:53:05 myNode lnbits[8540]:     await self.app(scope, receive, sender)
Oct 24 09:53:05 myNode lnbits[8540]:   File "/usr/local/lib/python3.9/site-packages/starlette/exceptions.py", line 82, in __call__
Oct 24 09:53:05 myNode lnbits[8540]:     raise exc
Oct 24 09:53:05 myNode lnbits[8540]:   File "/usr/local/lib/python3.9/site-packages/starlette/exceptions.py", line 93, in __call__
Oct 24 09:53:05 myNode lnbits[8540]:     await self.app(scope, receive, send)
Oct 24 09:53:05 myNode lnbits[8540]:   File "/usr/local/lib/python3.9/site-packages/starlette/middleware/cors.py", line 84, in __call__
Oct 24 09:53:05 myNode lnbits[8540]:     await self.app(scope, receive, self.send_with_gzip)
Oct 24 09:53:05 myNode lnbits[8540]:   File "/usr/local/lib/python3.9/site-packages/starlette/middleware/gzip.py", line 43, in __call__
Oct 24 09:53:05 myNode lnbits[8540]:     await responder(scope, receive, send)
Oct 24 09:53:05 myNode lnbits[8540]:   File "/usr/local/lib/python3.9/site-packages/starlette/middleware/gzip.py", line 24, in __call__
Oct 24 09:53:05 myNode lnbits[8540]:     await self.app(scope, receive, _send)
Oct 24 09:53:05 myNode lnbits[8540]:   File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 162, in __call__
Oct 24 09:53:05 myNode lnbits[8540]: Traceback (most recent call last):
Oct 24 09:53:05 myNode lnbits[8540]: 2022-10-23 20:53:05.23 | ERROR | ERROR:
Oct 24 09:53:05 myNode lnbits[8540]: 2022-10-23 20:53:05.23 | ERROR | handled error
```

**Comment by callebtc** [comment]
Not exactly sure what's happening here but I would guess this might have to do with the invoice listeners that are maybe broken on the remote instance. Which version is running there? Might be worth an update.

**Comment by dni** [comment]
closed, old issue, reopen if error still exists.
