### ISSUE TITLE
Integer Out of Range: Unable to make payments >2,300,000 SAT

### ISSUE THREAD

**Issue by Liongrass** [lnbits/lnbits#1069]
I noticed I am unable to make payments larger than ~2.3M SAT.

Error in the logs:

```
Oct 21 20:34:36 send pipenv[707]: 2022-10-21 20:34:36.66 | ERROR | handled error
Oct 21 20:34:36 send pipenv[707]: 2022-10-21 20:34:36.66 | ERROR | ERROR:
Oct 21 20:34:36 send pipenv[707]: Traceback (most recent call last):
Oct 21 20:34:36 send pipenv[707]:   File "/home/ubuntu/.local/share/virtualenvs/ubuntu-7Wf190Ea/lib/python3.8/site-packages/sqlalchemy/engine/base.py", l>
Oct 21 20:34:36 send pipenv[707]:     self.dialect.do_execute(
Oct 21 20:34:36 send pipenv[707]:   File "/home/ubuntu/.local/share/virtualenvs/ubuntu-7Wf190Ea/lib/python3.8/site-packages/sqlalchemy/engine/default.py">
Oct 21 20:34:36 send pipenv[707]:     cursor.execute(statement, parameters)
Oct 21 20:34:36 send pipenv[707]: psycopg2.errors.NumericValueOutOfRange: integer out of range
Oct 21 20:34:36 send pipenv[707]: The above exception was the direct cause of the following exception:
Oct 21 20:34:36 send pipenv[707]: Traceback (most recent call last):
Oct 21 20:34:36 send pipenv[707]:   File "/home/ubuntu/.local/share/virtualenvs/ubuntu-7Wf190Ea/lib/python3.8/site-packages/starlette/middleware/errors.p>
Oct 21 20:34:36 send pipenv[707]:     await self.app(scope, receive, _send)
Oct 21 20:34:36 send pipenv[707]:   File "/home/ubuntu/.local/share/virtualenvs/ubuntu-7Wf190Ea/lib/python3.8/site-packages/starlette/middleware/gzip.py">
Oct 21 20:34:36 send pipenv[707]:     await responder(scope, receive, send)
Oct 21 20:34:36 send pipenv[707]:   File "/home/ubuntu/.local/share/virtualenvs/ubuntu-7Wf190Ea/lib/python3.8/site-packages/starlette/middleware/gzip.py">
Oct 21 20:34:36 send pipenv[707]:     await self.app(scope, receive, self.send_with_gzip)
Oct 21 20:34:36 send pipenv[707]:   File "/home/ubuntu/.local/share/virtualenvs/ubuntu-7Wf190Ea/lib/python3.8/site-packages/starlette/middleware/cors.py">
Oct 21 20:34:36 send pipenv[707]:     await self.simple_response(scope, receive, send, request_headers=headers)
Oct 21 20:34:36 send pipenv[707]:   File "/home/ubuntu/.local/share/virtualenvs/ubuntu-7Wf190Ea/lib/python3.8/site-packages/starlette/middleware/cors.py">
Oct 21 20:34:36 send pipenv[707]:     await self.app(scope, receive, send)
Oct 21 20:34:36 send pipenv[707]:   File "/home/ubuntu/.local/share/virtualenvs/ubuntu-7Wf190Ea/lib/python3.8/site-packages/starlette/exceptions.py", lin>
Oct 21 20:34:36 send pipenv[707]:     raise exc
Oct 21 20:34:36 send pipenv[707]:   File "/home/ubuntu/.local/share/virtualenvs/ubuntu-7Wf190Ea/lib/python3.8/site-packages/starlette/exceptions.py", lin>
Oct 21 20:34:36 send pipenv[707]:     await self.app(scope, receive, sender)
Oct 21 20:34:36 send pipenv[707]:   File "/home/ubuntu/.local/share/virtualenvs/ubuntu-7Wf190Ea/lib/python3.8/site-packages/fastapi/middleware/asyncexits>
Oct 21 20:34:36 send pipenv[707]:     raise e
Oct 21 20:34:36 send pipenv[707]:   File "/home/ubuntu/.local/share/virtualenvs/ubuntu-7Wf190Ea/lib/python3.8/site-packages/fastapi/middleware/asyncexits>
Oct 21 20:34:36 send pipenv[707]:     await self.app(scope, receive, send)
Oct 21 20:34:36 send pipenv[707]:   File "/home/ubuntu/.local/share/virtualenvs/ubuntu-7Wf190Ea/lib/python3.8/site-packages/starlette/routing.py", line 6>
Oct 21 20:34:36 send pipenv[707]:     await route.handle(scope, receive, send)
Oct 21 20:34:36 send pipenv[707]:   File "/home/ubuntu/.local/share/virtualenvs/ubuntu-7Wf190Ea/lib/python3.8/site-packages/starlette/routing.py", line 2>
Oct 21 20:34:36 send pipenv[707]:     await self.app(scope, receive, send)
Oct 21 20:34:36 send pipenv[707]:   File "/home/ubuntu/.local/share/virtualenvs/ubuntu-7Wf190Ea/lib/python3.8/site-packages/starlette/routing.py", line 6>
Oct 21 20:34:36 send pipenv[707]:     response = await func(request)
Oct 21 20:34:36 send pipenv[707]:   File "/home/ubuntu/.local/share/virtualenvs/ubuntu-7Wf190Ea/lib/python3.8/site-packages/fastapi/routing.py", line 227>
Oct 21 20:34:36 send pipenv[707]:     raw_response = await run_endpoint_function(
Oct 21 20:34:36 send pipenv[707]:   File "/home/ubuntu/.local/share/virtualenvs/ubuntu-7Wf190Ea/lib/python3.8/site-packages/fastapi/routing.py", line 160>
Oct 21 20:34:36 send pipenv[707]:     return await dependant.call(**values)
Oct 21 20:34:36 send pipenv[707]:   File "/home/ubuntu/git/lnbits-legend/./lnbits/core/views/api.py", line 279, in api_payments_create
Oct 21 20:34:36 send pipenv[707]:     return await api_payments_pay_invoice(
Oct 21 20:34:36 send pipenv[707]:   File "/home/ubuntu/git/lnbits-legend/./lnbits/core/views/api.py", line 256, in api_payments_pay_invoice
Oct 21 20:34:36 send pipenv[707]:     raise exc
Oct 21 20:34:36 send pipenv[707]:   File "/home/ubuntu/git/lnbits-legend/./lnbits/core/views/api.py", line 248, in api_payments_pay_invoice
Oct 21 20:34:36 send pipenv[707]:     payment_hash = await pay_invoice(wallet_id=wallet.id, payment_request=bolt11)
Oct 21 20:34:36 send pipenv[707]:   File "/home/ubuntu/git/lnbits-legend/./lnbits/core/services.py", line 168, in pay_invoice
Oct 21 20:34:36 send pipenv[707]:     wallet = await get_wallet(wallet_id, conn=conn)
Oct 21 20:34:36 send pipenv[707]:   File "/home/ubuntu/git/lnbits-legend/./lnbits/core/crud.py", line 147, in get_wallet
Oct 21 20:34:36 send pipenv[707]:     row = await (conn or db).fetchone(
Oct 21 20:34:36 send pipenv[707]:   File "/home/ubuntu/git/lnbits-legend/./lnbits/db.py", line 75, in fetchone
Oct 21 20:34:36 send pipenv[707]:     result = await self.conn.execute(self.rewrite_query(query), values)
Oct 21 20:34:36 send pipenv[707]:   File "/home/ubuntu/.local/share/virtualenvs/ubuntu-7Wf190Ea/lib/python3.8/site-packages/sqlalchemy_aio/base.py", line>
Oct 21 20:34:36 send pipenv[707]:     rp = await self._run_in_thread(
Oct 21 20:34:36 send pipenv[707]:   File "/home/ubuntu/.local/share/virtualenvs/ubuntu-7Wf190Ea/lib/python3.8/site-packages/sqlalchemy_aio/base.py", line>
Oct 21 20:34:36 send pipenv[707]:     return await _self._worker.run(_func, args, kwargs)
Oct 21 20:34:36 send pipenv[707]:   File "/home/ubuntu/.local/share/virtualenvs/ubuntu-7Wf190Ea/lib/python3.8/site-packages/sqlalchemy_aio/asyncio.py", l>
Oct 21 20:34:36 send pipenv[707]:     return request.response.unwrap()
Oct 21 20:34:36 send pipenv[707]:   File "/home/ubuntu/.local/share/virtualenvs/ubuntu-7Wf190Ea/lib/python3.8/site-packages/outcome/_impl.py", line 138, >
Oct 21 20:34:36 send pipenv[707]:     raise captured_error
Oct 21 20:34:36 send pipenv[707]:   File "/home/ubuntu/.local/share/virtualenvs/ubuntu-7Wf190Ea/lib/python3.8/site-packages/sqlalchemy/engine/base.py", l>
Oct 21 20:34:36 send pipenv[707]:     return self._execute_text(object_, multiparams, params)
Oct 21 20:34:36 send pipenv[707]:   File "/home/ubuntu/.local/share/virtualenvs/ubuntu-7Wf190Ea/lib/python3.8/site-packages/sqlalchemy/engine/base.py", l>
Oct 21 20:34:36 send pipenv[707]:     ret = self._execute_context(
Oct 21 20:34:36 send pipenv[707]:   File "/home/ubuntu/.local/share/virtualenvs/ubuntu-7Wf190Ea/lib/python3.8/site-packages/sqlalchemy/engine/base.py", l>
Oct 21 20:34:36 send pipenv[707]:     self._handle_dbapi_exception(
Oct 21 20:34:36 send pipenv[707]:   File "/home/ubuntu/.local/share/virtualenvs/ubuntu-7Wf190Ea/lib/python3.8/site-packages/sqlalchemy/engine/base.py", l>
Oct 21 20:34:36 send pipenv[707]:     util.raise_(
Oct 21 20:34:36 send pipenv[707]:   File "/home/ubuntu/.local/share/virtualenvs/ubuntu-7Wf190Ea/lib/python3.8/site-packages/sqlalchemy/util/compat.py", l>
Oct 21 20:34:36 send pipenv[707]:     raise exception
Oct 21 20:34:36 send pipenv[707]:   File "/home/ubuntu/.local/share/virtualenvs/ubuntu-7Wf190Ea/lib/python3.8/site-packages/sqlalchemy/engine/base.py", l>
Oct 21 20:34:36 send pipenv[707]:     self.dialect.do_execute(
Oct 21 20:34:36 send pipenv[707]:   File "/home/ubuntu/.local/share/virtualenvs/ubuntu-7Wf190Ea/lib/python3.8/site-packages/sqlalchemy/engine/default.py">
Oct 21 20:34:36 send pipenv[707]:     cursor.execute(statement, parameters)
Oct 21 20:34:36 send pipenv[707]: sqlalchemy.exc.DataError: (psycopg2.errors.NumericValueOutOfRange) integer out of range
Oct 21 20:34:36 send pipenv[707]: [SQL:
Oct 21 20:34:36 send pipenv[707]:         SELECT *, COALESCE((SELECT balance FROM balances WHERE wallet = wallets.id), 0) AS balance_msat
Oct 21 20:34:36 send pipenv[707]:         FROM wallets
Oct 21 20:34:36 send pipenv[707]:         WHERE id = %s
Oct 21 20:34:36 send pipenv[707]:         ]
Oct 21 20:34:36 send pipenv[707]: [parameters: ('REDACTED',)]
Oct 21 20:34:36 send pipenv[707]: (Background on this error at: http://sqlalche.me/e/13/9h9h)
Oct 21 20:34:36 send pipenv[707]: 2022-10-21 20:34:36.67 | ERROR | Exception in ASGI application
Oct 21 20:34:36 send pipenv[707]: 2022-10-21 20:34:36.67 | INFO | 178.249.214.10:0 - "POST /api/v1/payments HTTP/1.0" 500
```

I believe the key issue here is `psycopg2.errors.NumericValueOutOfRange: integer out of range`

The actual maximum amount that I'm able to pay is likely slightly above 0.99*2^31 = 2,126,009 SAT

**Comment by callebtc** [comment]
This is probably related to the fact that SQLite uses only `INT` while Postgres wants `BIGINT` for large integers.

This has been fixed in a recent PR but it doesn't apply to old databases. Could you try to convert the type of the `amount` column in your postgres db (`public.apipayments`) to `BIGINT`?

**Comment by dni** [comment]
here a related issue and the PR

https://github.com/lnbits/lnbits/issues/956
https://github.com/lnbits/lnbits/pull/1030

**Comment by callebtc** [comment]
Closing because this has been fixed and we can't offer a better solution for existing dbs. Hope you'll manage the column conversion @Liongrass.

**Comment by guiporto** [comment]
I've just deployed a new lnbits instance (Postgres) from master (commit f3b720b690c533b4b28793209f5a71fd01b9af6e) and I can't generate large invoices. Just checked the db and amount is set as integer.
