### ISSUE TITLE
[BUG] LNURLDEVICE on a localhost node

### ISSUE THREAD

**Issue by JensC** [lnbits/lnbits#1090]
**Describe the bug**
I've installed the newest version of lnbits and the plugin LNURLDEVICE. 
When I want to create a instance (switch) an error 500 pops up.
lnbits itself works just fine

**Desktop (please complete the following information):**
 - LNbits version: newest
 
The lnbits uses a nginx reverse proxy (url: https://192.168.1.48:4002/lnurldevice/?usr....) 
The error log looks like this:
```
Oct 27 17:42:07 rocky-raccoon poetry[61537]: 2022-10-27 17:42:07.31 | ERROR | handled error
Oct 27 17:42:07 rocky-raccoon poetry[61537]: 2022-10-27 17:42:07.31 | ERROR | ERROR:
Oct 27 17:42:07 rocky-raccoon poetry[61537]: Traceback (most recent call last):
Oct 27 17:42:07 rocky-raccoon poetry[61537]:   File "/home/pi/.cache/pypoetry/virtualenvs/lnbits-UJme9GZJ-py3.9/lib/python3.9/site-packages/lnurl/core.py", line 24, in encode
Oct 27 17:42:07 rocky-raccoon poetry[61537]:     return Lnurl(_url_encode(url))
Oct 27 17:42:07 rocky-raccoon poetry[61537]:   File "/home/pi/.cache/pypoetry/virtualenvs/lnbits-UJme9GZJ-py3.9/lib/python3.9/site-packages/lnurl/types.py", line 161, in __init__
Oct 27 17:42:07 rocky-raccoon poetry[61537]:     self.url = url if url else self.__get_url__(bech32)
Oct 27 17:42:07 rocky-raccoon poetry[61537]:   File "/home/pi/.cache/pypoetry/virtualenvs/lnbits-UJme9GZJ-py3.9/lib/python3.9/site-packages/lnurl/types.py", line 165, in __get_url__
Oct 27 17:42:07 rocky-raccoon poetry[61537]:     return parse_obj_as(Union[OnionUrl, ClearnetUrl], _lnurl_decode(bech32))
Oct 27 17:42:07 rocky-raccoon poetry[61537]:   File "/home/pi/.cache/pypoetry/virtualenvs/lnbits-UJme9GZJ-py3.9/lib/python3.9/site-packages/pydantic/tools.py", line 35, in parse_obj_as
Oct 27 17:42:07 rocky-raccoon poetry[61537]:     return model_type(__root__=obj).__root__
Oct 27 17:42:07 rocky-raccoon poetry[61537]:   File "/home/pi/.cache/pypoetry/virtualenvs/lnbits-UJme9GZJ-py3.9/lib/python3.9/site-packages/pydantic/main.py", line 406, in __init__
Oct 27 17:42:07 rocky-raccoon poetry[61537]:     raise validation_error
Oct 27 17:42:07 rocky-raccoon poetry[61537]: pydantic.error_wrappers.ValidationError: 2 validation errors for ParsingModel[Union[lnurl.types.OnionUrl, lnurl.types.ClearnetUrl]]
Oct 27 17:42:07 rocky-raccoon poetry[61537]: __root__
Oct 27 17:42:07 rocky-raccoon poetry[61537]:   URL host invalid, top level domain required (type=value_error.url.host)
Oct 27 17:42:07 rocky-raccoon poetry[61537]: __root__
Oct 27 17:42:07 rocky-raccoon poetry[61537]:   URL scheme not permitted (type=value_error.url.scheme; allowed_schemes={'https'})
Oct 27 17:42:07 rocky-raccoon poetry[61537]: During handling of the above exception, another exception occurred:
Oct 27 17:42:07 rocky-raccoon poetry[61537]: Traceback (most recent call last):
Oct 27 17:42:07 rocky-raccoon poetry[61537]:   File "/home/pi/.cache/pypoetry/virtualenvs/lnbits-UJme9GZJ-py3.9/lib/python3.9/site-packages/starlette/middleware/errors.py", line 162, in __call__
Oct 27 17:42:07 rocky-raccoon poetry[61537]:     await self.app(scope, receive, _send)
Oct 27 17:42:07 rocky-raccoon poetry[61537]:   File "/home/pi/.cache/pypoetry/virtualenvs/lnbits-UJme9GZJ-py3.9/lib/python3.9/site-packages/starlette/middleware/gzip.py", line 24, in __call__
Oct 27 17:42:07 rocky-raccoon poetry[61537]:     await responder(scope, receive, send)
Oct 27 17:42:07 rocky-raccoon poetry[61537]:   File "/home/pi/.cache/pypoetry/virtualenvs/lnbits-UJme9GZJ-py3.9/lib/python3.9/site-packages/starlette/middleware/gzip.py", line 43, in __call__
Oct 27 17:42:07 rocky-raccoon poetry[61537]:     await self.app(scope, receive, self.send_with_gzip)
Oct 27 17:42:07 rocky-raccoon poetry[61537]:   File "/home/pi/.cache/pypoetry/virtualenvs/lnbits-UJme9GZJ-py3.9/lib/python3.9/site-packages/starlette/middleware/cors.py", line 92, in __call__
Oct 27 17:42:07 rocky-raccoon poetry[61537]:     await self.simple_response(scope, receive, send, request_headers=headers)
Oct 27 17:42:07 rocky-raccoon poetry[61537]:   File "/home/pi/.cache/pypoetry/virtualenvs/lnbits-UJme9GZJ-py3.9/lib/python3.9/site-packages/starlette/middleware/cors.py", line 147, in simple_response
Oct 27 17:42:07 rocky-raccoon poetry[61537]:     await self.app(scope, receive, send)
Oct 27 17:42:07 rocky-raccoon poetry[61537]:   File "/home/pi/.cache/pypoetry/virtualenvs/lnbits-UJme9GZJ-py3.9/lib/python3.9/site-packages/starlette/exceptions.py", line 93, in __call__
Oct 27 17:42:07 rocky-raccoon poetry[61537]:     raise exc
Oct 27 17:42:07 rocky-raccoon poetry[61537]:   File "/home/pi/.cache/pypoetry/virtualenvs/lnbits-UJme9GZJ-py3.9/lib/python3.9/site-packages/starlette/exceptions.py", line 82, in __call__
Oct 27 17:42:07 rocky-raccoon poetry[61537]:     await self.app(scope, receive, sender)
Oct 27 17:42:07 rocky-raccoon poetry[61537]:   File "/home/pi/.cache/pypoetry/virtualenvs/lnbits-UJme9GZJ-py3.9/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
Oct 27 17:42:07 rocky-raccoon poetry[61537]:     raise e
Oct 27 17:42:07 rocky-raccoon poetry[61537]:   File "/home/pi/.cache/pypoetry/virtualenvs/lnbits-UJme9GZJ-py3.9/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
Oct 27 17:42:07 rocky-raccoon poetry[61537]:     await self.app(scope, receive, send)
Oct 27 17:42:07 rocky-raccoon poetry[61537]:   File "/home/pi/.cache/pypoetry/virtualenvs/lnbits-UJme9GZJ-py3.9/lib/python3.9/site-packages/starlette/routing.py", line 670, in __call__
Oct 27 17:42:07 rocky-raccoon poetry[61537]:     await route.handle(scope, receive, send)
Oct 27 17:42:07 rocky-raccoon poetry[61537]:   File "/home/pi/.cache/pypoetry/virtualenvs/lnbits-UJme9GZJ-py3.9/lib/python3.9/site-packages/starlette/routing.py", line 266, in handle
Oct 27 17:42:07 rocky-raccoon poetry[61537]:     await self.app(scope, receive, send)
Oct 27 17:42:07 rocky-raccoon poetry[61537]:   File "/home/pi/.cache/pypoetry/virtualenvs/lnbits-UJme9GZJ-py3.9/lib/python3.9/site-packages/starlette/routing.py", line 65, in app
Oct 27 17:42:07 rocky-raccoon poetry[61537]:     response = await func(request)
Oct 27 17:42:07 rocky-raccoon poetry[61537]:   File "/home/pi/.cache/pypoetry/virtualenvs/lnbits-UJme9GZJ-py3.9/lib/python3.9/site-packages/fastapi/routing.py", line 227, in app
Oct 27 17:42:07 rocky-raccoon poetry[61537]:     raw_response = await run_endpoint_function(
Oct 27 17:42:07 rocky-raccoon poetry[61537]:   File "/home/pi/.cache/pypoetry/virtualenvs/lnbits-UJme9GZJ-py3.9/lib/python3.9/site-packages/fastapi/routing.py", line 160, in run_endpoint_function
Oct 27 17:42:07 rocky-raccoon poetry[61537]:     return await dependant.call(**values)
Oct 27 17:42:07 rocky-raccoon poetry[61537]:   File "/home/pi/lnbits-legend/lnbits/extensions/lnurldevice/views_api.py", line 42, in api_lnurldevice_create_or_update
Oct 27 17:42:07 rocky-raccoon poetry[61537]:     return {**lnurldevice.dict(), **{"switches": lnurldevice.switches(req)}}
Oct 27 17:42:07 rocky-raccoon poetry[61537]:   File "/home/pi/lnbits-legend/lnbits/extensions/lnurldevice/models.py", line 77, in switches
Oct 27 17:42:07 rocky-raccoon poetry[61537]:     lnurl_encode(
Oct 27 17:42:07 rocky-raccoon poetry[61537]:   File "/home/pi/.cache/pypoetry/virtualenvs/lnbits-UJme9GZJ-py3.9/lib/python3.9/site-packages/lnurl/core.py", line 26, in encode
Oct 27 17:42:07 rocky-raccoon poetry[61537]:     raise InvalidUrl
Oct 27 17:42:07 rocky-raccoon poetry[61537]: lnurl.exceptions.InvalidUrl
Oct 27 17:42:07 rocky-raccoon poetry[61537]: 2022-10-27 17:42:07.31 | ERROR | Exception in ASGI application
Oct 27 17:42:07 rocky-raccoon poetry[61537]: 2022-10-27 17:42:07.31 | INFO | 127.0.0.1:51662 - "POST /lnurldevice/api/v1/lnurlpos HTTP/1.1" 500

```

**Comment by arcbtc** [comment]
lnurls need to be delivered over https, so it wont work locally
