### ISSUE TITLE
Deploying to fly.io: NotADirectoryError

### ISSUE THREAD

**Issue by mariodian** [lnbits/lnbits#1355]
I'm deploying to fly.io. Everything goes smoothly until the deployment is over and I get the following error on the fly.io side:

````
2023-01-12T04:36:06.262 app[6c56657f] den [info] Process Process-1:
2023-01-12T04:36:06.265 app[6c56657f] den [info] Traceback (most recent call last):
2023-01-12T04:36:06.265 app[6c56657f] den [info] File "/usr/local/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
2023-01-12T04:36:06.265 app[6c56657f] den [info] self.run()
2023-01-12T04:36:06.265 app[6c56657f] den [info] File "/usr/local/lib/python3.10/multiprocessing/process.py", line 108, in run
2023-01-12T04:36:06.265 app[6c56657f] den [info] self._target(*self._args, **self._kwargs)
2023-01-12T04:36:06.265 app[6c56657f] den [info] File "/usr/local/lib/python3.10/site-packages/uvicorn/server.py", line 60, in run
2023-01-12T04:36:06.265 app[6c56657f] den [info] return asyncio.run(self.serve(sockets=sockets))
2023-01-12T04:36:06.265 app[6c56657f] den [info] File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
2023-01-12T04:36:06.265 app[6c56657f] den [info] return loop.run_until_complete(main)
2023-01-12T04:36:06.265 app[6c56657f] den [info] File "uvloop/loop.pyx", line 1501, in uvloop.loop.Loop.run_until_complete
2023-01-12T04:36:06.265 app[6c56657f] den [info] File "/usr/local/lib/python3.10/site-packages/uvicorn/server.py", line 67, in serve
2023-01-12T04:36:06.265 app[6c56657f] den [info] config.load()
2023-01-12T04:36:06.265 app[6c56657f] den [info] File "/usr/local/lib/python3.10/site-packages/uvicorn/config.py", line 479, in load
2023-01-12T04:36:06.265 app[6c56657f] den [info] rt_from_string module = importlib.import_modul
2023-01-12T04:36:06.265 app[6c56657f] den [info] File "/usr/local/lib/python3.10/site-packages/uvicorn/importer.py", line 21, in import_from_string
2023-01-12T04:36:06.265 app[6c56657f] den [info] module = importlib.import_modul
2023-01-12T04:36:06.265 app[6c56657f] den [info] (module_str)
2023-01-12T04:36:06.265 app[6c56657f] den [info] File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
2023-01-12T04:36:06.265 app[6c56657f] den [info] return _bootstrap._gcd_import(name[level:], package, level)
2023-01-12T04:36:06.265 app[6c56657f] den [info] File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
2023-01-12T04:36:06.265 app[6c56657f] den [info] File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
2023-01-12T04:36:06.265 app[6c56657f] den [info] File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
2023-01-12T04:36:06.265 app[6c56657f] den [info] File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
2023-01-12T04:36:06.265 app[6c56657f] den [info] File "<frozen importlib._bootstrap_external>", line 883, in exec_module
2023-01-12T04:36:06.265 app[6c56657f] den [info] File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
2023-01-12T04:36:06.265 app[6c56657f] den [info] File "/app/lnbits/__main__.py", line 1, in <module>
2023-01-12T04:36:06.265 app[6c56657f] den [info] __init__.py", line 5, in <modul
2023-01-12T04:36:06.265 app[6c56657f] den [info] File "/app/lnbits/app.py", line 17, in <module>
2023-01-12T04:36:06.265 app[6c56657f] den [info] from lnbits.core.tasks import register_task_listeners
2023-01-12T04:36:06.265 app[6c56657f] den [info] File "/app/lnbits/core/__init__.py", line 5, in <modul
2023-01-12T04:36:06.265 app[6c56657f] den [info] >
2023-01-12T04:36:06.265 app[6c56657f] den [info] db = Database("database")
2023-01-12T04:36:06.265 app[6c56657f] den [info] File "/app/lnbits/db.py", line 172, in __init__
2023-01-12T04:36:06.265 app[6c56657f] den [info] raise NotADirectoryError(
2023-01-12T04:36:06.265 app[6c56657f] den [info] NotADirectoryError: LNBITS_DATA_FOLDER named ./data was not created - please 'mkdir ./data' and try again
````

The following is set in `fly.toml` along with other unrelated stuff:

````
LNBITS_DATA_FOLDER="./data"
````

and I do see the `data` folder created in `/app/lnbits/` on fly.io however I don't see any sqlite file in there.

LNbits version: a813a37
Database: sqlite

**Comment by motorina0** [comment]
fixed here: https://github.com/lnbits/lnbits/pull/1930
