### ISSUE TITLE
Installation problems (Windows)

### ISSUE THREAD

**Issue by tradewind886** [lnbits/lnbits#155]
Having difficulty setting up lnbits on Windows machine, stuck at the "quart migrate" step. 

Receiving "duplicate column name error from sqlalchemy"

> running migration core.1
running migration core.2
running migration core.3
running migration bleskomat.1
running migration events.1
running migration events.2
running migration lnticket.1
running migration lnticket.2
running migration lnticket.3
running migration lnurlp.1
running migration lnurlp.2
Traceback (most recent call last):
  File "c:\users\HOMEDIRECTORY\.virtualenvs\lnbits-ujz_aox8\lib\site-packages\sqlalchemy\engine\base.py", line 1277, in _execute_context
    cursor, statement, parameters, context
  File "c:\users\HOMEDIRECTORY\.virtualenvs\lnbits-ujz_aox8\lib\site-packages\sqlalchemy\engine\default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: duplicate column name: webhook_url
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "C:\Users\HOMEDIRECTORY\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\HOMEDIRECTORY\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\HOMEDIRECTORY\.virtualenvs\lnbits-uJz_aOX8\Scripts\quart.exe\__main__.py", line 7, in <module>
    sys.exit(main())
  File "c:\users\HOMEDIRECTORY\.virtualenvs\lnbits-ujz_aox8\lib\site-packages\quart\cli.py", line 294, in main
    cli.main(args=args, prog_name=name)
  File "c:\users\HOMEDIRECTORY\.virtualenvs\lnbits-ujz_aox8\lib\site-packages\quart\cli.py", line 229, in main
    return super().main(*args, **kwargs)
  File "c:\users\HOMEDIRECTORY\.virtualenvs\lnbits-ujz_aox8\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "c:\users\HOMEDIRECTORY\.virtualenvs\lnbits-ujz_aox8\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\HOMEDIRECTORY\.virtualenvs\lnbits-ujz_aox8\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\HOMEDIRECTORY\.virtualenvs\lnbits-ujz_aox8\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File ".\lnbits\commands.py", line 16, in db_migrate
    trio.run(migrate_databases)
  File "c:\users\HOMEDIRECTORY\.virtualenvs\lnbits-ujz_aox8\lib\site-packages\trio\_core\_run.py", line 1896, in run
    raise runner.main_task_outcome.error
  File ".\lnbits\commands.py", line 83, in migrate_databases
    await run_migration(ext_db, ext_migrations)
  File ".\lnbits\commands.py", line 72, in run_migration
    await migrate(db)
  File ".\lnbits\extensions\lnurlp\migrations.py", line 23, in m002_webhooks_and_success_actions
    await db.execute("ALTER TABLE pay_links ADD COLUMN webhook_url TEXT;")
  File ".\lnbits\db.py", line 65, in execute
    return await conn.execute(query, values)
  File "c:\users\HOMEDIRECTORY\.virtualenvs\lnbits-ujz_aox8\lib\site-packages\sqlalchemy_aio\base.py", line 288, in execute
    self._connection.execute, *args, **kwargs)
  File "c:\users\HOMEDIRECTORY\.virtualenvs\lnbits-ujz_aox8\lib\site-packages\sqlalchemy_aio\base.py", line 230, in _run_in_thread
    return await _self._worker.run(_func, args, kwargs)
  File "c:\users\HOMEDIRECTORY\.virtualenvs\lnbits-ujz_aox8\lib\site-packages\sqlalchemy_aio\trio.py", line 70, in run
    return resp.unwrap()
  File "c:\users\HOMEDIRECTORY\.virtualenvs\lnbits-ujz_aox8\lib\site-packages\outcome\_impl.py", line 138, in unwrap
    raise captured_error
  File "c:\users\HOMEDIRECTORY\.virtualenvs\lnbits-ujz_aox8\lib\site-packages\sqlalchemy\engine\base.py", line 1003, in execute
    return self._execute_text(object_, multiparams, params)
  File "c:\users\HOMEDIRECTORY\.virtualenvs\lnbits-ujz_aox8\lib\site-packages\sqlalchemy\engine\base.py", line 1178, in _execute_text
    parameters,
  File "c:\users\HOMEDIRECTORY\.virtualenvs\lnbits-ujz_aox8\lib\site-packages\sqlalchemy\engine\base.py", line 1317, in _execute_context
    e, statement, parameters, cursor, context
  File "c:\users\HOMEDIRECTORY\.virtualenvs\lnbits-ujz_aox8\lib\site-packages\sqlalchemy\engine\base.py", line 1511, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "c:\users\HOMEDIRECTORY\.virtualenvs\lnbits-ujz_aox8\lib\site-packages\sqlalchemy\util\compat.py", line 182, in raise_
    raise exception
  File "c:\users\HOMEDIRECTORY\.virtualenvs\lnbits-ujz_aox8\lib\site-packages\sqlalchemy\engine\base.py", line 1277, in _execute_context
    cursor, statement, parameters, context
  File "c:\users\HOMEDIRECTORY\.virtualenvs\lnbits-ujz_aox8\lib\site-packages\sqlalchemy\engine\default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) duplicate column name: webhook_url
[SQL: ALTER TABLE pay_links ADD COLUMN webhook_url TEXT;]
(Background on this error at: http://sqlalche.me/e/13/e3q8)

Has anyone managed to get LNbits running on a Windows machine? (using the LNDWallet setting as funding source for a local instance of LND)
So far i've had to modify lndgrpc\common.py to recognize the proper directory for LND to make it here.  It is not obvious what I need to do from here

Thanks for the help!

**Comment by fiatjaf** [comment]
This is weird.

What is the version of SQLite you're running? I think it must be over 3.24.

Can you open SQLite manually and print the schema for the lnurlp database? You can use https://sqlitebrowser.org/.

See if the `webhook_url` column is there, and also `success_text`. Then try to run `ALTER TABLE pay_links ADD COLUMN webhook_url TEXT` manually and see what happens.

**Comment by tradewind886** [comment]
Thank you. Looks like my SQLite version is up-to-date
>SQLite version 3.32.2 2020-06-04 12:58:43

looks like something is funky in the lndurlp schema:

> CREATE TABLE invoices (
            pay_link INTEGER NOT NULL REFERENCES pay_links (id),
            payment_hash TEXT NOT NULL,
            webhook_sent INT, -- null means not sent, otherwise store status
            expiry INT
        )

**Comment by fiatjaf** [comment]
What is funky? I don't see it. It looks ok to me. This error is bizarre.

Please try running this manually: `ALTER TABLE pay_links ADD COLUMN webhook_url TEXT`

**Comment by tradewind886** [comment]
receives the same duplicate column name error when attempting to run the query manually in the ext_lnurlp database

>Execution finished with errors.
Result: duplicate column name: webhook_url
At line 1:
ALTER TABLE pay_links ADD COLUMN webhook_url TEXT

**Comment by tradewind886** [comment]
It appears the duplicate column error is due to the migrate process is trying to add columns to an already existing table, but because the migrate process never completed the database is left in whatever state it was created in. (never completed lndurlp.2 of the migration process) so the error makes sense.

Removing all the tables before running 'quart assets' and 'quart migrate' appears to be the solution to get rid of the duplicate column error, but I still cant complete the migrate process....

now on part3 of the lndurlp.3 is is giving a syntax error:
>sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) near "COLUMN": syntax error
[SQL: ALTER TABLE pay_links RENAME COLUMN amount TO min;]

**Comment by fiatjaf** [comment]
I think you are the first brave user to try this on Windows, and you succeeded! Amazing!
Next time someone has trouble I will point them to this issue instead of fixing the problem.

**Comment by tradewind886** [comment]
i ran into issues when creating invoices, but it has to do with how i screwed up the database not paying attention to Column datatypes when adding columns.  I will eventually work my way through it because LNBits is definitely interacting with my instance of LND now (yay). The setup is much easier on Linux, I do not recommend windows for LNBits for those starting from scratch and haven't decided on a platform

>[2021-03-12 20:56:23,896] ERROR in app: Exception on request POST /api/v1/payments
Traceback (most recent call last):
  File "C:\Users\HOMEDIRECTORY\.virtualenvs\lnbits-uJz_aOX8\lib\site-packages\sqlalchemy\engine\base.py", line 1277, in _execute_context
    cursor, statement, parameters, context
  File "C:\Users\HOMEDIRECTORY\.virtualenvs\lnbits-uJz_aOX8\lib\site-packages\sqlalchemy\engine\default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
sqlite3.IntegrityError: NOT NULL constraint failed: apipayments.payhash
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "C:\Users\HOMEDIRECTORY\.virtualenvs\lnbits-uJz_aOX8\lib\site-packages\quart_trio\app.py", line 143, in handle_request
    return await self.full_dispatch_request(request_context)
  File "C:\Users\HOMEDIRECTORY\.virtualenvs\lnbits-uJz_aOX8\lib\site-packages\quart_trio\app.py", line 165, in full_dispatch_request
    result = await self.handle_user_exception(error)
  File "C:\Users\HOMEDIRECTORY\.virtualenvs\lnbits-uJz_aOX8\lib\site-packages\quart_trio\app.py", line 178, in handle_user_exception
    return await super().handle_user_exception(error)
  File "C:\Users\HOMEDIRECTORY\.virtualenvs\lnbits-uJz_aOX8\lib\site-packages\quart\app.py", line 1076, in handle_user_exception
    raise error
  File "C:\Users\HOMEDIRECTORY\.virtualenvs\lnbits-uJz_aOX8\lib\site-packages\quart_trio\app.py", line 163, in full_dispatch_request
    result = await self.dispatch_request(request_context)
  File "C:\Users\HOMEDIRECTORY\.virtualenvs\lnbits-uJz_aOX8\lib\site-packages\quart\app.py", line 1882, in dispatch_request
    return await handler(**request_.view_args)
  File "C:\Users\HOMEDIRECTORY\Workspace\lnbits\lnbits\decorators.py", line 55, in wrapped_view
    return await view(**kwargs)
  File "C:\Users\HOMEDIRECTORY\Workspace\lnbits\lnbits\core\views\api.py", line 147, in api_payments_create
    return await api_payments_create_invoice()
  File "C:\Users\HOMEDIRECTORY\Workspace\lnbits\lnbits\decorators.py", line 28, in wrapped_view
    return await view(**kwargs)
  File "C:\Users\HOMEDIRECTORY\Workspace\lnbits\lnbits\decorators.py", line 55, in wrapped_view
    return await view(**kwargs)
  File "C:\Users\HOMEDIRECTORY\Workspace\lnbits\lnbits\core\views\api.py", line 77, in api_payments_create_invoice
    raise exc
  File "C:\Users\HOMEDIRECTORY\Workspace\lnbits\lnbits\core\views\api.py", line 73, in api_payments_create_invoice
    webhook=g.data.get("webhook"),
  File "C:\Users\HOMEDIRECTORY\Workspace\lnbits\lnbits\core\services.py", line 54, in create_invoice
    webhook=webhook,
  File "C:\Users\HOMEDIRECTORY\Workspace\lnbits\lnbits\core\crud.py", line 276, in create_payment
    webhook,
  File "C:\Users\HOMEDIRECTORY\Workspace\lnbits\lnbits\db.py", line 62, in execute
    return await conn.execute(query, values)
  File "C:\Users\HOMEDIRECTORY\.virtualenvs\lnbits-uJz_aOX8\lib\site-packages\sqlalchemy_aio\base.py", line 288, in execute
    self._connection.execute, *args, **kwargs)
  File "C:\Users\HOMEDIRECTORY\.virtualenvs\lnbits-uJz_aOX8\lib\site-packages\sqlalchemy_aio\base.py", line 230, in _run_in_thread
    return await _self._worker.run(_func, args, kwargs)
  File "C:\Users\HOMEDIRECTORY\.virtualenvs\lnbits-uJz_aOX8\lib\site-packages\sqlalchemy_aio\trio.py", line 70, in run
    return resp.unwrap()
  File "C:\Users\HOMEDIRECTORY\.virtualenvs\lnbits-uJz_aOX8\lib\site-packages\outcome\_impl.py", line 138, in unwrap
    raise captured_error
  File "C:\Users\HOMEDIRECTORY\.virtualenvs\lnbits-uJz_aOX8\lib\site-packages\sqlalchemy\engine\base.py", line 1003, in execute
    return self._execute_text(object_, multiparams, params)
  File "C:\Users\HOMEDIRECTORY\.virtualenvs\lnbits-uJz_aOX8\lib\site-packages\sqlalchemy\engine\base.py", line 1178, in _execute_text
    parameters,
  File "C:\Users\HOMEDIRECTORY\.virtualenvs\lnbits-uJz_aOX8\lib\site-packages\sqlalchemy\engine\base.py", line 1317, in _execute_context
    e, statement, parameters, cursor, context
  File "C:\Users\HOMEDIRECTORY\.virtualenvs\lnbits-uJz_aOX8\lib\site-packages\sqlalchemy\engine\base.py", line 1511, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "C:\Users\HOMEDIRECTORY\.virtualenvs\lnbits-uJz_aOX8\lib\site-packages\sqlalchemy\util\compat.py", line 182, in raise_
    raise exception
  File "C:\Users\HOMEDIRECTORY\.virtualenvs\lnbits-uJz_aOX8\lib\site-packages\sqlalchemy\engine\base.py", line 1277, in _execute_context
    cursor, statement, parameters, context
  File "C:\Users\HOMEDIRECTORY\.virtualenvs\lnbits-uJz_aOX8\lib\site-packages\sqlalchemy\engine\default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) NOT NULL constraint failed: apipayments.payhash
[SQL:
        INSERT INTO apipayments
          (wallet, checking_id, bolt11, hash, preimage,
           amount, pending, memo, fee, extra, webhook)
        VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
        ]
[parameters: ('here was a valid wallet ID', 'here was a valid checking_id', 'here was a valid bolt11 invoice', 'here was a valid hash', None, 1000, 1, 'LNBits Invoice Test', 0, None, None)]
(Background on this error at: http://sqlalche.me/e/13/gkpj)
[2021-03-12 20:56:23,898] Error in ASGI Framework

Thanks for calling me brave, made my day after feeling like an idiot for many hours.
