### ISSUE TITLE
[BUG] No description passed to CLN pay_invoice

### ISSUE THREAD

**Issue by daywalker90** [lnbits/lnbits#1553]
**Describe the bug**
cln background not working with e.g. lightning addresses or other description-less invoices.

**To Reproduce**
1. Go to Paste Request
2. Enter lightning address
3. Continue dialog
4. See error: 
```
Feb 28 17:58:07 poetry[619976]: 2023-02-28 17:58:07.83 | WARNING | backend sent payment failure
Feb 28 17:58:07 poetry[619976]: Traceback (most recent call last):
Feb 28 17:58:07 poetry[619976]:   File "/home/bitcoin/.cache/pypoetry/virtualenvs/lnbits-YwOF1MmK-py3.9/lib/python3.9/site-packages/starlette/middleware/errors.py", line 162, in __call__
Feb 28 17:58:07 poetry[619976]:     await self.app(scope, receive, _send)
Feb 28 17:58:07 poetry[619976]:   File "/home/bitcoin/lnbits-legend/lnbits/middleware.py", line 73, in __call__
Feb 28 17:58:07 poetry[619976]:     await self.app(scope, receive, send)
Feb 28 17:58:07 poetry[619976]:   File "/home/bitcoin/lnbits-legend/lnbits/middleware.py", line 52, in __call__
Feb 28 17:58:07 poetry[619976]:     await self.app(scope, receive, send)
Feb 28 17:58:07 poetry[619976]:   File "/home/bitcoin/.cache/pypoetry/virtualenvs/lnbits-YwOF1MmK-py3.9/lib/python3.9/site-packages/starlette/middleware/gzip.py", line 24, in __call__
Feb 28 17:58:07 poetry[619976]:     await responder(scope, receive, send)
Feb 28 17:58:07 poetry[619976]:   File "/home/bitcoin/.cache/pypoetry/virtualenvs/lnbits-YwOF1MmK-py3.9/lib/python3.9/site-packages/starlette/middleware/gzip.py", line 43, in __call__
Feb 28 17:58:07 poetry[619976]:     await self.app(scope, receive, self.send_with_gzip)
Feb 28 17:58:07 poetry[619976]:   File "/home/bitcoin/.cache/pypoetry/virtualenvs/lnbits-YwOF1MmK-py3.9/lib/python3.9/site-packages/starlette/middleware/cors.py", line 92, in __call__
Feb 28 17:58:07 poetry[619976]:     await self.simple_response(scope, receive, send, request_headers=headers)
Feb 28 17:58:07 poetry[619976]:   File "/home/bitcoin/.cache/pypoetry/virtualenvs/lnbits-YwOF1MmK-py3.9/lib/python3.9/site-packages/starlette/middleware/cors.py", line 147, in simple_response
Feb 28 17:58:07 poetry[619976]:     await self.app(scope, receive, send)
Feb 28 17:58:07 poetry[619976]:   File "/home/bitcoin/.cache/pypoetry/virtualenvs/lnbits-YwOF1MmK-py3.9/lib/python3.9/site-packages/starlette/exceptions.py", line 93, in __call__
Feb 28 17:58:07 poetry[619976]:     raise exc
Feb 28 17:58:07 poetry[619976]:   File "/home/bitcoin/.cache/pypoetry/virtualenvs/lnbits-YwOF1MmK-py3.9/lib/python3.9/site-packages/starlette/exceptions.py", line 82, in __call__
Feb 28 17:58:07 poetry[619976]:     await self.app(scope, receive, sender)
Feb 28 17:58:07 poetry[619976]:   File "/home/bitcoin/.cache/pypoetry/virtualenvs/lnbits-YwOF1MmK-py3.9/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
Feb 28 17:58:07 poetry[619976]:     raise e
Feb 28 17:58:07 poetry[619976]:   File "/home/bitcoin/.cache/pypoetry/virtualenvs/lnbits-YwOF1MmK-py3.9/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
Feb 28 17:58:07 poetry[619976]:     await self.app(scope, receive, send)
Feb 28 17:58:07 poetry[619976]:   File "/home/bitcoin/.cache/pypoetry/virtualenvs/lnbits-YwOF1MmK-py3.9/lib/python3.9/site-packages/starlette/routing.py", line 670, in __call__
Feb 28 17:58:07 poetry[619976]:     await route.handle(scope, receive, send)
Feb 28 17:58:07 poetry[619976]:   File "/home/bitcoin/.cache/pypoetry/virtualenvs/lnbits-YwOF1MmK-py3.9/lib/python3.9/site-packages/starlette/routing.py", line 266, in handle
Feb 28 17:58:07 poetry[619976]:     await self.app(scope, receive, send)
Feb 28 17:58:07 poetry[619976]:   File "/home/bitcoin/.cache/pypoetry/virtualenvs/lnbits-YwOF1MmK-py3.9/lib/python3.9/site-packages/starlette/routing.py", line 65, in app
Feb 28 17:58:07 poetry[619976]:     response = await func(request)
Feb 28 17:58:07 poetry[619976]:   File "/home/bitcoin/.cache/pypoetry/virtualenvs/lnbits-YwOF1MmK-py3.9/lib/python3.9/site-packages/fastapi/routing.py", line 231, in app
Feb 28 17:58:07 poetry[619976]:     raw_response = await run_endpoint_function(
Feb 28 17:58:07 poetry[619976]:   File "/home/bitcoin/.cache/pypoetry/virtualenvs/lnbits-YwOF1MmK-py3.9/lib/python3.9/site-packages/fastapi/routing.py", line 160, in run_endpoint_function
Feb 28 17:58:07 poetry[619976]:     return await dependant.call(**values)
Feb 28 17:58:07 poetry[619976]:   File "/home/bitcoin/lnbits-legend/lnbits/core/views/api.py", line 357, in api_payments_pay_lnurl
Feb 28 17:58:07 poetry[619976]:     payment_hash = await pay_invoice(
Feb 28 17:58:07 poetry[619976]:   File "/home/bitcoin/lnbits-legend/lnbits/core/services.py", line 239, in pay_invoice
Feb 28 17:58:07 poetry[619976]:     raise PaymentFailure(
Feb 28 17:58:07 poetry[619976]: lnbits.core.services.PaymentFailure: Payment failed: CLN method 'pay' failed with 'bolt11 uses description_hash, but you did not provide description parameter'.
```

**Desktop (please complete the following information):**
 - LNbits version: https://github.com/lnbits/lnbits/commit/6f194fe2f8efa13d67bfb5fd3e18d91d896699cd
 - Database postgres 14

**Additional context**
the bolt11 has no description and a description hash which is fine, but cln wants the description in its pay method as an extra parameter to check if the hash is correct. Lnbits does not pass the description to the pay_invoice function in any way.

**Comment by daywalker90** [comment]
duplicate of #625 i think, closing for now
