### ISSUE TITLE
[BUG] Update from 239f166a141fa9347ba7ab958c80cbc8804bd8b8 commit to fe315d0a9b97f360c1540509654dce91568bdf45 failed

### ISSUE THREAD

**Issue by Perlover** [lnbits/lnbits#1635]
**Describe the bug**

I updated by instruction the version from `239f166a141fa9347ba7ab958c80cbc8804bd8b8` commit to `fe315d0a9b97f360c1540509654dce91568bdf45` and cannot run - throw error

**To Reproduce**
1. Install `239f166a141fa9347ba7ab958c80cbc8804bd8b8` commit version
2. Set up the config AdminUI version and LndRestWallet type
3. Everything works fine (REST point is OK, macaroon is OK)
4. Update through console as described in "Update LNbits" section to `origin/main` branch (the current is `fe315d0a9b97f360c1540509654dce91568bdf45` commit)
5. Restart LNBits and get errors (with same config and with `LNBITS_ADMIN_UI=false` too)
6. If I do downgrade - everything works again

**Additional context**

Error of stack trace after upgrade:

```
2023-04-18 17:26:19.41 | ERROR | cannot initialize lndrest
2023-04-18 17:26:19.41 | ERROR | Traceback (most recent call last):
  File "/home/lnbits/lnbits/lnbits/app.py", line 288, in lnbits_startup
    set_wallet_class()
  File "/home/lnbits/lnbits/lnbits/settings.py", line 326, in set_wallet_class
    WALLET = wallet_class()
  File "/home/lnbits/lnbits/lnbits/wallets/lndrest.py", line 43, in __init__
    raise Exception("cannot initialize lndrest")
Exception: cannot initialize lndrest

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lnbits/.cache/pypoetry/virtualenvs/lnbits-Me3QFGJB-py3.9/lib/python3.9/site-packages/starlette/routing.py", line 635, in lifespan
    async with self.lifespan_context(app):
  File "/home/lnbits/.cache/pypoetry/virtualenvs/lnbits-Me3QFGJB-py3.9/lib/python3.9/site-packages/starlette/routing.py", line 530, in __aenter__
    await self._router.startup()
  File "/home/lnbits/.cache/pypoetry/virtualenvs/lnbits-Me3QFGJB-py3.9/lib/python3.9/site-packages/starlette/routing.py", line 612, in startup
    await handler()
  File "/home/lnbits/lnbits/lnbits/app.py", line 298, in lnbits_startup
    raise ImportError("Failed to run 'startup' event.")
ImportError: Failed to run 'startup' event.

2023-04-18 17:26:19.41 | ERROR | Application startup failed. Exiting.
```

**Comment by Perlover** [comment]
I used the 'git bisect` for founding the bug and got results:

```
git bisect bad
02306148df90a537be494e8450912d52836b2ca6 is the first bad commit
commit 02306148df90a537be494e8450912d52836b2ca6
Author: Pavol Rusnak <pavol@rusnak.io>
Date:   Thu Feb 2 12:58:23 2023 +0000

    fix pyright lnbits
    
    Co-authored-by: dni ⚡ <office@dnilabs.com>

 lnbits/bolt11.py            |  52 ++++++----
 lnbits/commands.py          |   1 +
 lnbits/db.py                |  18 ++--
 lnbits/decorators.py        |  26 +++--
 lnbits/extension_manager.py | 242 +++++++++++++++++++++++++++++++++-----------
 lnbits/jinja2_templating.py |  23 ++---
 lnbits/settings.py          |  12 ++-
 lnbits/tasks.py             |   8 +-
 8 files changed, 266 insertions(+), 116 deletions(-)
```

https://github.com/lnbits/lnbits/commit/02306148df90a537be494e8450912d52836b2ca6

Ping @prusnak

**Comment by Perlover** [comment]
> I used the 'git bisect` for founding the bug and got results:
> 
> ...
> [0230614](https://github.com/lnbits/lnbits/commit/02306148df90a537be494e8450912d52836b2ca6)
> 
> Ping @prusnak

But this commit introduce few other errors:

```
/home/lnbits/.local/bin/poetry run lnbits
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/lnbits/.cache/pypoetry/virtualenvs/lnbits-Me3QFGJB-py3.9/lib/python3.9/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "uvloop/loop.pyx", line 1501, in uvloop.loop.Loop.run_until_complete
  File "/home/lnbits/.cache/pypoetry/virtualenvs/lnbits-Me3QFGJB-py3.9/lib/python3.9/site-packages/uvicorn/server.py", line 67, in serve
    config.load()
  File "/home/lnbits/.cache/pypoetry/virtualenvs/lnbits-Me3QFGJB-py3.9/lib/python3.9/site-packages/uvicorn/config.py", line 479, in load
    self.loaded_app = import_from_string(self.app)
  File "/home/lnbits/.cache/pypoetry/virtualenvs/lnbits-Me3QFGJB-py3.9/lib/python3.9/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/lnbits/lnbits/lnbits/__main__.py", line 1, in <module>
    from .app import create_app
  File "/home/lnbits/lnbits/lnbits/app.py", line 21, in <module>
    from lnbits.core.crud import get_installed_extensions
  File "/home/lnbits/lnbits/lnbits/core/__init__.py", line 3, in <module>
    from lnbits.core.models import CoreAppExtra
  File "/home/lnbits/lnbits/lnbits/core/models.py", line 15, in <module>
    from lnbits.helpers import url_for
  File "/home/lnbits/lnbits/lnbits/helpers.py", line 16, in <module>
    from .extension_manager import get_valid_extensions
  File "/home/lnbits/lnbits/lnbits/extension_manager.py", line 526, in <module>
    class InstalledExtensionMiddleware:
  File "/home/lnbits/lnbits/lnbits/extension_manager.py", line 531, in InstalledExtensionMiddleware
    def __init__(self, app: ASGIApp) -> None:
NameError: name 'ASGIApp' is not defined
^C
Aborted!
```

I will try to find where exactly first bug appears

**Comment by Perlover** [comment]
Exactly same error described as in my first message appears here:

```
486631b4558230184182722083be8cf54a871b22 is the first bad commit
commit 486631b4558230184182722083be8cf54a871b22
Author: dni ⚡ <office@dnilabs.com>
Date:   Thu Feb 23 10:15:39 2023 +0100

    move middleware to middleware.py

 lnbits/extension_manager.py | 46 ---------------------------------------------
 1 file changed, 46 deletions(-)
```

**Comment by prusnak** [comment]
Pinging @dni

**Comment by dni** [comment]
wow, investigating  did not see that at also, also our tests did not catch that, which is very weird..
did you run `poetry install` after pulling?

**Comment by Perlover** [comment]
> wow, investigating did not see that at all, also our tests did not catch that, which is very weird.. did you run `poetry install` after pulling?

I did how described in your install guide:

```
cd lnbits
git pull
poetry self update
poetry install --only main
/home/lnbits/.local/bin/poetry run lnbits
```

**Comment by dni** [comment]
`/home/lnbits/.local/bin/poetry run lnbits` should be `poetry run lnbits` if thats not working what your python version on env `poetry env info`.

**Comment by Perlover** [comment]
> `poetry env info`

```
$ cd lnbits/
$ poetry env info

Virtualenv
Python:         3.9.16
Implementation: CPython
Path:           /home/lnbits/.cache/pypoetry/virtualenvs/lnbits-Me3QFGJB-py3.9
Executable:     /home/lnbits/.cache/pypoetry/virtualenvs/lnbits-Me3QFGJB-py3.9/bin/python
Valid:          True

System
Platform:   linux
OS:         posix
Python:     3.9.16
Path:       /usr
Executable: /usr/bin/python3.9
```

**Comment by dni** [comment]
not it should be automatically pulled on poetry install, via a dependency from fastapi

**Comment by dni** [comment]
can you try `poetry install` without --only main? maybe that helps?

**Comment by Perlover** [comment]
> http://127.0.0.1:5000/wallet?usr=3472987066834ecabefe8152691aada0

I posted private data.... Ohh...

**Comment by Perlover** [comment]
> > http://127.0.0.1:5000/wallet?usr=3472987066834ecabefe8152691aada0
> 
> I posted private data.... Ohh...

May be admin account should not be logged for security reason?

**Comment by dni** [comment]
ok, that kind of looks right, not ASGIApp error? the  question is why no lndrest init? kann you try fakewallet?

**Comment by Perlover** [comment]
> ok, that kind of looks right, not ASGIApp error? the question is why no lndrest init? kann you try fakewallet?

I can checkout to `02306148df90a537be494e8450912d52836b2ca6` commit and will get ASGIApp error

**Comment by dni** [comment]
once you set admin ui to true.
.env doesnt do it anymore, you need to truncate settings table to be newly created

**Comment by dni** [comment]
ok that one it that issue https://github.com/lnbits/lnbits/issues/1184 python3.9...

but it work the issue is literally your rest, i may do a PR make it more clear what actually is missing instead of 1 generic error for all of them

you either missing endpoint, macaroon or ssl cert.

**Comment by Perlover** [comment]
Ok, now I have: admin ui off, LndRestWallet, commit `fe315d0a9b97f360c1540509654dce91568bdf45`,

```
2023-04-19 09:18:13.99 | INFO | Git version: fe315d0a9b97f360c1540509654dce91568bdf45
2023-04-19 09:18:13.99 | INFO | Database: SQLite
2023-04-19 09:18:13.99 | INFO | Service fee: 0.0
2023-04-19 09:18:13.99 | ERROR | cannot initialize lndrest
2023-04-19 09:18:13.99 | ERROR | Traceback (most recent call last):
  File "/home/lnbits/lnbits/lnbits/app.py", line 288, in lnbits_startup
    set_wallet_class()
  File "/home/lnbits/lnbits/lnbits/settings.py", line 326, in set_wallet_class
    WALLET = wallet_class()
  File "/home/lnbits/lnbits/lnbits/wallets/lndrest.py", line 43, in __init__
    raise Exception("cannot initialize lndrest")
Exception: cannot initialize lndrest

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lnbits/.cache/pypoetry/virtualenvs/lnbits-Me3QFGJB-py3.9/lib/python3.9/site-packages/starlette/routing.py", line 635, in lifespan
    async with self.lifespan_context(app):
  File "/home/lnbits/.cache/pypoetry/virtualenvs/lnbits-Me3QFGJB-py3.9/lib/python3.9/site-packages/starlette/routing.py", line 530, in __aenter__
    await self._router.startup()
  File "/home/lnbits/.cache/pypoetry/virtualenvs/lnbits-Me3QFGJB-py3.9/lib/python3.9/site-packages/starlette/routing.py", line 612, in startup
    await handler()
  File "/home/lnbits/lnbits/lnbits/app.py", line 298, in lnbits_startup
    raise ImportError("Failed to run 'startup' event.")
ImportError: Failed to run 'startup' event.

2023-04-19 09:18:13.99 | ERROR | Application startup failed. Exiting.
^C
Aborted!
```

Then I checkout to old `239f166a141fa9347ba7ab958c80cbc8804bd8b8`

```
$ git checkout 239f166a141fa9347ba7ab958c80cbc8804bd8b8
Previous HEAD position was fe315d0a FEAT: remove python 3.7 and update dependencies (#1629)
HEAD is now at 239f166a fix: format relative path
$ poetry self update
Updating Poetry version ...

Using version ^1.4.2 for poetry

Updating dependencies
Resolving dependencies... (0.5s)

No dependencies to install or update
$ poetry install
Installing dependencies from lock file

Package operations: 0 installs, 8 updates, 0 removals

  • Updating wrapt (1.15.0 -> 1.14.1)
  • Updating astroid (2.15.2 -> 2.14.1)
  • Updating coverage (7.2.3 -> 7.1.0)
  • Updating isort (5.12.0 -> 5.11.5)
  • Updating pathspec (0.11.1 -> 0.11.0)
  • Updating platformdirs (3.2.0 -> 2.6.2)
  • Updating tomlkit (0.11.7 -> 0.11.6)
  • Updating pylint (2.17.2 -> 2.16.1)

Preparing build environment with build-system requirements poetry-core>=1.0.0, pyscss
Installing the current project: lnbits (0.10.3)
$ /home/lnbits/.local/bin/poetry run lnbits
...
2023-04-19 09:20:25.28 | INFO | Started server process [2140799]
2023-04-19 09:20:25.28 | INFO | Waiting for application startup.
2023-04-19 09:20:25.91 | INFO | ✔️ All migrations done.
2023-04-19 09:20:25.91 | INFO | Starting LNbits
2023-04-19 09:20:25.91 | INFO | Baseurl: http://127.0.0.1:5000/
2023-04-19 09:20:25.91 | INFO | Host: 127.0.0.1
2023-04-19 09:20:25.91 | INFO | Port: 5000
2023-04-19 09:20:25.91 | INFO | Debug: False
2023-04-19 09:20:25.91 | INFO | Site title: LNbits
2023-04-19 09:20:25.91 | INFO | Funding source: LndRestWallet
2023-04-19 09:20:25.91 | INFO | Data folder: ./data
2023-04-19 09:20:25.91 | INFO | Git version: 239f166a141fa9347ba7ab958c80cbc8804bd8b8
2023-04-19 09:20:25.91 | INFO | Database: SQLite
2023-04-19 09:20:25.91 | INFO | Service fee: 0.0
2023-04-19 09:20:25.96 | INFO | ✔️ Backend LndRestWallet connected and with a balance of 1266214000 msat.
2023-04-19 09:20:25.97 | INFO | Application startup complete.
2023-04-19 09:20:25.98 | INFO | Uvicorn running on http://127.0.0.1:5000 (Press CTRL+C to quit)
2023-04-19 09:20:25.98 | INFO | Task: checking all pending payments (incoming=True, outgoing=True) of last 15 days
2023-04-19 09:20:25.98 | INFO | Task: pending check finished for 0 payments (took 0.003 s)
2023-04-19 09:20:25.98 | INFO | Task: expired invoice deletion finished (took 0.001 s)
^C
Aborted!
2023-04-19 09:20:28.38 | INFO | Shutting down
2023-04-19 09:20:28.48 | INFO | Waiting for application shutdown.
2023-04-19 09:20:28.49 | INFO | Application shutdown complete.
2023-04-19 09:20:28.49 | INFO | Finished server process [2140799]
```

So same credentials when admin ui off work

**Comment by Perlover** [comment]
> you either missing endpoint, macaroon or ssl cert.

I have endpoint and macaroon and cert disabled in .env because I use Let's Encrypt valid certificate at the endpoint (I use BTCPay server)

**Comment by Perlover** [comment]
> ok that one it that issue #1184 python3.9...

I can try python3.10 but few later. Will do it?

**Comment by dni** [comment]
ok, yeah i think the issue is we always expect a ssl cert else  we will raise an exception

**Comment by Perlover** [comment]
> ok, yeah i think the issue is we always expect a ssl cert else we will raise an exception

But no exception when I use commit `239f166a141fa9347ba7ab958c80cbc8804bd8b8`
And very strange to copy certificate for valid CA centers

**Comment by Perlover** [comment]
python3.10

```
$ poetry env info

Virtualenv
Python:         3.10.11
Implementation: CPython
Path:           /home/lnbits/.cache/pypoetry/virtualenvs/lnbits-Me3QFGJB-py3.10
Executable:     /home/lnbits/.cache/pypoetry/virtualenvs/lnbits-Me3QFGJB-py3.10/bin/python
Valid:          True

System
Platform:   linux
OS:         posix
Python:     3.10.11
Path:       /usr
Executable: /usr/bin/python3.10

2023-04-19 09:34:58.81 | ERROR | cannot initialize lndrest
2023-04-19 09:34:58.81 | ERROR | Traceback (most recent call last):
  File "/home/lnbits/lnbits/lnbits/app.py", line 288, in lnbits_startup
    set_wallet_class()
  File "/home/lnbits/lnbits/lnbits/settings.py", line 326, in set_wallet_class
    WALLET = wallet_class()
  File "/home/lnbits/lnbits/lnbits/wallets/lndrest.py", line 43, in __init__
    raise Exception("cannot initialize lndrest")
Exception: cannot initialize lndrest

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lnbits/.cache/pypoetry/virtualenvs/lnbits-Me3QFGJB-py3.10/lib/python3.10/site-packages/starlette/routing.py", line 635, in lifespan
    async with self.lifespan_context(app):
  File "/home/lnbits/.cache/pypoetry/virtualenvs/lnbits-Me3QFGJB-py3.10/lib/python3.10/site-packages/starlette/routing.py", line 530, in __aenter__
    await self._router.startup()
  File "/home/lnbits/.cache/pypoetry/virtualenvs/lnbits-Me3QFGJB-py3.10/lib/python3.10/site-packages/starlette/routing.py", line 612, in startup
    await handler()
  File "/home/lnbits/lnbits/lnbits/app.py", line 298, in lnbits_startup
    raise ImportError("Failed to run 'startup' event.")
ImportError: Failed to run 'startup' event.

2023-04-19 09:34:58.81 | ERROR | Application startup failed. Exiting.
^C
Aborted!
```

So v3.10 - same error

**Comment by Perlover** [comment]
> ok, yeah i think the issue is we always expect a ssl cert else we will raise an exception

I think it's not right

Firstly, your old version works without a certificate. Secondly, the endpoint can be located on a server where I do not have access, and where the certificate of the center Lets'encrypt, for example. Should I ask the administrator to send me a new certificate every two months (when renewed)?

**Comment by dni** [comment]
i agree, it the first time though i saw it that it is possible to use lndrest with a letsencrypt certificate. maybe it should be just a warning stating, `no certificate for lndrest provided, this only works if you have a publicly issues certificate`.

**Comment by dni** [comment]
can you try the above PR if that is working for you?

**Comment by dni** [comment]
https://github.com/lnbits/lnbits/pull/1636 this one :)

**Comment by Perlover** [comment]
> #1636 this one :)

The patch works! Thanks!

```
2023-04-19 16:27:48.04 | INFO | Started server process [2146612]
2023-04-19 16:27:48.04 | INFO | Waiting for application startup.
2023-04-19 16:27:48.70 | INFO | ✔️ All migrations done.
2023-04-19 16:27:48.70 | INFO | Starting LNbits
2023-04-19 16:27:48.70 | INFO | Version: 0.10.3
2023-04-19 16:27:48.70 | INFO | Baseurl: http://127.0.0.1:5000/
2023-04-19 16:27:48.70 | INFO | Host: 127.0.0.1
2023-04-19 16:27:48.70 | INFO | Port: 5000
2023-04-19 16:27:48.70 | INFO | Debug: False
2023-04-19 16:27:48.70 | INFO | Site title: LNbits
2023-04-19 16:27:48.70 | INFO | Funding source: LndRestWallet
2023-04-19 16:27:48.70 | INFO | Data folder: ./data
2023-04-19 16:27:48.70 | INFO | Git version: adae3b4302756f3d75498f8fb05658a9a565aa9c
2023-04-19 16:27:48.70 | INFO | Database: SQLite
2023-04-19 16:27:48.70 | INFO | Service fee: 0.0
2023-04-19 16:27:48.70 | WARNING | no certificate for lndrest provided, this only works if you have a publicly issued certificate
2023-04-19 16:27:48.75 | INFO | ✔️ Backend LndRestWallet connected and with a balance of 1266214000 msat.
2023-04-19 16:27:48.77 | INFO | Application startup complete.
2023-04-19 16:27:48.77 | INFO | Uvicorn running on http://127.0.0.1:5000 (Press CTRL+C to quit)
2023-04-19 16:27:48.77 | INFO | Task: checking all pending payments (incoming=True, outgoing=True) of last 15 days
2023-04-19 16:27:48.78 | INFO | Task: pending check finished for 0 payments (took 0.004 s)
2023-04-19 16:27:48.78 | INFO | Task: expired invoice deletion finished (took 0.001 s)
```

**Comment by dni** [comment]
truncating the settings table will work it will regenerate an admin each time

**Comment by Perlover** [comment]
> truncating the settings table will work it will regenerate the superuser each time

I found in docs [other way](https://github.com/lnbits/lnbits/wiki/LNbits-Documentation#install-options)

> "After the settings are "reset to defaults" and restarted a new super user is created".

I started the server in admin ui and pressed the "RESET TO DEFAULTS". So now I have other admin ui user ;-)

**Comment by Perlover** [comment]
Can you merge this with `main` branch? The patch works but it's not in `main` branch yet

**Comment by dni** [comment]
which one?

**Comment by Perlover** [comment]
> which one?

This one:

https://github.com/lnbits/lnbits/issues/1635#issuecomment-1514352436

**Comment by Perlover** [comment]
I applied this patch by same way:

```
git fetch origin pull/1636/head:patch-1636
git checkout patch-1636 
```

**Comment by Perlover** [comment]
> it is merged into main, but not in the latest version

So may be this issue will close?

**Comment by dni** [comment]
yes, closed, patch is merged! and works

**Comment by Perlover** [comment]
I found this commit I think:

https://github.com/lnbits/lnbits/commit/adae3b4302756f3d75498f8fb05658a9a565aa9c
