### ISSUE TITLE
[BUG] sqlite3.OperationalError: unable to open database file

### ISSUE THREAD

**Issue by Perlover** [lnbits/lnbits#1639]
**Describe the bug**

I have LNBits instance at `adae3b4302756f3d75498f8fb05658a9a565aa9c` commit (patch from https://github.com/lnbits/lnbits/pull/1636). And today I found out that all the services are not working (502 error from nginx). Looking into the logs, I saw errors. The restart command was worked out for a very long time (judging by the logs, the processes were hanging).

**Desktop (please complete the following information):**
 - LNbits version: adae3b4302756f3d75498f8fb05658a9a565aa9c
 - Database sqlite

**Additional context**

Errors like this:

```
Apr 20 09:20:11 fuckedbitcoin poetry[2147615]: 2023-04-20 09:20:11.98 | ERROR | caught exception in background task:
Apr 20 09:20:11 fuckedbitcoin poetry[2147615]: 2023-04-20 09:20:11.98 | ERROR | Traceback (most recent call last):
Apr 20 09:20:11 fuckedbitcoin poetry[2147615]:   File "/home/lnbits/.cache/pypoetry/virtualenvs/lnbits-Me3QFGJB-py3.9/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2336, in _wrap_pool_connect
Apr 20 09:20:11 fuckedbitcoin poetry[2147615]:   File "/home/lnbits/.cache/pypoetry/virtualenvs/lnbits-Me3QFGJB-py3.9/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 304, in unique_connection
Apr 20 09:20:11 fuckedbitcoin poetry[2147615]:   File "/home/lnbits/.cache/pypoetry/virtualenvs/lnbits-Me3QFGJB-py3.9/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 778, in _checkout
Apr 20 09:20:11 fuckedbitcoin poetry[2147615]:   File "/home/lnbits/.cache/pypoetry/virtualenvs/lnbits-Me3QFGJB-py3.9/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 495, in checkout
Apr 20 09:20:11 fuckedbitcoin poetry[2147615]:   File "/home/lnbits/.cache/pypoetry/virtualenvs/lnbits-Me3QFGJB-py3.9/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 241, in _do_get
Apr 20 09:20:11 fuckedbitcoin poetry[2147615]:   File "/home/lnbits/.cache/pypoetry/virtualenvs/lnbits-Me3QFGJB-py3.9/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 309, in _create_connection
Apr 20 09:20:11 fuckedbitcoin poetry[2147615]:   File "/home/lnbits/.cache/pypoetry/virtualenvs/lnbits-Me3QFGJB-py3.9/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 440, in __init__
Apr 20 09:20:11 fuckedbitcoin poetry[2147615]:   File "/home/lnbits/.cache/pypoetry/virtualenvs/lnbits-Me3QFGJB-py3.9/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 661, in __connect
Apr 20 09:20:11 fuckedbitcoin poetry[2147615]:   File "/home/lnbits/.cache/pypoetry/virtualenvs/lnbits-Me3QFGJB-py3.9/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
Apr 20 09:20:11 fuckedbitcoin poetry[2147615]:   File "/home/lnbits/.cache/pypoetry/virtualenvs/lnbits-Me3QFGJB-py3.9/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
Apr 20 09:20:11 fuckedbitcoin poetry[2147615]:   File "/home/lnbits/.cache/pypoetry/virtualenvs/lnbits-Me3QFGJB-py3.9/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 656, in __connect
Apr 20 09:20:11 fuckedbitcoin poetry[2147615]:   File "/home/lnbits/.cache/pypoetry/virtualenvs/lnbits-Me3QFGJB-py3.9/lib/python3.9/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
Apr 20 09:20:11 fuckedbitcoin poetry[2147615]:   File "/home/lnbits/.cache/pypoetry/virtualenvs/lnbits-Me3QFGJB-py3.9/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 508, in connect
Apr 20 09:20:11 fuckedbitcoin poetry[2147615]: sqlite3.OperationalError: unable to open database file
Apr 20 09:20:11 fuckedbitcoin poetry[2147615]: The above exception was the direct cause of the following exception:
Apr 20 09:20:11 fuckedbitcoin poetry[2147615]: Traceback (most recent call last):
Apr 20 09:20:11 fuckedbitcoin poetry[2147615]:   File "/home/lnbits/lnbits/lnbits/tasks.py", line 25, in catch_everything_and_restart
Apr 20 09:20:11 fuckedbitcoin poetry[2147615]:     await func()
Apr 20 09:20:11 fuckedbitcoin poetry[2147615]:   File "/home/lnbits/lnbits/lnbits/tasks.py", line 128, in check_pending_payments
Apr 20 09:20:11 fuckedbitcoin poetry[2147615]:     async with db.connect() as conn:
Apr 20 09:20:11 fuckedbitcoin poetry[2147615]:   File "/usr/lib/python3.9/contextlib.py", line 181, in __aenter__
Apr 20 09:20:11 fuckedbitcoin poetry[2147615]:   File "/home/lnbits/lnbits/lnbits/db.py", line 188, in connect
Apr 20 09:20:11 fuckedbitcoin poetry[2147615]:   File "/home/lnbits/.cache/pypoetry/virtualenvs/lnbits-Me3QFGJB-py3.9/lib/python3.9/site-packages/sqlalchemy_aio/base.py", line 580, in __aenter__
Apr 20 09:20:11 fuckedbitcoin poetry[2147615]:   File "/home/lnbits/.cache/pypoetry/virtualenvs/lnbits-Me3QFGJB-py3.9/lib/python3.9/site-packages/sqlalchemy_aio/base.py", line 110, in _make_async_connection
Apr 20 09:20:11 fuckedbitcoin poetry[2147615]:   File "/home/lnbits/.cache/pypoetry/virtualenvs/lnbits-Me3QFGJB-py3.9/lib/python3.9/site-packages/sqlalchemy_aio/asyncio.py", line 70, in run
Apr 20 09:20:11 fuckedbitcoin poetry[2147615]:   File "/home/lnbits/.cache/pypoetry/virtualenvs/lnbits-Me3QFGJB-py3.9/lib/python3.9/site-packages/outcome/_impl.py", line 138, in unwrap
Apr 20 09:20:11 fuckedbitcoin poetry[2147615]:   File "/home/lnbits/.cache/pypoetry/virtualenvs/lnbits-Me3QFGJB-py3.9/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2263, in connect
Apr 20 09:20:11 fuckedbitcoin poetry[2147615]:   File "/home/lnbits/.cache/pypoetry/virtualenvs/lnbits-Me3QFGJB-py3.9/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 104, in __init__
Apr 20 09:20:11 fuckedbitcoin poetry[2147615]:   File "/home/lnbits/.cache/pypoetry/virtualenvs/lnbits-Me3QFGJB-py3.9/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2369, in raw_connection
Apr 20 09:20:11 fuckedbitcoin poetry[2147615]:   File "/home/lnbits/.cache/pypoetry/virtualenvs/lnbits-Me3QFGJB-py3.9/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2339, in _wrap_pool_connect
Apr 20 09:20:11 fuckedbitcoin poetry[2147615]:   File "/home/lnbits/.cache/pypoetry/virtualenvs/lnbits-Me3QFGJB-py3.9/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1583, in _handle_dbapi_exception_noconnection
Apr 20 09:20:11 fuckedbitcoin poetry[2147615]:   File "/home/lnbits/.cache/pypoetry/virtualenvs/lnbits-Me3QFGJB-py3.9/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
Apr 20 09:20:11 fuckedbitcoin poetry[2147615]:   File "/home/lnbits/.cache/pypoetry/virtualenvs/lnbits-Me3QFGJB-py3.9/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2336, in _wrap_pool_connect
Apr 20 09:20:11 fuckedbitcoin poetry[2147615]:   File "/home/lnbits/.cache/pypoetry/virtualenvs/lnbits-Me3QFGJB-py3.9/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 304, in unique_connection
Apr 20 09:20:11 fuckedbitcoin poetry[2147615]:   File "/home/lnbits/.cache/pypoetry/virtualenvs/lnbits-Me3QFGJB-py3.9/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 778, in _checkout
Apr 20 09:20:11 fuckedbitcoin poetry[2147615]:   File "/home/lnbits/.cache/pypoetry/virtualenvs/lnbits-Me3QFGJB-py3.9/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 495, in checkout
Apr 20 09:20:11 fuckedbitcoin poetry[2147615]:   File "/home/lnbits/.cache/pypoetry/virtualenvs/lnbits-Me3QFGJB-py3.9/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 241, in _do_get
Apr 20 09:20:11 fuckedbitcoin poetry[2147615]:   File "/home/lnbits/.cache/pypoetry/virtualenvs/lnbits-Me3QFGJB-py3.9/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 309, in _create_connection
Apr 20 09:20:11 fuckedbitcoin poetry[2147615]:   File "/home/lnbits/.cache/pypoetry/virtualenvs/lnbits-Me3QFGJB-py3.9/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 440, in __init__
Apr 20 09:20:11 fuckedbitcoin poetry[2147615]:   File "/home/lnbits/.cache/pypoetry/virtualenvs/lnbits-Me3QFGJB-py3.9/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 661, in __connect
Apr 20 09:20:11 fuckedbitcoin poetry[2147615]:   File "/home/lnbits/.cache/pypoetry/virtualenvs/lnbits-Me3QFGJB-py3.9/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
Apr 20 09:20:11 fuckedbitcoin poetry[2147615]:   File "/home/lnbits/.cache/pypoetry/virtualenvs/lnbits-Me3QFGJB-py3.9/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
Apr 20 09:20:11 fuckedbitcoin poetry[2147615]:   File "/home/lnbits/.cache/pypoetry/virtualenvs/lnbits-Me3QFGJB-py3.9/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 656, in __connect
Apr 20 09:20:11 fuckedbitcoin poetry[2147615]:   File "/home/lnbits/.cache/pypoetry/virtualenvs/lnbits-Me3QFGJB-py3.9/lib/python3.9/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
Apr 20 09:20:11 fuckedbitcoin poetry[2147615]:   File "/home/lnbits/.cache/pypoetry/virtualenvs/lnbits-Me3QFGJB-py3.9/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 508, in connect
Apr 20 09:20:11 fuckedbitcoin poetry[2147615]: sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) unable to open database file
Apr 20 09:20:11 fuckedbitcoin poetry[2147615]: (Background on this error at: http://sqlalche.me/e/13/e3q8)
Apr 20 09:20:11 fuckedbitcoin poetry[2147615]: 2023-04-20 09:20:11.99 | ERROR | will restart the task in 5 seconds.
```

Logs about stopping:

```
Apr 20 17:51:53 fuckedbitcoin systemd[1]: Stopping LNbits...
Apr 20 17:51:53 fuckedbitcoin poetry[2147615]: 2023-04-20 17:51:53.26 | INFO | Shutting down
Apr 20 17:51:53 fuckedbitcoin poetry[2147615]: 2023-04-20 17:51:53.27 | WARNING | Connection to remote host was lost.
Apr 20 17:51:53 fuckedbitcoin poetry[2147615]: 2023-04-20 17:51:53.28 | ERROR | closing handshake failed
Apr 20 17:51:53 fuckedbitcoin poetry[2147615]: 2023-04-20 17:51:53.28 | INFO | connection closed
Apr 20 17:51:53 fuckedbitcoin poetry[2147615]: 2023-04-20 17:51:53.36 | INFO | Waiting for background tasks to complete. (CTRL+C to force quit)
Apr 20 17:53:53 fuckedbitcoin systemd[1]: lnbits.service: State 'stop-final-sigterm' timed out. Killing.
Apr 20 17:53:53 fuckedbitcoin systemd[1]: lnbits.service: Killing process 2147615 (python) with signal SIGKILL.
Apr 20 17:53:53 fuckedbitcoin systemd[1]: lnbits.service: Killing process 2147648 (python) with signal SIGKILL.
Apr 20 17:53:53 fuckedbitcoin systemd[1]: lnbits.service: Killing process 2147649 (python) with signal SIGKILL.
Apr 20 17:53:53 fuckedbitcoin systemd[1]: lnbits.service: Killing process 2147650 (python) with signal SIGKILL.
Apr 20 17:53:53 fuckedbitcoin systemd[1]: lnbits.service: Killing process 2149118 (python) with signal SIGKILL.
Apr 20 17:53:53 fuckedbitcoin systemd[1]: lnbits.service: Killing process 2149121 (python) with signal SIGKILL.
Apr 20 17:53:53 fuckedbitcoin systemd[1]: lnbits.service: Killing process 2149128 (python) with signal SIGKILL.
Apr 20 17:53:53 fuckedbitcoin systemd[1]: lnbits.service: Killing process 2149130 (python) with signal SIGKILL.
Apr 20 17:53:53 fuckedbitcoin systemd[1]: lnbits.service: Killing process 2149139 (python) with signal SIGKILL.
Apr 20 17:53:53 fuckedbitcoin systemd[1]: lnbits.service: Killing process 2149140 (python) with signal SIGKILL.
Apr 20 17:53:53 fuckedbitcoin systemd[1]: lnbits.service: Killing process 2149141 (python) with signal SIGKILL.
Apr 20 17:53:53 fuckedbitcoin systemd[1]: lnbits.service: Killing process 2149142 (python) with signal SIGKILL.
Apr 20 17:53:53 fuckedbitcoin systemd[1]: lnbits.service: Killing process 2149144 (python) with signal SIGKILL.
Apr 20 17:53:53 fuckedbitcoin systemd[1]: lnbits.service: Killing process 2149146 (python) with signal SIGKILL.
Apr 20 17:53:53 fuckedbitcoin systemd[1]: lnbits.service: Killing process 2149155 (python) with signal SIGKILL.
Apr 20 17:53:53 fuckedbitcoin systemd[1]: lnbits.service: Killing process 2149156 (python) with signal SIGKILL.
Apr 20 17:53:53 fuckedbitcoin systemd[1]: lnbits.service: Killing process 2149157 (python) with signal SIGKILL.
Apr 20 17:53:53 fuckedbitcoin systemd[1]: lnbits.service: Killing process 2149158 (python) with signal SIGKILL.
Apr 20 17:53:53 fuckedbitcoin systemd[1]: lnbits.service: Killing process 2149159 (python) with signal SIGKILL.
Apr 20 17:53:53 fuckedbitcoin systemd[1]: lnbits.service: Killing process 2149160 (python) with signal SIGKILL.
Apr 20 17:53:53 fuckedbitcoin systemd[1]: lnbits.service: Killing process 2149161 (python) with signal SIGKILL.
Apr 20 17:53:53 fuckedbitcoin systemd[1]: lnbits.service: Killing process 2149162 (python) with signal SIGKILL.
Apr 20 17:53:53 fuckedbitcoin systemd[1]: lnbits.service: Killing process 2149164 (python) with signal SIGKILL.
Apr 20 17:53:53 fuckedbitcoin systemd[1]: lnbits.service: Killing process 2149165 (python) with signal SIGKILL.
Apr 20 17:53:53 fuckedbitcoin systemd[1]: lnbits.service: Killing process 2149172 (python) with signal SIGKILL.
Apr 20 17:53:53 fuckedbitcoin systemd[1]: lnbits.service: Killing process 2149173 (python) with signal SIGKILL.
Apr 20 17:53:53 fuckedbitcoin systemd[1]: lnbits.service: Killing process 2149174 (python) with signal SIGKILL.
Apr 20 17:53:53 fuckedbitcoin systemd[1]: lnbits.service: Killing process 2149175 (python) with signal SIGKILL.
Apr 20 17:53:53 fuckedbitcoin systemd[1]: lnbits.service: Killing process 2149176 (python) with signal SIGKILL.
Apr 20 17:53:53 fuckedbitcoin systemd[1]: lnbits.service: Killing process 2149177 (python) with signal SIGKILL.
Apr 20 17:53:53 fuckedbitcoin systemd[1]: lnbits.service: Killing process 2149178 (python) with signal SIGKILL.
Apr 20 17:53:53 fuckedbitcoin systemd[1]: lnbits.service: Killing process 2149179 (python) with signal SIGKILL.
Apr 20 17:53:53 fuckedbitcoin systemd[1]: lnbits.service: Killing process 2149180 (python) with signal SIGKILL.
Apr 20 17:53:53 fuckedbitcoin systemd[1]: lnbits.service: Killing process 2149181 (python) with signal SIGKILL.
Apr 20 17:53:53 fuckedbitcoin systemd[1]: lnbits.service: Killing process 2149183 (python) with signal SIGKILL.
Apr 20 17:53:53 fuckedbitcoin systemd[1]: lnbits.service: Killing process 2149184 (python) with signal SIGKILL.
Apr 20 17:53:53 fuckedbitcoin systemd[1]: lnbits.service: Killing process 2149185 (python) with signal SIGKILL.
Apr 20 17:53:53 fuckedbitcoin systemd[1]: lnbits.service: Killing process 2149196 (python) with signal SIGKILL.
Apr 20 17:53:53 fuckedbitcoin systemd[1]: lnbits.service: Killing process 2149198 (python) with signal SIGKILL.
Apr 20 17:53:53 fuckedbitcoin systemd[1]: lnbits.service: Killing process 2149200 (python) with signal SIGKILL.
Apr 20 17:53:53 fuckedbitcoin systemd[1]: lnbits.service: Killing process 2149202 (python) with signal SIGKILL.
Apr 20 17:53:53 fuckedbitcoin systemd[1]: lnbits.service: Killing process 2149204 (python) with signal SIGKILL.
Apr 20 17:53:53 fuckedbitcoin systemd[1]: lnbits.service: Killing process 2149206 (python) with signal SIGKILL.
Apr 20 17:53:53 fuckedbitcoin systemd[1]: lnbits.service: Killing process 2149207 (python) with signal SIGKILL.
Apr 20 17:53:53 fuckedbitcoin systemd[1]: lnbits.service: Killing process 2149209 (python) with signal SIGKILL.
Apr 20 17:53:53 fuckedbitcoin systemd[1]: lnbits.service: Killing process 2149210 (python) with signal SIGKILL.
Apr 20 17:53:53 fuckedbitcoin systemd[1]: lnbits.service: Killing process 2149211 (python) with signal SIGKILL.
Apr 20 17:53:53 fuckedbitcoin systemd[1]: lnbits.service: Killing process 2149218 (python) with signal SIGKILL.
Apr 20 17:53:53 fuckedbitcoin systemd[1]: lnbits.service: Killing process 2149219 (python) with signal SIGKILL.
Apr 20 17:53:53 fuckedbitcoin systemd[1]: lnbits.service: Killing process 2149220 (python) with signal SIGKILL.
Apr 20 17:53:53 fuckedbitcoin systemd[1]: lnbits.service: Killing process 2149221 (python) with signal SIGKILL.
Apr 20 17:53:53 fuckedbitcoin systemd[1]: lnbits.service: Killing process 2149222 (python) with signal SIGKILL.
Apr 20 17:53:53 fuckedbitcoin systemd[1]: lnbits.service: Killing process 2149223 (python) with signal SIGKILL.
Apr 20 17:53:53 fuckedbitcoin systemd[1]: lnbits.service: Killing process 2149224 (python) with signal SIGKILL.
Apr 20 17:53:53 fuckedbitcoin systemd[1]: lnbits.service: Killing process 2149225 (python) with signal SIGKILL.
Apr 20 17:53:53 fuckedbitcoin systemd[1]: lnbits.service: Killing process 2149226 (python) with signal SIGKILL.
Apr 20 17:53:53 fuckedbitcoin systemd[1]: lnbits.service: Killing process 2149227 (python) with signal SIGKILL.
...
>Apr 20 17:53:53 fuckedbitcoin systemd[1]: lnbits.service: Killing process 2149405 (n/a) with signal SIGKILL.
Apr 20 17:53:53 fuckedbitcoin systemd[1]: lnbits.service: Killing process 2149406 (n/a) with signal SIGKILL.
Apr 20 17:53:53 fuckedbitcoin systemd[1]: lnbits.service: Killing process 2149413 (python) with signal SIGKILL.
Apr 20 17:53:53 fuckedbitcoin systemd[1]: lnbits.service: Killing process 2149416 (n/a) with signal SIGKILL.
Apr 20 17:53:53 fuckedbitcoin systemd[1]: lnbits.service: Killing process 2149418 (python) with signal SIGKILL.
Apr 20 17:53:53 fuckedbitcoin systemd[1]: lnbits.service: Killing process 2149420 (n/a) with signal SIGKILL.
Apr 20 17:53:53 fuckedbitcoin systemd[1]: lnbits.service: Killing process 2149422 (python) with signal SIGKILL.
Apr 20 17:53:53 fuckedbitcoin systemd[1]: lnbits.service: Killing process 2149424 (python) with signal SIGKILL.
Apr 20 17:53:53 fuckedbitcoin systemd[1]: lnbits.service: Killing process 2149425 (python) with signal SIGKILL.
Apr 20 17:53:53 fuckedbitcoin systemd[1]: lnbits.service: Killing process 2149426 (n/a) with signal SIGKILL.
Apr 20 17:53:53 fuckedbitcoin systemd[1]: lnbits.service: Killing process 2149428 (python) with signal SIGKILL.
...
Apr 20 17:53:53 fuckedbitcoin systemd[1]: lnbits.service: Killing process 2150009 (n/a) with signal SIGKILL.
Apr 20 17:53:53 fuckedbitcoin systemd[1]: lnbits.service: Killing process 2150010 (n/a) with signal SIGKILL.
Apr 20 17:53:53 fuckedbitcoin systemd[1]: lnbits.service: Killing process 2150011 (n/a) with signal SIGKILL.
Apr 20 17:53:53 fuckedbitcoin systemd[1]: lnbits.service: Failed to kill control group /system.slice/lnbits.service, ignoring: Input/output error
Apr 20 17:53:53 fuckedbitcoin systemd[1]: lnbits.service: Failed with result 'timeout'.
Apr 20 17:53:53 fuckedbitcoin systemd[1]: Stopped LNbits.
Apr 20 17:53:53 fuckedbitcoin systemd[1]: Started LNbits.
```

But all this was preceded by such an error (I have the nostr client extension installed):

```
pr 20 04:54:31 fuckedbitcoin poetry[2147615]: 2023-04-20 04:54:31.21 | INFO | 170.75.175.50:0 - "GET /api/v1/payments/sse?api-key=XXXXXXXXXXXXXXXXXXXXXXX HTTP/1.1" 200
Apr 20 04:55:31 fuckedbitcoin poetry[2147615]: Traceback (most recent call last):
Apr 20 04:55:31 fuckedbitcoin poetry[2147615]:   File "/home/lnbits/.cache/pypoetry/virtualenvs/lnbits-Me3QFGJB-py3.9/lib/python3.9/site-packages/starlette/middleware/errors.py", line 162, in __call__
Apr 20 04:55:31 fuckedbitcoin poetry[2147615]:     await self.app(scope, receive, _send)
Apr 20 04:55:31 fuckedbitcoin poetry[2147615]:   File "/home/lnbits/lnbits/lnbits/middleware.py", line 74, in __call__
Apr 20 04:55:31 fuckedbitcoin poetry[2147615]:     await self.app(scope, receive, send)
Apr 20 04:55:31 fuckedbitcoin poetry[2147615]:   File "/home/lnbits/lnbits/lnbits/middleware.py", line 53, in __call__
Apr 20 04:55:31 fuckedbitcoin poetry[2147615]:     await self.app(scope, receive, send)
Apr 20 04:55:31 fuckedbitcoin poetry[2147615]:   File "/home/lnbits/.cache/pypoetry/virtualenvs/lnbits-Me3QFGJB-py3.9/lib/python3.9/site-packages/starlette/middleware/gzip.py", line 24, in __call__
Apr 20 04:55:31 fuckedbitcoin poetry[2147615]:     await responder(scope, receive, send)
Apr 20 04:55:31 fuckedbitcoin poetry[2147615]:   File "/home/lnbits/.cache/pypoetry/virtualenvs/lnbits-Me3QFGJB-py3.9/lib/python3.9/site-packages/starlette/middleware/gzip.py", line 43, in __call__
Apr 20 04:55:31 fuckedbitcoin poetry[2147615]:     await self.app(scope, receive, self.send_with_gzip)
Apr 20 04:55:31 fuckedbitcoin poetry[2147615]:   File "/home/lnbits/.cache/pypoetry/virtualenvs/lnbits-Me3QFGJB-py3.9/lib/python3.9/site-packages/starlette/middleware/cors.py", line 84, in __call__
Apr 20 04:55:31 fuckedbitcoin poetry[2147615]:     await self.app(scope, receive, send)
Apr 20 04:55:31 fuckedbitcoin poetry[2147615]:   File "/home/lnbits/.cache/pypoetry/virtualenvs/lnbits-Me3QFGJB-py3.9/lib/python3.9/site-packages/starlette/exceptions.py", line 93, in __call__
Apr 20 04:55:31 fuckedbitcoin poetry[2147615]:     raise exc
Apr 20 04:55:31 fuckedbitcoin poetry[2147615]:   File "/home/lnbits/.cache/pypoetry/virtualenvs/lnbits-Me3QFGJB-py3.9/lib/python3.9/site-packages/starlette/exceptions.py", line 82, in __call__
Apr 20 04:55:31 fuckedbitcoin poetry[2147615]:     await self.app(scope, receive, sender)
Apr 20 04:55:31 fuckedbitcoin poetry[2147615]:   File "/home/lnbits/.cache/pypoetry/virtualenvs/lnbits-Me3QFGJB-py3.9/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
Apr 20 04:55:31 fuckedbitcoin poetry[2147615]:     raise e
Apr 20 04:55:31 fuckedbitcoin poetry[2147615]:   File "/home/lnbits/.cache/pypoetry/virtualenvs/lnbits-Me3QFGJB-py3.9/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
Apr 20 04:55:31 fuckedbitcoin poetry[2147615]:     await self.app(scope, receive, send)
Apr 20 04:55:31 fuckedbitcoin poetry[2147615]:   File "/home/lnbits/.cache/pypoetry/virtualenvs/lnbits-Me3QFGJB-py3.9/lib/python3.9/site-packages/starlette/routing.py", line 670, in __call__
Apr 20 04:55:31 fuckedbitcoin poetry[2147615]:     await route.handle(scope, receive, send)
Apr 20 04:55:31 fuckedbitcoin poetry[2147615]:   File "/home/lnbits/.cache/pypoetry/virtualenvs/lnbits-Me3QFGJB-py3.9/lib/python3.9/site-packages/starlette/routing.py", line 266, in handle
Apr 20 04:55:31 fuckedbitcoin poetry[2147615]:     await self.app(scope, receive, send)
Apr 20 04:55:31 fuckedbitcoin poetry[2147615]:   File "/home/lnbits/.cache/pypoetry/virtualenvs/lnbits-Me3QFGJB-py3.9/lib/python3.9/site-packages/starlette/routing.py", line 68, in app
Apr 20 04:55:31 fuckedbitcoin poetry[2147615]:     await response(scope, receive, send)
Apr 20 04:55:31 fuckedbitcoin poetry[2147615]:   File "/home/lnbits/.cache/pypoetry/virtualenvs/lnbits-Me3QFGJB-py3.9/lib/python3.9/site-packages/sse_starlette/sse.py", line 182, in __call__
Apr 20 04:55:31 fuckedbitcoin poetry[2147615]:     await self.wait()
Apr 20 04:55:31 fuckedbitcoin poetry[2147615]:   File "/home/lnbits/.cache/pypoetry/virtualenvs/lnbits-Me3QFGJB-py3.9/lib/python3.9/site-packages/sse_starlette/sse.py", line 216, in wait
Apr 20 04:55:31 fuckedbitcoin poetry[2147615]:     await self._ping_task
Apr 20 04:55:31 fuckedbitcoin poetry[2147615]:   File "/home/lnbits/.cache/pypoetry/virtualenvs/lnbits-Me3QFGJB-py3.9/lib/python3.9/site-packages/sse_starlette/sse.py", line 259, in _ping
Apr 20 04:55:31 fuckedbitcoin poetry[2147615]:     await send({"type": "http.response.body", "body": ping, "more_body": True})
Apr 20 04:55:31 fuckedbitcoin poetry[2147615]:   File "/home/lnbits/.cache/pypoetry/virtualenvs/lnbits-Me3QFGJB-py3.9/lib/python3.9/site-packages/starlette/exceptions.py", line 79, in sender
Apr 20 04:55:31 fuckedbitcoin poetry[2147615]:     await send(message)
Apr 20 04:55:31 fuckedbitcoin poetry[2147615]:   File "/home/lnbits/.cache/pypoetry/virtualenvs/lnbits-Me3QFGJB-py3.9/lib/python3.9/site-packages/starlette/middleware/gzip.py", line 93, in send_with_gzip
Apr 20 04:55:31 fuckedbitcoin poetry[2147615]:     self.gzip_file.write(body)
Apr 20 04:55:31 fuckedbitcoin poetry[2147615]:   File "/usr/lib/python3.9/gzip.py", line 272, in write
Apr 20 04:55:31 fuckedbitcoin poetry[2147615]:     self._check_not_closed()
Apr 20 04:55:31 fuckedbitcoin poetry[2147615]:   File "/usr/lib/python3.9/_compression.py", line 14, in _check_not_closed
Apr 20 04:55:31 fuckedbitcoin poetry[2147615]:     raise ValueError("I/O operation on closed file")
Apr 20 04:55:31 fuckedbitcoin poetry[2147615]: ValueError: I/O operation on closed file
Apr 20 04:55:31 fuckedbitcoin poetry[2147615]: 2023-04-20 04:55:31.24 | ERROR | Exception: I/O operation on closed file
Apr 20 04:55:31 fuckedbitcoin poetry[2147615]: 2023-04-20 04:55:31.24 | ERROR | Exception in ASGI application
```

I don't know if one is related to the other, perhaps the nostr client is to blame for subsequent errors with opening the database, or these are independent errors.

P.S. After stopping and starting of lnbits systemd service the LNBits works again but sometime I see errors from in logs like the last error described here

**Comment by callebtc** [comment]
```
ValueError: I/O operation on closed file
```

Really not sure what the error could be caused by. Do you use anything else, any other software that accesses the lnbits database?

**Comment by dni** [comment]
it was a gzip payments/sse issue, you can resolve that by disabling compression.
there is also this pr this closes this issue once and for all. https://github.com/lnbits/lnbits/pull/1781
