### ISSUE TITLE
[BUG] LndHub with limit

### ISSUE THREAD

**Issue by callebtc** [lnbits/lnbits#1652]
```
2023-04-24 13:14:03.87 | INFO | xxxxxxxxxx:0 - "GET /lndhub/ext/gettxs?limit=10&offset=0 HTTP/1.1" 500
2023-04-24 13:14:03.87 | ERROR | Exception in ASGI application
ERROR:uvicorn.error:Exception in ASGI application
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/lnbits-3PdPdHve-py3.10/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 404, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/root/.cache/pypoetry/virtualenvs/lnbits-3PdPdHve-py3.10/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/root/.cache/pypoetry/virtualenvs/lnbits-3PdPdHve-py3.10/lib/python3.10/site-packages/fastapi/applications.py", line 269, in __call__
    await super().__call__(scope, receive, send)
  File "/root/.cache/pypoetry/virtualenvs/lnbits-3PdPdHve-py3.10/lib/python3.10/site-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/root/.cache/pypoetry/virtualenvs/lnbits-3PdPdHve-py3.10/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/root/.cache/pypoetry/virtualenvs/lnbits-3PdPdHve-py3.10/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/root/fast/lnbits-legend/lnbits/middleware.py", line 131, in __call__
    await self.app(scope, receive, send)
  File "/root/fast/lnbits-legend/lnbits/middleware.py", line 63, in __call__
    await self.app(scope, receive, send)
  File "/root/.cache/pypoetry/virtualenvs/lnbits-3PdPdHve-py3.10/lib/python3.10/site-packages/starlette/middleware/gzip.py", line 24, in __call__
    await responder(scope, receive, send)
  File "/root/.cache/pypoetry/virtualenvs/lnbits-3PdPdHve-py3.10/lib/python3.10/site-packages/starlette/middleware/gzip.py", line 43, in __call__
    await self.app(scope, receive, self.send_with_gzip)
  File "/root/.cache/pypoetry/virtualenvs/lnbits-3PdPdHve-py3.10/lib/python3.10/site-packages/starlette/middleware/cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "/root/.cache/pypoetry/virtualenvs/lnbits-3PdPdHve-py3.10/lib/python3.10/site-packages/starlette/exceptions.py", line 93, in __call__
    raise exc
  File "/root/.cache/pypoetry/virtualenvs/lnbits-3PdPdHve-py3.10/lib/python3.10/site-packages/starlette/exceptions.py", line 82, in __call__
    await self.app(scope, receive, sender)
  File "/root/.cache/pypoetry/virtualenvs/lnbits-3PdPdHve-py3.10/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/root/.cache/pypoetry/virtualenvs/lnbits-3PdPdHve-py3.10/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/root/.cache/pypoetry/virtualenvs/lnbits-3PdPdHve-py3.10/lib/python3.10/site-packages/starlette/routing.py", line 670, in __call__
    await route.handle(scope, receive, send)
  File "/root/.cache/pypoetry/virtualenvs/lnbits-3PdPdHve-py3.10/lib/python3.10/site-packages/starlette/routing.py", line 266, in handle
    await self.app(scope, receive, send)
  File "/root/.cache/pypoetry/virtualenvs/lnbits-3PdPdHve-py3.10/lib/python3.10/site-packages/starlette/routing.py", line 65, in app
    response = await func(request)
  File "/root/.cache/pypoetry/virtualenvs/lnbits-3PdPdHve-py3.10/lib/python3.10/site-packages/fastapi/routing.py", line 231, in app
    raw_response = await run_endpoint_function(
  File "/root/.cache/pypoetry/virtualenvs/lnbits-3PdPdHve-py3.10/lib/python3.10/site-packages/fastapi/routing.py", line 160, in run_endpoint_function
    return await dependant.call(**values)
  File "/root/fast/lnbits-legend/lnbits/extensions/lndhub/views_api.py", line 121, in lndhub_gettxs
    for payment in await get_payments(
TypeError: get_payments() got an unexpected keyword argument 'limit'
```

**Comment by dni** [comment]
https://github.com/lnbits/lnbits/pull/1613
