### ISSUE TITLE
lntxbot as funding source - payment not sent, but debited from lnbits account

### ISSUE THREAD

**Issue by arcbtc** [lnbits/lnbits#168]
Using lntxbot as a funding source, user had this issue and I was able to replicate 

Payment appears sent in lnbits (take 3)
![image](https://user-images.githubusercontent.com/33088785/113749048-1780a380-9701-11eb-8fdb-7c814f5c709a.png)

But fails to leave lntxbot funding source
![image](https://user-images.githubusercontent.com/33088785/113749086-22d3cf00-9701-11eb-9454-e61ee03b44e7.png)

The 6sat fee is very confusing

**Comment by HamishMacEwan** [comment]
Hi,

This seems similar, albeit reversed.  I paid an invoice from an LNbits account with lntxbot as funding source, using an LNbits account with lntxbot as a funding source and the payment went through but the paying LNbits account was not debited.

Not debited due to this error:
```
Apr 12 21:25:19 flat6 lnbits[24746]: [2021-04-12 21:25:19,113] ERROR in app: Exception on request POST /api/v1/payments
Apr 12 21:25:19 flat6 lnbits[24746]: Traceback (most recent call last):
Apr 12 21:25:19 flat6 lnbits[24746]:   File "/opt/mynode/lnbits/lnbits_venv/lib/python3.7/site-packages/quart_trio/app.py", line 143, in handle_request
Apr 12 21:25:19 flat6 lnbits[24746]:     return await self.full_dispatch_request(request_context)
Apr 12 21:25:19 flat6 lnbits[24746]:   File "/opt/mynode/lnbits/lnbits_venv/lib/python3.7/site-packages/quart_trio/app.py", line 165, in full_dispatch_request
Apr 12 21:25:19 flat6 lnbits[24746]:     result = await self.handle_user_exception(error)
Apr 12 21:25:19 flat6 lnbits[24746]:   File "/opt/mynode/lnbits/lnbits_venv/lib/python3.7/site-packages/quart_trio/app.py", line 178, in handle_user_exception
Apr 12 21:25:19 flat6 lnbits[24746]:     return await super().handle_user_exception(error)
Apr 12 21:25:19 flat6 lnbits[24746]:   File "/opt/mynode/lnbits/lnbits_venv/lib/python3.7/site-packages/quart/app.py", line 1076, in handle_user_exception
Apr 12 21:25:19 flat6 lnbits[24746]:     raise error
Apr 12 21:25:19 flat6 lnbits[24746]:   File "/opt/mynode/lnbits/lnbits_venv/lib/python3.7/site-packages/quart_trio/app.py", line 163, in full_dispatch_request
Apr 12 21:25:19 flat6 lnbits[24746]:     result = await self.dispatch_request(request_context)
Apr 12 21:25:19 flat6 lnbits[24746]:   File "/opt/mynode/lnbits/lnbits_venv/lib/python3.7/site-packages/quart/app.py", line 1882, in dispatch_request
Apr 12 21:25:19 flat6 lnbits[24746]:     return await handler(**request_.view_args)
Apr 12 21:25:19 flat6 lnbits[24746]:   File "/opt/mynode/lnbits/lnbits/decorators.py", line 55, in wrapped_view
Apr 12 21:25:19 flat6 lnbits[24746]:     return await view(**kwargs)
Apr 12 21:25:19 flat6 lnbits[24746]:   File "/opt/mynode/lnbits/lnbits/core/views/api.py", line 139, in api_payments_create
Apr 12 21:25:19 flat6 lnbits[24746]:     return await api_payments_pay_invoice()
Apr 12 21:25:19 flat6 lnbits[24746]:   File "/opt/mynode/lnbits/lnbits/decorators.py", line 28, in wrapped_view
Apr 12 21:25:19 flat6 lnbits[24746]:     return await view(**kwargs)
Apr 12 21:25:19 flat6 lnbits[24746]:   File "/opt/mynode/lnbits/lnbits/decorators.py", line 55, in wrapped_view
Apr 12 21:25:19 flat6 lnbits[24746]:     return await view(**kwargs)
Apr 12 21:25:19 flat6 lnbits[24746]:   File "/opt/mynode/lnbits/lnbits/core/views/api.py", line 121, in api_payments_pay_invoice
Apr 12 21:25:19 flat6 lnbits[24746]:     raise exc
Apr 12 21:25:19 flat6 lnbits[24746]:   File "/opt/mynode/lnbits/lnbits/core/views/api.py", line 114, in api_payments_pay_invoice
Apr 12 21:25:19 flat6 lnbits[24746]:     payment_hash = await pay_invoice(wallet_id=g.wallet.id, payment_request=g.data["bolt11"])
Apr 12 21:25:19 flat6 lnbits[24746]:   File "/opt/mynode/lnbits/lnbits/core/services.py", line 131, in pay_invoice
Apr 12 21:25:19 flat6 lnbits[24746]:     payment: PaymentResponse = WALLET.pay_invoice(payment_request)
Apr 12 21:25:19 flat6 lnbits[24746]:   File "/opt/mynode/lnbits/lnbits/wallets/lntxbot.py", line 84, in pay_invoice
Apr 12 21:25:19 flat6 lnbits[24746]:     checking_id = data["payment_hash"]
Apr 12 21:25:19 flat6 lnbits[24746]: KeyError: 'payment_hash'
Apr 12 21:25:19 flat6 lnbits[24746]: [2021-04-12 21:25:19 +1200] [24747] [ERROR] Error in ASGI Framework
Apr 12 21:25:19 flat6 lnbits[24746]: Traceback (most recent call last):
Apr 12 21:25:19 flat6 lnbits[24746]:   File "/opt/mynode/lnbits/lnbits_venv/lib/python3.7/site-packages/hypercorn/trio/context.py", line 28, in _handle
Apr 12 21:25:19 flat6 lnbits[24746]:     await invoke_asgi(app, scope, receive, send)
Apr 12 21:25:19 flat6 lnbits[24746]:   File "/opt/mynode/lnbits/lnbits_venv/lib/python3.7/site-packages/hypercorn/utils.py", line 219, in invoke_asgi
Apr 12 21:25:19 flat6 lnbits[24746]:     await app(scope, receive, send)
Apr 12 21:25:19 flat6 lnbits[24746]:   File "/opt/mynode/lnbits/lnbits_venv/lib/python3.7/site-packages/quart/app.py", line 2068, in __call__
Apr 12 21:25:19 flat6 lnbits[24746]:     await self.asgi_app(scope, receive, send)
Apr 12 21:25:19 flat6 lnbits[24746]:   File "/opt/mynode/lnbits/lnbits_venv/lib/python3.7/site-packages/quart/app.py", line 2091, in asgi_app
Apr 12 21:25:19 flat6 lnbits[24746]:     await asgi_handler(receive, send)
Apr 12 21:25:19 flat6 lnbits[24746]:   File "/opt/mynode/lnbits/lnbits_venv/lib/python3.7/site-packages/quart_trio/asgi.py", line 18, in __call__
Apr 12 21:25:19 flat6 lnbits[24746]:     nursery.start_soon(self.handle_request, nursery, request, send)
Apr 12 21:25:19 flat6 lnbits[24746]:   File "/opt/mynode/lnbits/lnbits_venv/lib/python3.7/site-packages/trio/_core/_run.py", line 741, in __aexit__
Apr 12 21:25:19 flat6 lnbits[24746]:     raise combined_error_from_nursery
Apr 12 21:25:19 flat6 lnbits[24746]:   File "/opt/mynode/lnbits/lnbits_venv/lib/python3.7/site-packages/quart_trio/asgi.py", line 29, in handle_request
Apr 12 21:25:19 flat6 lnbits[24746]:     response = await self.app.handle_request(request)
Apr 12 21:25:19 flat6 lnbits[24746]:   File "/opt/mynode/lnbits/lnbits_venv/lib/python3.7/site-packages/quart_trio/app.py", line 147, in handle_request
Apr 12 21:25:19 flat6 lnbits[24746]:     return await self.handle_exception(error)
Apr 12 21:25:19 flat6 lnbits[24746]:   File "/opt/mynode/lnbits/lnbits_venv/lib/python3.7/site-packages/quart/app.py", line 1090, in handle_exception
Apr 12 21:25:19 flat6 lnbits[24746]:     raise error
Apr 12 21:25:19 flat6 lnbits[24746]:   File "/opt/mynode/lnbits/lnbits_venv/lib/python3.7/site-packages/quart_trio/app.py", line 143, in handle_request
Apr 12 21:25:19 flat6 lnbits[24746]:     return await self.full_dispatch_request(request_context)
Apr 12 21:25:19 flat6 lnbits[24746]:   File "/opt/mynode/lnbits/lnbits_venv/lib/python3.7/site-packages/quart_trio/app.py", line 165, in full_dispatch_request
Apr 12 21:25:19 flat6 lnbits[24746]:     result = await self.handle_user_exception(error)
Apr 12 21:25:19 flat6 lnbits[24746]:   File "/opt/mynode/lnbits/lnbits_venv/lib/python3.7/site-packages/quart_trio/app.py", line 178, in handle_user_exception
Apr 12 21:25:19 flat6 lnbits[24746]:     return await super().handle_user_exception(error)
Apr 12 21:25:19 flat6 lnbits[24746]:   File "/opt/mynode/lnbits/lnbits_venv/lib/python3.7/site-packages/quart/app.py", line 1076, in handle_user_exception
Apr 12 21:25:19 flat6 lnbits[24746]:     raise error
Apr 12 21:25:19 flat6 lnbits[24746]:   File "/opt/mynode/lnbits/lnbits_venv/lib/python3.7/site-packages/quart_trio/app.py", line 163, in full_dispatch_request
Apr 12 21:25:19 flat6 lnbits[24746]:     result = await self.dispatch_request(request_context)
Apr 12 21:25:19 flat6 lnbits[24746]:   File "/opt/mynode/lnbits/lnbits_venv/lib/python3.7/site-packages/quart/app.py", line 1882, in dispatch_request
Apr 12 21:25:19 flat6 lnbits[24746]:     return await handler(**request_.view_args)
Apr 12 21:25:19 flat6 lnbits[24746]:   File "/opt/mynode/lnbits/lnbits/decorators.py", line 55, in wrapped_view
Apr 12 21:25:19 flat6 lnbits[24746]:     return await view(**kwargs)
Apr 12 21:25:19 flat6 lnbits[24746]:   File "/opt/mynode/lnbits/lnbits/core/views/api.py", line 139, in api_payments_create
Apr 12 21:25:19 flat6 lnbits[24746]:     return await api_payments_pay_invoice()
Apr 12 21:25:19 flat6 lnbits[24746]:   File "/opt/mynode/lnbits/lnbits/decorators.py", line 28, in wrapped_view
Apr 12 21:25:19 flat6 lnbits[24746]:     return await view(**kwargs)
Apr 12 21:25:19 flat6 lnbits[24746]:   File "/opt/mynode/lnbits/lnbits/decorators.py", line 55, in wrapped_view
Apr 12 21:25:19 flat6 lnbits[24746]:     return await view(**kwargs)
Apr 12 21:25:19 flat6 lnbits[24746]:   File "/opt/mynode/lnbits/lnbits/core/views/api.py", line 121, in api_payments_pay_invoice
Apr 12 21:25:19 flat6 lnbits[24746]:     raise exc
Apr 12 21:25:19 flat6 lnbits[24746]:   File "/opt/mynode/lnbits/lnbits/core/views/api.py", line 114, in api_payments_pay_invoice
Apr 12 21:25:19 flat6 lnbits[24746]:     payment_hash = await pay_invoice(wallet_id=g.wallet.id, payment_request=g.data["bolt11"])
Apr 12 21:25:19 flat6 lnbits[24746]:   File "/opt/mynode/lnbits/lnbits/core/services.py", line 131, in pay_invoice
Apr 12 21:25:19 flat6 lnbits[24746]:     payment: PaymentResponse = WALLET.pay_invoice(payment_request)
Apr 12 21:25:19 flat6 lnbits[24746]:   File "/opt/mynode/lnbits/lnbits/wallets/lntxbot.py", line 84, in pay_invoice
Apr 12 21:25:19 flat6 lnbits[24746]:     checking_id = data["payment_hash"]
Apr 12 21:25:19 flat6 lnbits[24746]: KeyError: 'payment_hash'
```

**Comment by fiatjaf** [comment]
I think that is fixed. Are you running `master`?

**Comment by HamishMacEwan** [comment]
Apologies for the slow response.

I was running the version at this commit:

https://github.com/lnbits/lnbits/commit/946279674a457fbb1f9c575b5aa3638d5f0242cb

from master.

Just about to update to the latest.

**Comment by arcbtc** [comment]
Fixed for me on latest master
