### ISSUE TITLE
lnbits on debian 12

### ISSUE THREAD

**Issue by daywalker90** [lnbits/lnbits#1755]
Debian 12 just got released as stable and i upgraded to it.
It comes with python3.11.
I tried to get lnbits to work with the poetry method.
I got several errors i could solve by updating 2 dependcies: uvloop to 0.17.0 and psycopg2-binary to 2.9.6
I also ran `poetry env use python3.11`
Now lnbits starts without errors but apparently postgres is making trouble and lnbits logs say:
```
2023-06-12 04:47:30.41 | WARNING | Unsupported upgrade request.
WARNING:uvicorn.error:Unsupported upgrade request.
```
Same error shown in the browser.
tested with 0.10.8

**Comment by daywalker90** [comment]
i checked out [bug/security-issues-packages](https://github.com/lnbits/lnbits/tree/bug/security-issues-packages) @ c38ece66db8ba914347fb3d9aec130e651e2ea95 and i had to update psycopg2-binary and remove extensions copilot and withdraw to get lnbits running on debian 12 again. These 2 extensions gave a similar error:
```
Jun 28 13:34:52  poetry[2588474]: 2023-06-28 13:34:52.63 | ERROR | lnbits.app:register_routes:250 | Cannot use `Query` for path param 'link_id'
Jun 28 13:34:52  poetry[2588474]: Process Process-1:
Jun 28 13:34:52  poetry[2588474]: Traceback (most recent call last):
Jun 28 13:34:52  poetry[2588474]:   File "/usr/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
Jun 28 13:34:52  poetry[2588474]:     self.run()
Jun 28 13:34:52  poetry[2588474]:   File "/usr/lib/python3.11/multiprocessing/process.py", line 108, in run
Jun 28 13:34:52  poetry[2588474]:     self._target(*self._args, **self._kwargs)
Jun 28 13:34:52  poetry[2588474]:   File "/home/bitcoin/.cache/pypoetry/virtualenvs/lnbits-YwOF1MmK-py3.11/lib/python3.11/site-packages/uvicorn/server.py", line 59, in run
Jun 28 13:34:52  poetry[2588474]:     return asyncio.run(self.serve(sockets=sockets))
Jun 28 13:34:52  poetry[2588474]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Jun 28 13:34:52  poetry[2588474]:   File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run
Jun 28 13:34:52  poetry[2588474]:     return runner.run(main)
Jun 28 13:34:52  poetry[2588474]:            ^^^^^^^^^^^^^^^^
Jun 28 13:34:52  poetry[2588474]:   File "/usr/lib/python3.11/asyncio/runners.py", line 118, in run
Jun 28 13:34:52  poetry[2588474]:     return self._loop.run_until_complete(task)
Jun 28 13:34:52  poetry[2588474]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Jun 28 13:34:52  poetry[2588474]:   File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
Jun 28 13:34:52  poetry[2588474]:   File "/home/bitcoin/.cache/pypoetry/virtualenvs/lnbits-YwOF1MmK-py3.11/lib/python3.11/site-packages/uvicorn/server.py", line 66, in serve
Jun 28 13:34:52  poetry[2588474]:     config.load()
Jun 28 13:34:52  poetry[2588474]:   File "/home/bitcoin/.cache/pypoetry/virtualenvs/lnbits-YwOF1MmK-py3.11/lib/python3.11/site-packages/uvicorn/config.py", line 471, in load
Jun 28 13:34:52  poetry[2588474]:     self.loaded_app = import_from_string(self.app)
Jun 28 13:34:52  poetry[2588474]:                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Jun 28 13:34:52  poetry[2588474]:   File "/home/bitcoin/.cache/pypoetry/virtualenvs/lnbits-YwOF1MmK-py3.11/lib/python3.11/site-packages/uvicorn/importer.py", line 24, in import_from_string
Jun 28 13:34:52  poetry[2588474]:     raise exc from None
Jun 28 13:34:52  poetry[2588474]:   File "/home/bitcoin/.cache/pypoetry/virtualenvs/lnbits-YwOF1MmK-py3.11/lib/python3.11/site-packages/uvicorn/importer.py", line 21, in import_from_string
Jun 28 13:34:52  poetry[2588474]:     module = importlib.import_module(module_str)
Jun 28 13:34:52  poetry[2588474]:              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Jun 28 13:34:52  poetry[2588474]:   File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
Jun 28 13:34:52  poetry[2588474]:     return _bootstrap._gcd_import(name[level:], package, level)
Jun 28 13:34:52  poetry[2588474]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Jun 28 13:34:52  poetry[2588474]:   File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
Jun 28 13:34:52  poetry[2588474]:   File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
Jun 28 13:34:52  poetry[2588474]:   File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
Jun 28 13:34:52  poetry[2588474]:   File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
Jun 28 13:34:52  poetry[2588474]:   File "<frozen importlib._bootstrap_external>", line 940, in exec_module
Jun 28 13:34:52  poetry[2588474]:   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
Jun 28 13:34:52  poetry[2588474]:   File "/home/bitcoin/lnbits-legend/lnbits/__main__.py", line 3, in <module>
Jun 28 13:34:52  poetry[2588474]:     app = create_app()
Jun 28 13:34:52  poetry[2588474]:           ^^^^^^^^^^^^
Jun 28 13:34:52  poetry[2588474]:   File "/home/bitcoin/lnbits-legend/lnbits/app.py", line 101, in create_app
Jun 28 13:34:52  poetry[2588474]:     register_routes(app)
Jun 28 13:34:52  poetry[2588474]:   File "/home/bitcoin/lnbits-legend/lnbits/app.py", line 251, in register_routes
Jun 28 13:34:52  poetry[2588474]:     raise ImportError(
Jun 28 13:34:52  poetry[2588474]: ImportError: Please make sure that the extension `withdraw` follows conventions.
```

**Comment by daywalker90** [comment]
Ah there was an update for withdraw in the meantime, so withdraw actually works.

**Comment by dni** [comment]
yep, copilot should work aswell, thanks for the review updating, psycog now.!

**Comment by daywalker90** [comment]
My lightning address from lnurl-p is broken after this. 
```
 2023-06-28 13:54:33.63 | INFO | 2a02:8108:8ac0:207b:f3b7:f96e:bb64:1ae:0 - "GET /lnurlp/api/v1/well-known/daywalker HTTP/1.1" 500
 2023-06-28 13:54:33.63 | ERROR | Exception in ASGI application
 Traceback (most recent call last):
   File "/home/bitcoin/.cache/pypoetry/virtualenvs/lnbits-YwOF1MmK-py3.11/lib/python3.11/site-packages/anyio/streams/memory.py", line 98, in receive
     return self.receive_nowait()
            ^^^^^^^^^^^^^^^^^^^^^
   File "/home/bitcoin/.cache/pypoetry/virtualenvs/lnbits-YwOF1MmK-py3.11/lib/python3.11/site-packages/anyio/streams/memory.py", line 93, in receive_nowait
     raise WouldBlock
 anyio.WouldBlock
 During handling of the above exception, another exception occurred:
 Traceback (most recent call last):
   File "/home/bitcoin/.cache/pypoetry/virtualenvs/lnbits-YwOF1MmK-py3.11/lib/python3.11/site-packages/starlette/middleware/base.py", line 78, in call_next
     message = await recv_stream.receive()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/home/bitcoin/.cache/pypoetry/virtualenvs/lnbits-YwOF1MmK-py3.11/lib/python3.11/site-packages/anyio/streams/memory.py", line 118, in receive
     raise EndOfStream
 anyio.EndOfStream
 During handling of the above exception, another exception occurred:
 Traceback (most recent call last):
   File "/home/bitcoin/.cache/pypoetry/virtualenvs/lnbits-YwOF1MmK-py3.11/lib/python3.11/site-packages/starlette/middleware/errors.py", line 162, in __call__
     await self.app(scope, receive, _send)
   File "/home/bitcoin/.cache/pypoetry/virtualenvs/lnbits-YwOF1MmK-py3.11/lib/python3.11/site-packages/starlette/middleware/base.py", line 108, in __call__
     response = await self.dispatch_func(request, call_next)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/home/bitcoin/.cache/pypoetry/virtualenvs/lnbits-YwOF1MmK-py3.11/lib/python3.11/site-packages/slowapi/middleware.py", line 128, in dispatch
     return await call_next(request)
            ^^^^^^^^^^^^^^^^^^^^^^^^
   File "/home/bitcoin/.cache/pypoetry/virtualenvs/lnbits-YwOF1MmK-py3.11/lib/python3.11/site-packages/starlette/middleware/base.py", line 84, in call_next
     raise app_exc
   File "/home/bitcoin/.cache/pypoetry/virtualenvs/lnbits-YwOF1MmK-py3.11/lib/python3.11/site-packages/starlette/middleware/base.py", line 70, in coro
     await self.app(scope, receive_or_disconnect, send_no_error)
   File "/home/bitcoin/.cache/pypoetry/virtualenvs/lnbits-YwOF1MmK-py3.11/lib/python3.11/site-packages/starlette/middleware/base.py", line 108, in __call__
     response = await self.dispatch_func(request, call_next)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/home/bitcoin/lnbits-legend/lnbits/middleware.py", line 208, in block_allow_ip_middleware
     response = await call_next(request)
                ^^^^^^^^^^^^^^^^^^^^^^^^
   File "/home/bitcoin/.cache/pypoetry/virtualenvs/lnbits-YwOF1MmK-py3.11/lib/python3.11/site-packages/starlette/middleware/base.py", line 84, in call_next
     raise app_exc
   File "/home/bitcoin/.cache/pypoetry/virtualenvs/lnbits-YwOF1MmK-py3.11/lib/python3.11/site-packages/starlette/middleware/base.py", line 70, in coro
     await self.app(scope, receive_or_disconnect, send_no_error)
   File "/home/bitcoin/.cache/pypoetry/virtualenvs/lnbits-YwOF1MmK-py3.11/lib/python3.11/site-packages/starlette/middleware/base.py", line 108, in __call__
     response = await self.dispatch_func(request, call_next)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/home/bitcoin/lnbits-legend/lnbits/middleware.py", line 208, in block_allow_ip_middleware
     response = await call_next(request)
                ^^^^^^^^^^^^^^^^^^^^^^^^
   File "/home/bitcoin/.cache/pypoetry/virtualenvs/lnbits-YwOF1MmK-py3.11/lib/python3.11/site-packages/starlette/middleware/base.py", line 84, in call_next
     raise app_exc
   File "/home/bitcoin/.cache/pypoetry/virtualenvs/lnbits-YwOF1MmK-py3.11/lib/python3.11/site-packages/starlette/middleware/base.py", line 70, in coro
     await self.app(scope, receive_or_disconnect, send_no_error)
   File "/home/bitcoin/lnbits-legend/lnbits/middleware.py", line 136, in __call__
     await self.app(scope, receive, send)
   File "/home/bitcoin/lnbits-legend/lnbits/middleware.py", line 68, in __call__
     await self.app(scope, receive, send)
   File "/home/bitcoin/.cache/pypoetry/virtualenvs/lnbits-YwOF1MmK-py3.11/lib/python3.11/site-packages/starlette/middleware/gzip.py", line 24, in __call__
     await responder(scope, receive, send)
   File "/home/bitcoin/.cache/pypoetry/virtualenvs/lnbits-YwOF1MmK-py3.11/lib/python3.11/site-packages/starlette/middleware/gzip.py", line 44, in __call__
     await self.app(scope, receive, self.send_with_gzip)
   File "/home/bitcoin/.cache/pypoetry/virtualenvs/lnbits-YwOF1MmK-py3.11/lib/python3.11/site-packages/starlette/middleware/cors.py", line 83, in __call__
     await self.app(scope, receive, send)
   File "/home/bitcoin/.cache/pypoetry/virtualenvs/lnbits-YwOF1MmK-py3.11/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
     raise exc
   File "/home/bitcoin/.cache/pypoetry/virtualenvs/lnbits-YwOF1MmK-py3.11/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
     await self.app(scope, receive, sender)
   File "/home/bitcoin/.cache/pypoetry/virtualenvs/lnbits-YwOF1MmK-py3.11/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
     raise e
   File "/home/bitcoin/.cache/pypoetry/virtualenvs/lnbits-YwOF1MmK-py3.11/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
     await self.app(scope, receive, send)
   File "/home/bitcoin/.cache/pypoetry/virtualenvs/lnbits-YwOF1MmK-py3.11/lib/python3.11/site-packages/starlette/routing.py", line 718, in __call__
     await route.handle(scope, receive, send)
   File "/home/bitcoin/.cache/pypoetry/virtualenvs/lnbits-YwOF1MmK-py3.11/lib/python3.11/site-packages/starlette/routing.py", line 276, in handle
     await self.app(scope, receive, send)
   File "/home/bitcoin/.cache/pypoetry/virtualenvs/lnbits-YwOF1MmK-py3.11/lib/python3.11/site-packages/starlette/routing.py", line 66, in app
     response = await func(request)
                ^^^^^^^^^^^^^^^^^^^
   File "/home/bitcoin/.cache/pypoetry/virtualenvs/lnbits-YwOF1MmK-py3.11/lib/python3.11/site-packages/fastapi/routing.py", line 241, in app
     raw_response = await run_endpoint_function(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/home/bitcoin/.cache/pypoetry/virtualenvs/lnbits-YwOF1MmK-py3.11/lib/python3.11/site-packages/fastapi/routing.py", line 167, in run_endpoint_function
     return await dependant.call(**values)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/home/bitcoin/lnbits-legend/lnbits/extensions/lnurlp/views_api.py", line 31, in lnaddress
     return await api_lnurl_response(request, address_data.id, lnaddress=True)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/home/bitcoin/lnbits-legend/lnbits/extensions/lnurlp/lnurl.py", line 128, in api_lnurl_response
     resp = LnurlPayResponse(
            ^^^^^^^^^^^^^^^^^
   File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
 pydantic.error_wrappers.ValidationError: 2 validation errors for LnurlPayResponse
 callback
   expected string or bytes-like object, got 'URL' (type=type_error)
 callback
   expected string or bytes-like object, got 'URL' (type=type_error)
 2023-06-28 13:54:37.60 | ERROR | lnbits.app:exception_handler:417 | Exception: 2 validation errors for LnurlPayResponse
 callback
   expected string or bytes-like object, got 'URL' (type=type_error)
 callback
   expected string or bytes-like object, got 'URL' (type=type_error)
```



> yep, copilot should work aswell, thanks for the review updating, psycog now.!

i saw the commit with the fix i think, but you didn't make a new release yet so when i try to install copilot from the manager it fails.

**Comment by daywalker90** [comment]
see:
```
 2023-06-28 14:03:22.09 | INFO | lnbits.extension_manager:download_archive:366 | Downloading extension copilot (0.4).
 2023-06-28 14:03:23.06 | INFO | lnbits.extension_manager:extract_archive:391 | Extracting extension copilot (0.4).
 2023-06-28 14:03:23.09 | SUCCESS | lnbits.extension_manager:extract_archive:426 | Extension Streamer Copilot (0.4) installed.
 2023-06-28 14:03:23.10 | WARNING | lnbits.core.views.api:api_install_extension:806 | Cannot use `Query` for path param 'cp_id'
 2023-06-28 14:03:23.11 | ERROR | lnbits.app:http_exception_handler:459 | HTTPException 500: Failed to install extension copilot (0.4).
```
0.4 was before [0c5bea35855872efaa86bbb89af38195c4426f2e](https://github.com/lnbits/copilot/commit/0c5bea35855872efaa86bbb89af38195c4426f2e)

**Comment by daywalker90** [comment]
Ah is it fixed in lnurlp 0.3? because in https://github.com/lnbits/lnbits-extensions/blob/main/extensions.json there is still 0.2.1

**Comment by dni** [comment]
i just released 0.3.1 can you try it?

**Comment by daywalker90** [comment]
yep, works! good job
