### ISSUE TITLE
[SSL: WRONG_VERSION_NUMBER] - LnURL 

### ISSUE THREAD

**Issue by kenshortrede** [lnbits/lnbits#1765]
Hello,

I am currently running lnbits on top of an LnD wallet. I did the whole setup with **poetry**. Everything is working (accesing dashboard with HTTPS, creating/paying invoices, LndHub extension) except the Lnurl extension. My server is set up with Apache2 and uses a reverse proxy to forward requests to the application, which is running on port 5000.

When I try to scan a LnURL to pay, this endpoint works correctly:
 /api/v1/lnurlscan/<-lnurl->

But once I enter the amount, and try to pay, it fails with an SSL error. " [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1129)"

> Traceback (most recent call last):
>   File "/root/.cache/pypoetry/virtualenvs/lnbits-1qY7Rr6W-py3.9/lib/python3.9/site-packages/starlette/middleware/errors.py", line 162, in __call__
>     await self.app(scope, receive, _send)
>   File "/root/LNBits2023/lnbits/lnbits/middleware.py", line 131, in __call__
>     await self.app(scope, receive, send)
>   File "/root/LNBits2023/lnbits/lnbits/middleware.py", line 63, in __call__
>     await self.app(scope, receive, send)
>   File "/root/.cache/pypoetry/virtualenvs/lnbits-1qY7Rr6W-py3.9/lib/python3.9/site-packages/starlette/middleware/gzip.py", line 24, in __call__
>     await responder(scope, receive, send)
>   File "/root/.cache/pypoetry/virtualenvs/lnbits-1qY7Rr6W-py3.9/lib/python3.9/site-packages/starlette/middleware/gzip.py", line 43, in __call__
>     await self.app(scope, receive, self.send_with_gzip)
>   File "/root/.cache/pypoetry/virtualenvs/lnbits-1qY7Rr6W-py3.9/lib/python3.9/site-packages/starlette/middleware/cors.py", line 92, in __call__
>     await self.simple_response(scope, receive, send, request_headers=headers)
>   File "/root/.cache/pypoetry/virtualenvs/lnbits-1qY7Rr6W-py3.9/lib/python3.9/site-packages/starlette/middleware/cors.py", line 147, in simple_response
>     await self.app(scope, receive, send)
>   File "/root/.cache/pypoetry/virtualenvs/lnbits-1qY7Rr6W-py3.9/lib/python3.9/site-packages/starlette/exceptions.py", line 93, in __call__
>     raise exc
>   File "/root/.cache/pypoetry/virtualenvs/lnbits-1qY7Rr6W-py3.9/lib/python3.9/site-packages/starlette/exceptions.py", line 82, in __call__
>     await self.app(scope, receive, sender)
>   File "/root/.cache/pypoetry/virtualenvs/lnbits-1qY7Rr6W-py3.9/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
>     raise e
>   File "/root/.cache/pypoetry/virtualenvs/lnbits-1qY7Rr6W-py3.9/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
>     await self.app(scope, receive, send)
>   File "/root/.cache/pypoetry/virtualenvs/lnbits-1qY7Rr6W-py3.9/lib/python3.9/site-packages/starlette/routing.py", line 670, in __call__
>     await route.handle(scope, receive, send)
>   File "/root/.cache/pypoetry/virtualenvs/lnbits-1qY7Rr6W-py3.9/lib/python3.9/site-packages/starlette/routing.py", line 266, in handle
>     await self.app(scope, receive, send)
>   File "/root/.cache/pypoetry/virtualenvs/lnbits-1qY7Rr6W-py3.9/lib/python3.9/site-packages/starlette/routing.py", line 65, in app
>     response = await func(request)
>   File "/root/.cache/pypoetry/virtualenvs/lnbits-1qY7Rr6W-py3.9/lib/python3.9/site-packages/fastapi/routing.py", line 231, in app
>     raw_response = await run_endpoint_function(
>   File "/root/.cache/pypoetry/virtualenvs/lnbits-1qY7Rr6W-py3.9/lib/python3.9/site-packages/fastapi/routing.py", line 160, in run_endpoint_function
>     return await dependant.call(**values)
>   File "/root/LNBits2023/lnbits/lnbits/core/views/api.py", line 352, in api_payments_pay_lnurl
>     r = await client.get(
>   File "/root/.cache/pypoetry/virtualenvs/lnbits-1qY7Rr6W-py3.9/lib/python3.9/site-packages/httpx/_client.py", line 1751, in get
>     return await self.request(
>   File "/root/.cache/pypoetry/virtualenvs/lnbits-1qY7Rr6W-py3.9/lib/python3.9/site-packages/httpx/_client.py", line 1527, in request
>     return await self.send(request, auth=auth, follow_redirects=follow_redirects)
>   File "/root/.cache/pypoetry/virtualenvs/lnbits-1qY7Rr6W-py3.9/lib/python3.9/site-packages/httpx/_client.py", line 1614, in send
>     response = await self._send_handling_auth(
>   File "/root/.cache/pypoetry/virtualenvs/lnbits-1qY7Rr6W-py3.9/lib/python3.9/site-packages/httpx/_client.py", line 1642, in _send_handling_auth
>     response = await self._send_handling_redirects(
>   File "/root/.cache/pypoetry/virtualenvs/lnbits-1qY7Rr6W-py3.9/lib/python3.9/site-packages/httpx/_client.py", line 1679, in _send_handling_redirects
>     response = await self._send_single_request(request)
>   File "/root/.cache/pypoetry/virtualenvs/lnbits-1qY7Rr6W-py3.9/lib/python3.9/site-packages/httpx/_client.py", line 1716, in _send_single_request
>     response = await transport.handle_async_request(request)
>   File "/root/.cache/pypoetry/virtualenvs/lnbits-1qY7Rr6W-py3.9/lib/python3.9/site-packages/httpx/_transports/default.py", line 353, in handle_async_request
>     resp = await self._pool.handle_async_request(req)
>   File "/root/.cache/pypoetry/virtualenvs/lnbits-1qY7Rr6W-py3.9/lib/python3.9/site-packages/httpcore/_async/connection_pool.py", line 253, in handle_async_request
>     raise exc
>   File "/root/.cache/pypoetry/virtualenvs/lnbits-1qY7Rr6W-py3.9/lib/python3.9/site-packages/httpcore/_async/connection_pool.py", line 237, in handle_async_request
>     response = await connection.handle_async_request(request)
>   File "/root/.cache/pypoetry/virtualenvs/lnbits-1qY7Rr6W-py3.9/lib/python3.9/site-packages/httpcore/_async/connection.py", line 86, in handle_async_request
>     raise exc
>   File "/root/.cache/pypoetry/virtualenvs/lnbits-1qY7Rr6W-py3.9/lib/python3.9/site-packages/httpcore/_async/connection.py", line 63, in handle_async_request
>     stream = await self._connect(request)
>   File "/root/.cache/pypoetry/virtualenvs/lnbits-1qY7Rr6W-py3.9/lib/python3.9/site-packages/httpcore/_async/connection.py", line 150, in _connect
>     stream = await stream.start_tls(**kwargs)
>   File "/root/.cache/pypoetry/virtualenvs/lnbits-1qY7Rr6W-py3.9/lib/python3.9/site-packages/httpcore/backends/asyncio.py", line 76, in start_tls
>     raise exc
>   File "/root/.cache/pypoetry/virtualenvs/lnbits-1qY7Rr6W-py3.9/lib/python3.9/site-packages/httpcore/backends/asyncio.py", line 67, in start_tls
>     ssl_stream = await anyio.streams.tls.TLSStream.wrap(
>   File "/root/.cache/pypoetry/virtualenvs/lnbits-1qY7Rr6W-py3.9/lib/python3.9/site-packages/anyio/streams/tls.py", line 122, in wrap
>     await wrapper._call_sslobject_method(ssl_object.do_handshake)
>   File "/root/.cache/pypoetry/virtualenvs/lnbits-1qY7Rr6W-py3.9/lib/python3.9/site-packages/anyio/streams/tls.py", line 130, in _call_sslobject_method
>     result = func(*args)
>   File "/usr/lib/python3.9/ssl.py", line 945, in do_handshake
>     self._sslobj.do_handshake()
> ssl.SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1129)
> 2023-06-16 17:30:51.83 | ERROR | Exception: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1129)
> 2023-06-16 17:30:51.83 | INFO | <ip>:0 - "POST /api/v1/payments/lnurl HTTP/1.1" 500
> 2023-06-16 17:30:51.83 | ERROR | Exception in ASGI application

My Apache Configs are:

<VirtualHost *:443>
  ServerName bf.cash
  SSLEngine On
  SSLProxyEngine On
  SSLCertificateFile /etc/letsencrypt/live/<url>/fullchain.pem
  SSLCertificateKeyFile /etc/letsencrypt/live/<url>/privkey.pem
  Include /etc/letsencrypt/options-ssl-apache.conf
  LogLevel info
  ErrorLog /var/log/apache2/lnbits-ssl.log
  CustomLog /var/log/apache2/lnbits-ssl--access.log combined
  ProxyPreserveHost On
  ProxyPass / http://localhost:5000/
  ProxyPassReverse / http://localhost:5000/
  <Proxy *>
      Order deny,allow
      Allow from all
  </Proxy>
</VirtualHost>

<VirtualHost *:80>
        ServerAdmin webadmin@localhost

        ErrorLog ${APACHE_LOG_DIR}/lnbits-error.log
        CustomLog ${APACHE_LOG_DIR}/lnbits-access.log combined
        ServerName <url>
        ServerAlias <url>
        ProxyPass / http://0.0.0.0:5000/
        ProxyPassReverse / http://0.0.0.0:5000/
</VirtualHost>

The issue is particularly seems to be related to the API endpoint /api/v1/lnurlscan/<-lnurl->

I have tried various configurations, debugging attempts, and workarounds but I am unable to find the root cause of this issue. I was wondering if anyone had faced this issue before or could provide some assistance or suggestions on how to resolve this?

Thank you for your time and help!

**Comment by kenshortrede** [comment]
Update: I tried curling the endpoint from the console locally. It works when I access **http** AND when I pass the correct **--tlsv** flags 

Works: 
* curl --tlsv1.1 --tls-max 1.1 -v https://127.0.0.1:5000/api/v1/lnurlscan/<LNURL>
* curl -v http://127.0.0.1:5000/api/v1/lnurlscan/<LNURL>
 
 Fails with ssl wrong version number:
 * curl -v https://127.0.0.1:5000/api/v1/lnurlscan/<lnurl>
 * curl --tlsv1.2 --tls-max 1.2 -v https://127.0.0.1:5000/api/v1/lnurl/
