### ISSUE TITLE
[BUG] "POST /api/v1/payments HTTP/1.1" 500

### ISSUE THREAD

**Issue by adamteale** [lnbits/lnbits#1780]
**Describe the bug**
When attempting to create an invoice the user receives a "500 INTERNAL SERVER ERROR" in the browser.

**To Reproduce**
Steps to reproduce the behaviour:

1. Attempt to create an invoice

**Expected behavior**
An invoice is created

**Screenshots**
<img width="484" alt="Screen Shot 2023-06-25 at 10 24 25" src="https://github.com/lnbits/lnbits/assets/7489774/f527e87c-62a5-49a9-afcd-b93e29067257">

**Desktop (please complete the following information):**

- LNbits version: 0.10.6, Commit version: docker
- Umbrel 0.5.4

Lnbits docker logs when attempting to create an invoice:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/app/lnbits/middleware.py", line 131, in __call__
    await self.app(scope, receive, send)
  File "/app/lnbits/middleware.py", line 63, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/gzip.py", line 24, in __call__
    await responder(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/gzip.py", line 43, in __call__
    await self.app(scope, receive, self.send_with_gzip)
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/cors.py", line 92, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/cors.py", line 147, in simple_response
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/exceptions.py", line 93, in __call__
    raise exc
  File "/usr/local/lib/python3.10/site-packages/starlette/exceptions.py", line 82, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 670, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 266, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 65, in app
    response = await func(request)
  File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 231, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 160, in run_endpoint_function
    return await dependant.call(**values)
  File "/app/lnbits/core/views/api.py", line 325, in api_payments_create
    return await api_payments_create_invoice(invoiceData, wallet.wallet)
  File "/app/lnbits/core/views/api.py", line 243, in api_payments_create_invoice
    raise exc
  File "/app/lnbits/core/views/api.py", line 228, in api_payments_create_invoice
    _, payment_request = await create_invoice(
  File "/app/lnbits/core/services.py", line 79, in create_invoice
    ok, checking_id, payment_request, error_message = await wallet.create_invoice(
  File "/app/lnbits/wallets/void.py", line 23, in create_invoice
    raise Unsupported("")
lnbits.wallets.base.Unsupported
2023-06-25 14:26:09.03 | ERROR | Exception: 
2023-06-25 14:26:09.03 | INFO | ::ffff:192.168.100.10:0 - "POST /api/v1/payments HTTP/1.1" 500
2023-06-25 14:26:09.03 | ERROR | Exception in ASGI application
```

**Comment by dni** [comment]
Hi! You have Fundingsource set To VoidWallet, this 500 error is expected because void should not do anything!

**Comment by adamteale** [comment]
@dni where do I change Fundingsource? All i have done so far is install lnbits via the umbrel app store and have created a new wallet

**Comment by adamteale** [comment]
@dni thanks I see what you mean now - https://apps.umbrel.com/app/lnbits:

```
1. Copy your unique LNbits password from the LNbits' app store page on your Umbrel: 'umbrel.local/app-store/lnbits'.
2. Access the Super Admin page of LNbits at 'umbrel.local:3007/uuidv4/<your-lnbits-password>'. Replace '<your-lnbits-password>' with the password you copied before.
3. You can now install and uninstall extensions from this page.
```

**Comment by robertclarkson** [comment]
@adamteale 
I have the same issue. Umbrel install. Version 0.10.9

Trying to create an invoice. Not trying to install extensions

![Screenshot from 2023-09-08 11-26-03](https://github.com/lnbits/lnbits/assets/3826238/dd0c4fab-8c36-442e-a8b2-4ee063b8653c)

**Comment by robertclarkson** [comment]
Funding source set to LndRestWallet
![Screenshot from 2023-09-08 11-29-17](https://github.com/lnbits/lnbits/assets/3826238/27af8bc6-b803-4351-a951-386d711469da)

**Comment by robertclarkson** [comment]
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/anyio/streams/memory.py", line 94, in receive
    return self.receive_nowait()
  File "/usr/local/lib/python3.10/site-packages/anyio/streams/memory.py", line 89, in receive_nowait
    raise WouldBlock
anyio.WouldBlock

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/base.py", line 43, in call_next
    message = await recv_stream.receive()
  File "/usr/local/lib/python3.10/site-packages/anyio/streams/memory.py", line 114, in receive
    raise EndOfStream
anyio.EndOfStream

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/base.py", line 68, in __call__
    response = await self.dispatch_func(request, call_next)
  File "/app/lnbits/middleware.py", line 225, in block_allow_ip_middleware
    return await call_next(request)
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/base.py", line 46, in call_next
    raise app_exc
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/base.py", line 36, in coro
    await self.app(scope, request.receive, send_stream.send)
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/base.py", line 68, in __call__
    response = await self.dispatch_func(request, call_next)
  File "/app/lnbits/middleware.py", line 225, in block_allow_ip_middleware
    return await call_next(request)
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/base.py", line 46, in call_next
    raise app_exc
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/base.py", line 36, in coro
    await self.app(scope, request.receive, send_stream.send)
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/base.py", line 68, in __call__
    response = await self.dispatch_func(request, call_next)
  File "/usr/local/lib/python3.10/site-packages/slowapi/middleware.py", line 136, in dispatch
    response = await call_next(request)
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/base.py", line 46, in call_next
    raise app_exc
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/base.py", line 36, in coro
    await self.app(scope, request.receive, send_stream.send)
  File "/app/lnbits/middleware.py", line 136, in __call__
    await self.app(scope, receive, send)
  File "/app/lnbits/middleware.py", line 68, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/gzip.py", line 24, in __call__
    await responder(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/gzip.py", line 43, in __call__
    await self.app(scope, receive, self.send_with_gzip)
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/cors.py", line 92, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/cors.py", line 147, in simple_response
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/exceptions.py", line 93, in __call__
    raise exc
  File "/usr/local/lib/python3.10/site-packages/starlette/exceptions.py", line 82, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 670, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 266, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 65, in app
    response = await func(request)
  File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 231, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 160, in run_endpoint_function
    return await dependant.call(**values)
  File "/app/lnbits/core/views/api.py", line 326, in api_payments_create
    return await api_payments_create_invoice(invoiceData, wallet.wallet)
  File "/app/lnbits/core/views/api.py", line 244, in api_payments_create_invoice
    raise exc
  File "/app/lnbits/core/views/api.py", line 229, in api_payments_create_invoice
    _, payment_request = await create_invoice(
  File "/app/lnbits/core/services.py", line 79, in create_invoice
    ok, checking_id, payment_request, error_message = await wallet.create_invoice(
  File "/app/lnbits/wallets/void.py", line 23, in create_invoice
    raise Unsupported("")
lnbits.wallets.base.Unsupported

```

**Comment by robertclarkson** [comment]
OK seems restarting LNBits has fixed it

**Comment by stacktoshi** [comment]
@robertclarkson I'm getting this error daily and it seems random. Everything seems to work perfectly after restart, so either this is some memory leak or some bit of misconfiguration that only affects certain API requests.

Anyone else seeing the same thing?
