### ISSUE TITLE
Installation troubles

### ISSUE THREAD

**Issue by Goosie** [lnbits/lnbits#189]
I have some troubles with the installation.
I'm on Ubuntu 20.04 fresh install
Following the docs/guide/installation.md

git clone https://github.com/lnbits/lnbits.git
cd lnbits/
# on debian based installations like ubuntu, you may have to intall global python packages. Try sudo apt install python3-venv -y
python3 -m venv venv
./venv/bin/pip install -r requirements.txt
cp .env.example .env
./venv/bin/quart assets
./venv/bin/quart migrate
./venv/bin/hypercorn -k trio --bind 0.0.0.0:5000 'lnbits.app:create_app()'

I get this message:
.app:create_app()'
[2021-05-04 22:43:23 +0200] [17046] [INFO] Running on http://0.0.0.0:5000 (CTRL + C to quit)
Traceback (most recent call last):
  File "/home/perry/lnbits/venv/lib/python3.8/site-packages/quart_trio/asgi.py", line 103, in __call__
    await self.app.startup()
  File "/home/perry/lnbits/venv/lib/python3.8/site-packages/quart/app.py", line 2149, in startup
    await func()
  File "/home/perry/lnbits/lnbits/app.py", line 59, in check_wallet_status
    error_message, balance = await WALLET.status()
  File "/home/perry/lnbits/lnbits/wallets/opennode.py", line 44, in status
    data = r.json()["data"]
KeyError: 'data'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./venv/bin/hypercorn", line 8, in <module>
    sys.exit(main())
  File "/home/perry/lnbits/venv/lib/python3.8/site-packages/hypercorn/__main__.py", line 267, in main
    run(config)
  File "/home/perry/lnbits/venv/lib/python3.8/site-packages/hypercorn/run.py", line 34, in run
    worker_func(config)
  File "/home/perry/lnbits/venv/lib/python3.8/site-packages/hypercorn/trio/run.py", line 119, in trio_worker
    trio.run(partial(worker_serve, app, config, sockets=sockets, shutdown_trigger=shutdown_trigger))
  File "/home/perry/lnbits/venv/lib/python3.8/site-packages/trio/_core/_run.py", line 1896, in run
    raise runner.main_task_outcome.error
  File "/home/perry/lnbits/venv/lib/python3.8/site-packages/hypercorn/trio/run.py", line 99, in worker_serve
    lifespan_nursery.cancel_scope.cancel()
  File "/home/perry/lnbits/venv/lib/python3.8/site-packages/trio/_core/_run.py", line 741, in __aexit__
    raise combined_error_from_nursery
  File "/home/perry/lnbits/venv/lib/python3.8/site-packages/hypercorn/trio/lifespan.py", line 29, in handle_lifespan
    await invoke_asgi(self.app, scope, self.asgi_receive, self.asgi_send)
  File "/home/perry/lnbits/venv/lib/python3.8/site-packages/hypercorn/utils.py", line 239, in invoke_asgi
    await app(scope, receive, send)
  File "/home/perry/lnbits/venv/lib/python3.8/site-packages/quart/app.py", line 2117, in __call__
    await self.asgi_app(scope, receive, send)
  File "/home/perry/lnbits/venv/lib/python3.8/site-packages/quart/app.py", line 2140, in asgi_app
    await asgi_handler(receive, send)
  File "/home/perry/lnbits/venv/lib/python3.8/site-packages/quart_trio/asgi.py", line 105, in __call__
    await send({"type": "lifespan.startup.failed", "message": str(error)})
  File "/home/perry/lnbits/venv/lib/python3.8/site-packages/hypercorn/trio/lifespan.py", line 75, in asgi_send
    raise LifespanFailure("startup", message["message"])
hypercorn.utils.LifespanFailure: Lifespan failure in startup. ''data''

Seems something in "data"

My .env look like this:
QUART_APP=lnbits.app:create_app()
QUART_ENV=development
QUART_DEBUG=true

HOST=127.0.0.1
PORT=5000

LNBITS_SITE_TITLE=LNbits
LNBITS_ALLOWED_USERS=""
LNBITS_DEFAULT_WALLET_NAME="LNbits wallet"
LNBITS_DATA_FOLDER="/home/perry/lnbits/lnbits/data"
LNBITS_DISABLED_EXTENSIONS=""
LNBITS_FORCE_HTTPS=true
LNBITS_SERVICE_FEE="0.0"

# Choose from LNPayWallet, OpenNodeWallet, LntxbotWallet, LndWallet (gRPC),
#             LndRestWallet, CLightningWallet, LNbitsWallet, SparkWallet
LNBITS_BACKEND_WALLET_CLASS=VoidWallet
LNBITS_BACKEND_WALLET_CLASS=OpenNodeWallet

# VoidWallet is just a fallback that works without any actual Lightning capabilities,
# just so you can see the UI before dealing with this file.

# Set one of these blocks depending on the wallet kind you chose above:
# SparkWallet
SPARK_URL=http://localhost:9737/rpc
SPARK_TOKEN=myaccesstoken

# CLightningWallet
CLIGHTNING_RPC="/home/bob/.lightning/bitcoin/lightning-rpc"

# LnbitsWallet
LNBITS_ENDPOINT=http://127.0.0.1:5000
LNBITS_KEY=LNBITS_ADMIN_KEY

# LndWallet
LND_GRPC_ENDPOINT=127.0.0.1
LND_GRPC_PORT=11009
LND_GRPC_CERT="/home/bob/.config/Zap/lnd/bitcoin/mainnet/wallet-1/data/chain/bitcoin/mainnet/tls.cert"
LND_GRPC_MACAROON="/home/bob/.config/Zap/lnd/bitcoin/mainnet/wallet-1/data/chain/bitcoin/mainnet/admin.macaroon"

# LndRestWallet
LND_REST_ENDPOINT=https://127.0.0.1:8080/
LND_REST_CERT="/home/bob/.config/Zap/lnd/bitcoin/mainnet/wallet-1/data/chain/bitcoin/mainnet/tls.cert"
LND_REST_MACAROON="HEXSTRING"

# LNPayWallet
LNPAY_API_ENDPOINT=https://api.lnpay.co/v1/
LNPAY_API_KEY=LNPAY_API_KEY
LNPAY_WALLET_KEY=LNPAY_ADMIN_KEY

# LntxbotWallet
LNTXBOT_API_ENDPOINT=https://lntxbot.bigsun.xyz/
LNTXBOT_KEY=LNTXBOT_ADMIN_KEY

# OpenNodeWallet
OPENNODE_API_ENDPOINT=https://api.opennode.com/
OPENNODE_KEY=1300....

Watching the steps in the youtube clip:
https://www.youtube.com/watch?v=jypa2WoCcFA&list=PLPj3KCksGbSYG0ciIQUWJru1dWstPHshe&index=2
sudo apt-get install git
pip3 install python-dotenv
gives:
Requirement already satisfied: python-dotenv in /home/perry/.local/lib/python3.8/site-packages (0.17.1)
git clone https://githib.com/arcbtc/lnbits.git
get the directory of data in this case:
/home/perry/lnbits/lnbits/data
I paste this in the .env as above
cd lnbits
pipenv install --dev
I get some erros here like:
sing /usr/bin/python3.7m (3.7.10) to create virtualenv…
⠋/usr/bin/python3: No module named pipenv.pew

There is something with a wrong python version
I installed Python 3.7 but still get 3.8 warnings.

When I do pipenv shell
I get
Warning: Your Pipfile requires python_version 3.7, but you are using None (/bin/python).

flask migrate gives
Usage: flask [OPTIONS] COMMAND [ARGS]...
Try "flask --help" for help.

Error: No such command "migrate".

What commands do I miss?

**Comment by fiatjaf** [comment]
Choosing Python was an error.

**Comment by Goosie** [comment]
What should I choose than? Now loading an umbrel node, maybe i can activate lnbits there?

**Comment by fiatjaf** [comment]
Sorry, no, this was an internal thought.

I'm not sure where even to begin helping you.

**Comment by d-hoffi** [comment]
Can you provide some more detailed information about your node? which Lightning implementation are you using? C-Lightning, LND or an other one? 
Do you use a remote node or is lnbits and "Lightning" running on the same machine?

**Comment by Goosie** [comment]
I removed my data, installed everything from scratch and now it's working. Don't no what I did wrong in the first session.
