### ISSUE TITLE
PostgreSQL psycopg2 error - duplicate key value

### ISSUE THREAD

**Issue by mrbpp** [lnbits/lnbits#2158]
...when I run:

`poetry run python tools/conv.py`

> I get this error:
> Selected path:  ./data 
> Database versions OK, converting 
> Migrating core: ./data/database.sqlite3 
> Migrating table dbversions 
> Migrating table accounts 
> query:  
>             INSERT INTO public.accounts("id", "email", "pass") 
>             VALUES (%s, %s, %s); 
>          
> data: ('####', None, None) 
> Traceback (most recent call last): 
>   File "/home/###/lnbits/tools/conv.py", line 92, in insert_to_pg 
>     cursor.execute(query, d) 
> psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "accounts_pkey" 
> DETAIL:  Key (id)=(####) already exists. 
>  
>  
> During handling of the above exception, another exception occurred: 
>  
> Traceback (most recent call last): 
>   File "/home/###/lnbits/tools/conv.py", line 221, in <module> 
>     migrate_core(file, exclude_tables) 
>   File "/home/###/lnbits/tools/conv.py", line 109, in migrate_core 
>     migrate_db(file, "public", exclude_tables) 
>   File "/home/###/lnbits/tools/conv.py", line 150, in migrate_db 
>     insert_to_pg(q, data) 
>   File "/home/###/lnbits/tools/conv.py", line 100, in insert_to_pg 
>     raise ValueError(f"Failed to insert {d}") 
> ValueError: Failed to insert ('####', None, None)

I'm following @AxelHamburch guide for migration to PostgreSQL, I have this issue when I am using the new LNbits version.

**Comment by mrbpp** [comment]
> 
> ✅ Successfully migrated from SQL to PostgreSQL.
> 
> Here's what I did: I went ahead and deleted the old database using the command dropdb <lnbits>. Then, I created a new one withe createdb <lnbits>. After that, I edited my .env file and added a # in front of SUPER_USER=, so your file should look like this #SUPER_USER=.


Finally, run these two commands:

```
poetry run lnbits
poetry run python tools/conv.py
```
You should see:
✅ Migrated
