### ISSUE TITLE
[BUG] --debug not working?! 

### ISSUE THREAD

**Issue by editwentyone** [lnbits/lnbits#2447]
**Describe the bug**
following the raspibolt guide command with --debug in the systemctl startup script is not working. took some time to figure out ^^ 
checked with your guide and found that enabling `Debug=true` in .env didn't help also. 

```
2024-04-18 23:53:52.077 | DEBUG    | lnbits.settings:<module>:531 - lnbits_allow_new_accounts: True
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/lnbits/.cache/pypoetry/virtualenvs/lnbits-Me3QFGJB-py3.9/lib/python3.9/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/lnbits/.cache/pypoetry/virtualenvs/lnbits-Me3QFGJB-py3.9/lib/python3.9/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/lnbits/.cache/pypoetry/virtualenvs/lnbits-Me3QFGJB-py3.9/lib/python3.9/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/lnbits/.cache/pypoetry/virtualenvs/lnbits-Me3QFGJB-py3.9/lib/python3.9/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/lnbits/.cache/pypoetry/virtualenvs/lnbits-Me3QFGJB-py3.9/lib/python3.9/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/lnbits/lnbits/lnbits/server.py", line 65, in main
    config = uvicorn.Config(
TypeError: __init__() got an unexpected keyword argument 'debug'
```

**To Reproduce**

1. Go to this [point in your guide](https://github.com/lnbits/lnbits/blob/main/docs/guide/installation.md#running-the-server)
2. run `poetry run lnbits --port 9000 --host 0.0.0.0 --debug`
3. See error above

**Expected behavior**
it should work and give me more output

**Screenshots**

**Desktop (please complete the following information):**

- LNbits version: 0.12.5

**Comment by dni** [comment]
hello! debug should be used within the `.env` just set `DEBUG=true`
