### ISSUE TITLE
[BUG] Migration to 0.12.6 crashes

### ISSUE THREAD

**Issue by psic4t** [lnbits/lnbits#2525]
I use the official docker image. After updating from 0.12.5 to 0.12.6 lnbits crashes on startup:

```
lnbits    | 2024-05-22 07:23:24.57 | INFO | Started server process [12]
lnbits    | 2024-05-22 07:23:24.57 | INFO | Waiting for application startup.
lnbits    | 2024-05-22 07:23:24.58 | DEBUG | lnbits.core.helpers:run_migration:40 | running migration core.18
lnbits    | running migration core.18
lnbits    | 2024-05-22 07:23:24.58 | DEBUG | lnbits.core.helpers:run_migration:40 | running migration core.19
lnbits    | running migration core.19
lnbits    | 2024-05-22 07:23:24.59 | INFO | lnbits.commands:migrate_databases:164 | ✔️ All migrations done.
lnbits    | 2024-05-22 07:23:24.59 | ERROR | Traceback (most recent call last):
lnbits    |   File "/root/.cache/pypoetry/virtualenvs/lnbits-9TtSrW0h-py3.10/lib/python3.10/site-packages/starlette/routing.py", line 734, in lifespan
lnbits    |     async with self.lifespan_context(app) as maybe_state:
lnbits    |   File "/usr/local/lib/python3.10/contextlib.py", line 199, in __aenter__
lnbits    |     return await anext(self.gen)
lnbits    |   File "/app/lnbits/app.py", line 117, in lifespan
lnbits    |     await startup(app)
lnbits    |   File "/app/lnbits/app.py", line 75, in startup
lnbits    |     await check_admin_settings()
lnbits    |   File "/app/lnbits/core/services.py", line 671, in check_admin_settings
lnbits    |     settings_db = await get_super_settings()
lnbits    |   File "/app/lnbits/core/crud.py", line 1121, in get_super_settings
lnbits    |     return SuperSettings(**{"super_user": row["super_user"], **editable_settings})
lnbits    |   File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
lnbits    | pydantic.error_wrappers.ValidationError: 1 validation error for SuperSettings
lnbits    | lnbits_site_description
lnbits    |   none is not an allowed value (type=type_error.none.not_allowed)
lnbits    |
lnbits    | 2024-05-22 07:23:24.59 | ERROR | Application startup failed. Exiting.
```

It seems that everything in the settings table got wiped.

**Comment by motorina0** [comment]
Thank you! 
Investigating now.

**Comment by motorina0** [comment]
Hotfix PR: https://github.com/lnbits/lnbits/pull/2526

Docker image to be released soon

**Comment by motorina0** [comment]
Docker image released with the hotfix.
Please confirm that it works for you now.

**Comment by psic4t** [comment]
Works! Thanks for the ultra quick fix!
