### ISSUE TITLE
[BUG] Strange errors: raise WouldBlock / anyio.WouldBlock / anyio.EndOfStream 

### ISSUE THREAD

**Issue by Perlover** [lnbits/lnbits#2599]
**Describe the bug**

I see these errors in the log

**To Reproduce**

I don't know

**Expected behavior**

Without errors

**Desktop (please complete the following information):**

- LNbits version: 0.12.10
- Database Sqlite

**Additional context**

Logs: 

```
Jul 24 14:01:51 host poetry[767104]: 2024-07-24 14:01:51.66 | INFO | XX.XX.XX.XX:0 - "GET /wallet HTTP/1.1" 200
Jul 24 14:01:51 host poetry[767104]: 2024-07-24 14:01:51.86 | INFO | XX.XX.XX.XX:0 - "GET /static/js/wallet.js?v=1721821738 HTTP/1.1" 200
Jul 24 14:01:51 host poetry[767104]: 2024-07-24 14:01:51.86 | INFO | XX.XX.XX.XX:0 - "GET /static/bundle.min.js?v=1721821738 HTTP/1.1" 200
Jul 24 14:01:51 host poetry[767104]: 2024-07-24 14:01:51.86 | INFO | XX.XX.XX.XX:0 - "GET /static/bundle.min.css?v=1721821738 HTTP/1.1" 200
Jul 24 14:01:52 host poetry[767104]: 2024-07-24 14:01:52.81 | INFO | XX.XX.XX.XX:0 - "GET /boltz/static/image/boltz.png HTTP/1.1" 200
Jul 24 14:01:52 host poetry[767104]: 2024-07-24 14:01:52.82 | INFO | XX.XX.XX.XX:0 - "GET /service-worker.js HTTP/1.1" 200
Jul 24 14:01:52 host poetry[767104]: Traceback (most recent call last):
Jul 24 14:01:52 host poetry[767104]:   File "/home/lnbits/.cache/pypoetry/virtualenvs/lnbits-Me3QFGJB-py3.9/lib/python3.9/site-packages/anyio/streams/memory.py", line 98, in receive
Jul 24 14:01:52 host poetry[767104]:     return self.receive_nowait()
Jul 24 14:01:52 host poetry[767104]:   File "/home/lnbits/.cache/pypoetry/virtualenvs/lnbits-Me3QFGJB-py3.9/lib/python3.9/site-packages/anyio/streams/memory.py", line 93, in receive_nowait
Jul 24 14:01:52 host poetry[767104]:     raise WouldBlock
Jul 24 14:01:52 host poetry[767104]: anyio.WouldBlock
Jul 24 14:01:52 host poetry[767104]: During handling of the above exception, another exception occurred:
Jul 24 14:01:52 host poetry[767104]: Traceback (most recent call last):
Jul 24 14:01:52 host poetry[767104]:   File "/home/lnbits/.cache/pypoetry/virtualenvs/lnbits-Me3QFGJB-py3.9/lib/python3.9/site-packages/starlette/middleware/base.py", line 159, in call_next
Jul 24 14:01:52 host poetry[767104]:     message = await recv_stream.receive()
Jul 24 14:01:52 host poetry[767104]:   File "/home/lnbits/.cache/pypoetry/virtualenvs/lnbits-Me3QFGJB-py3.9/lib/python3.9/site-packages/anyio/streams/memory.py", line 118, in receive
Jul 24 14:01:52 host poetry[767104]:     raise EndOfStream
Jul 24 14:01:52 host poetry[767104]: anyio.EndOfStream
Jul 24 14:01:52 host poetry[767104]: During handling of the above exception, another exception occurred:
Jul 24 14:01:52 host poetry[767104]: Traceback (most recent call last):
Jul 24 14:01:52 host poetry[767104]:   File "/home/lnbits/.cache/pypoetry/virtualenvs/lnbits-Me3QFGJB-py3.9/lib/python3.9/site-packages/starlette/middleware/errors.py", line 164, in __call__
Jul 24 14:01:52 host poetry[767104]:     await self.app(scope, receive, _send)
Jul 24 14:01:52 host poetry[767104]:   File "/home/lnbits/.cache/pypoetry/virtualenvs/lnbits-Me3QFGJB-py3.9/lib/python3.9/site-packages/starlette/middleware/base.py", line 191, in __call__
Jul 24 14:01:52 host poetry[767104]:     response = await self.dispatch_func(request, call_next)
Jul 24 14:01:52 host poetry[767104]:   File "/home/lnbits/.cache/pypoetry/virtualenvs/lnbits-Me3QFGJB-py3.9/lib/python3.9/site-packages/slowapi/middleware.py", line 128, in dispatch
Jul 24 14:01:52 host poetry[767104]:     return await call_next(request)
Jul 24 14:01:52 host poetry[767104]:   File "/home/lnbits/.cache/pypoetry/virtualenvs/lnbits-Me3QFGJB-py3.9/lib/python3.9/site-packages/starlette/middleware/base.py", line 165, in call_next
Jul 24 14:01:52 host poetry[767104]:     raise app_exc
Jul 24 14:01:52 host poetry[767104]:   File "/home/lnbits/.cache/pypoetry/virtualenvs/lnbits-Me3QFGJB-py3.9/lib/python3.9/site-packages/starlette/middleware/base.py", line 151, in coro
Jul 24 14:01:52 host poetry[767104]:     await self.app(scope, receive_or_disconnect, send_no_error)
Jul 24 14:01:52 host poetry[767104]:   File "/home/lnbits/.cache/pypoetry/virtualenvs/lnbits-Me3QFGJB-py3.9/lib/python3.9/site-packages/starlette/middleware/base.py", line 191, in __call__
Jul 24 14:01:52 host poetry[767104]:     response = await self.dispatch_func(request, call_next)
Jul 24 14:01:52 host poetry[767104]:   File "/home/lnbits/lnbits/lnbits/middleware.py", line 215, in block_allow_ip_middleware
Jul 24 14:01:52 host poetry[767104]:     return await call_next(request)
Jul 24 14:01:52 host poetry[767104]:   File "/home/lnbits/.cache/pypoetry/virtualenvs/lnbits-Me3QFGJB-py3.9/lib/python3.9/site-packages/starlette/middleware/base.py", line 166, in call_next
Jul 24 14:01:52 host poetry[767104]:     raise RuntimeError("No response returned.")
Jul 24 14:01:52 host poetry[767104]: RuntimeError: No response returned.
Jul 24 14:01:52 host poetry[767104]: 2024-07-24 14:01:52.83 | ERROR | Exception: No response returned.
Jul 24 14:01:52 host poetry[767104]: 2024-07-24 14:01:52.83 | ERROR | Exception in ASGI application
Jul 24 14:01:52 host poetry[767104]: 2024-07-24 14:01:52.88 | INFO | XX.XX.XX.XX:0 - "GET /static/fonts/material-icons-v50.woff2?v=1721821738 HTTP/1.1" 200
Jul 24 14:01:52 host poetry[767104]: 2024-07-24 14:01:52.93 | WARNING | Failed to fetch Bitcoin price for CZK from Bitstamp: Client error '404 Not Found' for url 'https://www.bitstamp.net/api/v2/ticker/btcczk/'
Jul 24 14:01:52 host poetry[767104]: For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/404
Jul 24 14:01:52 host poetry[767104]: 2024-07-24 14:01:52.93 | INFO | XX.XX.XX.XX:0 - "GET /api/v1/payments/sse?api-key=XXXXXXXXXXXXX HTTP/1.1" 200
Jul 24 14:01:52 host poetry[767104]: 2024-07-24 14:01:52.94 | INFO | XX.XX.XX.XX:0 - "GET /api/v1/payments/paginated?limit=10&offset=0&sortby=time&direction=desc HTTP/1.1" 200
Jul 24 14:01:52 host poetry[767104]: 2024-07-24 14:01:52.95 | WARNING | Failed to fetch Bitcoin price for CZK from Kraken: 'result'
Jul 24 14:01:52 host poetry[767104]: 2024-07-24 14:01:52.97 | WARNING | Failed to fetch Bitcoin price for CZK from Binance: Client error '400 Bad Request' for url 'https://api.binance.com/api/v3/ticker/price?symbol=BTCCZK'
Jul 24 14:01:52 host poetry[767104]: For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/400
Jul 24 14:01:53 host poetry[767104]: 2024-07-24 14:01:53.14 | WARNING | Failed to fetch Bitcoin price for CZK from Bitfinex: Client error '400 Bad Request' for url 'https://api.bitfinex.com/v1/pubticker/btcczk'
Jul 24 14:01:53 host poetry[767104]: For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/400
Jul 24 14:01:53 host poetry[767104]: 2024-07-24 14:01:53.28 | WARNING | Failed to fetch Bitcoin price for CZK from Exir:
Jul 24 14:01:53 host poetry[767104]: 2024-07-24 14:01:53.28 | INFO | XX.XX.XX.XX:0 - "POST /api/v1/conversion HTTP/1.1" 200
Jul 24 14:01:53 host poetry[767104]: 2024-07-24 14:01:53.81 | INFO | XX.XX.XX.XX:0 - "GET /service-worker.js HTTP/1.1" 200
Jul 24 14:01:57 host poetry[767104]: 2024-07-24 14:01:57.15 | INFO | XX.XX.XX.XX:0 - "GET /node HTTP/1.1" 200
```

**Comment by dni** [comment]
yeah, i am randomly getting this errors aswell, i cannot really locate it. i got similar erros before, on the lnurl callback endpoints

**Comment by bitkarrot** [comment]
@dni,  I commented out this line and the error went away , it looks like there was a double registration of middleware. 

https://github.com/lnbits/lnbits/blob/97de4eda18a2637c960613da11ce222af9b09775/lnbits/middleware.py#L217
<img width="545" alt="Screenshot 2024-07-27 at 1 28 09 AM" src="https://github.com/user-attachments/assets/2cfe6ca9-68f3-4af0-bf14-9c971ebceca4">

<img width="936" alt="Screenshot 2024-07-27 at 1 27 48 AM" src="https://github.com/user-attachments/assets/468f8a3f-764b-489f-9b40-6480ee271f7d">

**Comment by Perlover** [comment]
Other middleware modules are also registered in the same way. I think you just commented out the registration for the execution of this middleware and just disabled it. If you think there is double registration there, you need to find another place where it registers. 

I'm not proficient in python, but similar work happens in node.js / express

**Comment by dni** [comment]
yes, i tested it, the decorator itself already registered it
calling the app.middleware duplicated it!

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ESMELSTEPHANE24** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by qiliq** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by robykartis** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/Jostino/RimWorld-it/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
