### ISSUE TITLE
LNURLp: creating a paylink via API on s.lnbits.com returns an error

### ISSUE THREAD

**Issue by cryptoteun** [lnbits/lnbits#267]
When creating a pay link via API on s.lnbits.com an error is returned. 
POST {{E_host}}/lnurlp/api/v1/links

**Request**
`{
    "description": "{{$randomLoremWords}}",
    "amount": 3,
    "max": 2,
    "min": 2,
    "comment_chars": 50
}`

**Response:**

> LNbits internal error!
> 
> Traceback (most recent call last):
> File "/root/lnbits/venv/lib/python3.8/site-packages/quart_trio/app.py", line 151, in full_dispatch_request
> result = await self.dispatch_request(request_context)
> File "/root/lnbits/venv/lib/python3.8/site-packages/quart/app.py", line 1933, in dispatch_request
> return await handler(**request_.view_args)
> File "/root/cockroach-lnbits/lnbits/decorators.py", line 28, in wrapped_view
> return await view(**kwargs)
> File "/root/cockroach-lnbits/lnbits/decorators.py", line 55, in wrapped_view
> return await view(**kwargs)
> File "/root/cockroach-lnbits/lnbits/extensions/lnurlp/views_api.py", line 111, in api_link_create_or_update
> link = await create_pay_link(wallet_id=g.wallet.id, **g.data)
> File "/root/cockroach-lnbits/lnbits/extensions/lnurlp/crud.py", line 50, in create_pay_link
> assert link, "Newly created link couldn't be retrieved"
> AssertionError: Newly created link couldn't be retrieved
> 
> 
> If you believe this shouldn't be an error please bring it up on https://t.me/lnbits

**Comment by cryptoteun** [comment]
Ran into this issue while working on a postman test for lnbits.

**Comment by arcbtc** [comment]
Thanks! We will take a look but may take a few days. Huge thanks also for building the postman test fro api endpoints, will be a really useful tool
