### ISSUE TITLE
[BUG] installation err on v0.12.12

### ISSUE THREAD

**Issue by bitkarrot** [lnbits/lnbits#2744]
**Describe the bug**
using Poetry (version 1.8.4)
python version 3.10 
on poetry install --only main
<img width="1138" alt="Screenshot 2024-10-22 at 6 30 57 PM" src="https://github.com/user-attachments/assets/07641f18-de7d-447e-b5d8-03b6c978b006">

**Expected behavior**
clean build

**Additional context**
OSX M2 Sonoma 14.5

**Comment by bitkarrot** [comment]
@dni

**Comment by dni** [comment]
grml, freaking secp256k1 library. i spot a pkg-config is needed for the install, can you try to brew install that?

**Comment by bitkarrot** [comment]
yeah i did try the following but no dice. i can't recall how i fixed this bug last year

```
brew install pkg-config libsecp256k1

export PKG_CONFIG_PATH="/opt/homebrew/opt/libsecp256k1/lib/pkgconfig:$PKG_CONFIG_PATH"
export LDFLAGS="-L/opt/homebrew/opt/libsecp256k1/lib"
export CPPFLAGS="-I/opt/homebrew/opt/libsecp256k1/include"

arch -arm64 poetry install
```

**Comment by bitkarrot** [comment]
Also tried: 

```
brew uninstall libsecp256k1   # Remove existing installation
brew cleanup
brew install automake pkg-config libtool libsecp256k1

export LDFLAGS="-L/opt/homebrew/opt/libsecp256k1/lib -L/opt/homebrew/opt/openssl@3/lib"
export CFLAGS="-I/opt/homebrew/opt/libsecp256k1/include"
export CPPFLAGS="-I/opt/homebrew/opt/libsecp256k1/include"
export PKG_CONFIG_PATH="/opt/homebrew/opt/libsecp256k1/lib/pkgconfig:/opt/homebrew/opt/openssl@3/lib/pkgconfig"
```

and 
```
pip install --no-binary :all: secp256k1
```

**Comment by bitkarrot** [comment]
Both of the above , after i try to manually install secp256k1, i still get the same error on `poetry install --only main`

wondering if there is a way to bypass....?

**Comment by bitkarrot** [comment]
oookay that seemed to work

```brew install pkg-config```

**Comment by dni** [comment]
> oookay that seemed to work
> 
> `brew install pkg-config`

nice :)

**Comment by bitkarrot** [comment]
so just the command above works if i delete the poetry.lock

but on `poetry run lnbits` i now have this error 

poetry run lnbits
2024-10-22 19:05:32.23 | ERROR | Traceback (most recent call last):
  File "/Users/bk/Library/Caches/pypoetry/virtualenvs/lnbits-sDFEFuNU-py3.10/lib/python3.10/site-packages/starlette/routing.py", line 693, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "/opt/homebrew/Cellar/python@3.10/3.10.15/Frameworks/Python.framework/Versions/3.10/lib/python3.10/contextlib.py", line 199, in __aenter__
    return await anext(self.gen)
  File "/Users/bk/github/lnbits/lnbits/app.py", line 113, in lifespan
    await startup(app)
  File "/Users/bk/github/lnbits/lnbits/app.py", line 73, in startup
    await migrate_databases()
  File "/Users/bk/github/lnbits/lnbits/core/helpers.py", line 75, in migrate_databases
    async with core_db.connect() as conn:
  File "/opt/homebrew/Cellar/python@3.10/3.10.15/Frameworks/Python.framework/Versions/3.10/lib/python3.10/contextlib.py", line 199, in __aenter__
    return await anext(self.gen)
  File "/Users/bk/github/lnbits/lnbits/db.py", line 281, in connect
    async with self.engine.connect() as conn:
  File "/Users/bk/Library/Caches/pypoetry/virtualenvs/lnbits-sDFEFuNU-py3.10/lib/python3.10/site-packages/sqlalchemy/ext/asyncio/base.py", line 66, in __aenter__
    return await self.start(is_ctxmanager=True)
  File "/Users/bk/Library/Caches/pypoetry/virtualenvs/lnbits-sDFEFuNU-py3.10/lib/python3.10/site-packages/sqlalchemy/ext/asyncio/engine.py", line 157, in start
    await (greenlet_spawn(self.sync_engine.connect))
  File "/Users/bk/Library/Caches/pypoetry/virtualenvs/lnbits-sDFEFuNU-py3.10/lib/python3.10/site-packages/sqlalchemy/util/concurrency.py", line 64, in greenlet_spawn
    _not_implemented()
  File "/Users/bk/Library/Caches/pypoetry/virtualenvs/lnbits-sDFEFuNU-py3.10/lib/python3.10/site-packages/sqlalchemy/util/concurrency.py", line 47, in _not_implemented
    raise ValueError(
ValueError: the greenlet library is required to use this function. No module named 'greenlet'

2024-10-22 19:05:32.23 | ERROR | Application startup failed. Exiting.

**Comment by bitkarrot** [comment]
(running dev branch, btw)

**Comment by dni** [comment]
`dev` is tough right now. but greenlet is a dependency from breez. hmmm suspicious can you try installing with `poetry install` instead of `poetry install --only main`

**Comment by bitkarrot** [comment]
OK i had to kill off the poetry.lock file from dev, it rewrote it likely due to OSX

on main, it seems to work this time with just `poetry install` , before it wasn't working with --only main
