### ISSUE TITLE
[BUG] v1.0.0-rc5: Unable to start lnbits with LndRestWallet

### ISSUE THREAD

**Issue by Liongrass** [lnbits/lnbits#2745]
**Describe the bug**
I installed lnbits like this:

```
git pull
poetry self update
git checkout v1.0.0-rc5
poetry install --only main
```

**To Reproduce**

1. I then start lnbits with `poetry run lnbits`
2. See error

```
2024-10-23 20:16:23.78 | ERROR | will restart the task in 5 seconds.
2024-10-23 20:16:28.78 | ERROR | exception in background task `unnamed`:
2024-10-23 20:16:28.79 | ERROR | Traceback (most recent call last):
  File "/home/ubuntu/git/lnbits/lnbits/tasks.py", line 79, in catch_everything_and_restart
    return await func()
  File "/home/ubuntu/git/lnbits/lnbits/tasks.py", line 122, in internal_invoice_listener
    checking_id = await internal_invoice_queue.get()
  File "/usr/lib/python3.9/asyncio/queues.py", line 166, in get
    await getter
RuntimeError: Task <Task pending name='Task-18' coro=<catch_everything_and_restart() running at /home/ubuntu/git/lnbits/lnbits/tasks.py:87>> got Future <Future pending> attached to a different loop
```

**Additional context**
I'm running litd on signet. The error does not appear on version 0.12.11 on signet with the same litd backend

**Comment by motorina0** [comment]
Thank you for reporting.
New release candidates will be coming out.
Note: `dev` is the development branch, for stable version `main` should be used.
