### ISSUE TITLE
[BUG] error on audit page

### ISSUE THREAD

**Issue by dni** [lnbits/lnbits#2852]
seeing this error:

![screenshot-1734592637](https://github.com/user-attachments/assets/d6b01ee4-2e3a-47bd-a63e-0fd6d544cce4)

- Database sqlite

```
Traceback (most recent call last):
  File "/home/dni/.cache/pypoetry/virtualenvs/lnbits-XeqO4Z-j-py3.10/lib/python3.10/site-packages/starlette/_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "/home/dni/.cache/pypoetry/virtualenvs/lnbits-XeqO4Z-j-py3.10/lib/python3.10/site-packages/starlette/routing.py", line 73, in app
    response = await f(request)
  File "/home/dni/.cache/pypoetry/virtualenvs/lnbits-XeqO4Z-j-py3.10/lib/python3.10/site-packages/fastapi/routing.py", line 301, in app
    raw_response = await run_endpoint_function(
  File "/home/dni/.cache/pypoetry/virtualenvs/lnbits-XeqO4Z-j-py3.10/lib/python3.10/site-packages/fastapi/routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/dni/repos/lnbits/lnbits/lnbits/core/views/audit_api.py", line 41, in api_get_audit_stats
    response_code_stats = await get_count_stats("response_code", filters)
  File "/home/dni/repos/lnbits/lnbits/lnbits/core/crud/audit.py", line 50, in get_count_stats
    data = await (conn or db).fetchall(
  File "/home/dni/repos/lnbits/lnbits/lnbits/db.py", line 338, in fetchall
    return await conn.fetchall(query, values, model)
  File "/home/dni/repos/lnbits/lnbits/lnbits/db.py", line 161, in fetchall
    return [dict_to_model(r, model) for r in row]
  File "/home/dni/repos/lnbits/lnbits/lnbits/db.py", line 161, in <listcomp>
    return [dict_to_model(r, model) for r in row]
  File "/home/dni/repos/lnbits/lnbits/lnbits/db.py", line 682, in dict_to_model
    _model.__init__(**_dict)  # type: ignore
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for AuditCountStat
field
  field required (type=value_error.missing)
```

**Comment by motorina0** [comment]
https://github.com/lnbits/lnbits/pull/2854
