### ISSUE TITLE
LNbitswith Clinghtning wallet error - pylightning

### ISSUE THREAD

**Issue by NVG2021** [lnbits/lnbits#358]
Hello,
I am trying to install LNbits with c-lightning and I am getting an error and no idea how to make it work.0
I've installed LNBits and was able to see the first "fake-empty" wallet....
http://localhost:5000/.

 Then started to reconfigure the .env file in order to make c-lightning the source of funds.... and I've got the error message the pylightning was needed, I installed it but still asking for it....
So, I've made something wrong as it is not working.... If you could check the code and see if it gives light????
Thank you

These are the messages on the terminal screen

nicolas@HP655:~/lnbits$ pip install pylightning==0.0.7.3
/usr/lib/python3/dist-packages/secretstorage/dhcrypto.py:15: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
  from cryptography.utils import int_from_bytes
/usr/lib/python3/dist-packages/secretstorage/util.py:19: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
  from cryptography.utils import int_from_bytes
Requirement already satisfied: pylightning==0.0.7.3 in /home/nicolas/.local/lib/python3.8/site-packages (0.0.7.3)

nicolas@HP655:~/lnbits$ ./venv/bin/hypercorn -k trio --bind 0.0.0.0:5000 'lnbits.app:create_app()'
Traceback (most recent call last):
  File "./venv/bin/hypercorn", line 8, in <module>
    sys.exit(main())
  File "/home/nicolas/lnbits/venv/lib/python3.8/site-packages/hypercorn/__main__.py", line 267, in main
    run(config)
  File "/home/nicolas/lnbits/venv/lib/python3.8/site-packages/hypercorn/run.py", line 34, in run
    worker_func(config)
  File "/home/nicolas/lnbits/venv/lib/python3.8/site-packages/hypercorn/trio/run.py", line 113, in trio_worker
    app = load_application(config.application_path)
  File "/home/nicolas/lnbits/venv/lib/python3.8/site-packages/hypercorn/utils.py", line 110, in load_application
    module = import_module(import_name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/nicolas/lnbits/lnbits/app.py", line 11, in <module>
    from .commands import db_migrate, handle_assets
  File "/home/nicolas/lnbits/lnbits/commands.py", line 8, in <module>
    from .db import SQLITE, POSTGRES, COCKROACH
  File "/home/nicolas/lnbits/lnbits/db.py", line 11, in <module>
    from .settings import LNBITS_DATA_FOLDER, LNBITS_DATABASE_URL
  File "/home/nicolas/lnbits/lnbits/settings.py", line 46, in <module>
    WALLET = wallet_class()
  File "/home/nicolas/lnbits/lnbits/wallets/clightning.py", line 26, in __init__
    raise ImportError(
ImportError: The `pylightning` library must be installed to use `CLightningWallet`.
nicolas@HP655:~/lnbits$

**Comment by dni** [comment]
use ```./venv/bin/pip3 install pylightning```
