### ISSUE TITLE
Pays invoice but doesn't stop "checking pending transactions"

### ISSUE THREAD

**Issue by HamishMacEwan** [lnbits/lnbits#55]
Hi,

This capture is taken after pressing the "Send Satoshis" button:
![chrome_hKekWERBL2](https://user-images.githubusercontent.com/388061/89076107-d39c0880-d3d3-11ea-9b39-a646fee42d61.png)

"This problem with payments by myNode's LNbits instance continues.  It pays, the payment has been received, but the page will stay in this state until the popup is cancelled and will continually poll the myNode LNbits server whenever the page is active.

What could be preventing the recognition/acknowledgement that the payment has succeeded?"

https://t.me/lnbits/4123 

Attached is 
[lnbitsError.log](https://github.com/lnbits/lnbits/files/5008990/lnbitsError.log)
a log of lnbits activity on myNodeBTC  ( @tehelsper) including an error message I hadn't found before:

```
Aug  1 08:34:47 myNode lnbits[4233]: [2020-08-01 08:34:47,210] ERROR in app: Exception on /api/v1/payments [GET]
Aug  1 08:34:47 myNode lnbits[4233]: Traceback (most recent call last):
Aug  1 08:34:47 myNode lnbits[4233]:   File "/home/bitcoin/.local/share/virtualenvs/lnbits-ib5ZU12v/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
Aug  1 08:34:47 myNode lnbits[4233]:     response = self.full_dispatch_request()
Aug  1 08:34:47 myNode lnbits[4233]:   File "/home/bitcoin/.local/share/virtualenvs/lnbits-ib5ZU12v/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
Aug  1 08:34:47 myNode lnbits[4233]:     rv = self.handle_user_exception(e)
Aug  1 08:34:47 myNode lnbits[4233]:   File "/home/bitcoin/.local/share/virtualenvs/lnbits-ib5ZU12v/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
Aug  1 08:34:47 myNode lnbits[4233]:     reraise(exc_type, exc_value, tb)
Aug  1 08:34:47 myNode lnbits[4233]:   File "/home/bitcoin/.local/share/virtualenvs/lnbits-ib5ZU12v/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
Aug  1 08:34:47 myNode lnbits[4233]:     raise value
Aug  1 08:34:47 myNode lnbits[4233]:   File "/home/bitcoin/.local/share/virtualenvs/lnbits-ib5ZU12v/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
Aug  1 08:34:47 myNode lnbits[4233]:     rv = self.dispatch_request()
Aug  1 08:34:47 myNode lnbits[4233]:   File "/home/bitcoin/.local/share/virtualenvs/lnbits-ib5ZU12v/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
Aug  1 08:34:47 myNode lnbits[4233]:     return self.view_functions[rule.endpoint](**req.view_args)
Aug  1 08:34:47 myNode lnbits[4233]:   File "/opt/mynode/lnbits/lnbits/decorators.py", line 24, in wrapped_view
Aug  1 08:34:47 myNode lnbits[4233]:     return view(**kwargs)
Aug  1 08:34:47 myNode lnbits[4233]:   File "/opt/mynode/lnbits/lnbits/core/views/api.py", line 19, in api_payments
Aug  1 08:34:47 myNode lnbits[4233]:     payment.set_pending(WALLET.get_payment_status(payment.checking_id).pending)
Aug  1 08:34:47 myNode lnbits[4233]:   File "/opt/mynode/lnbits/lnbits/wallets/lndrest.py", line 86, in get_payment_status
Aug  1 08:34:47 myNode lnbits[4233]:     return PaymentStatus(statuses[payment["status"]])
Aug  1 08:34:47 myNode lnbits[4233]: TypeError: 'NoneType' object is not subscriptable

```

**Comment by arcbtc** [comment]
Oooo, I bet this is the new LND rest changes they made. I'll look into it

**Comment by HamishMacEwan** [comment]
I've tried `lnbits` with `lnd` gRPC and that seems to work.  Suggests your diagnosis of `lnd` REST changes is on the right track.

**Comment by ChuckNorrison** [comment]
I did another isolated pr to improve that check:
https://github.com/lnbits/lnbits/pull/79

**Comment by fiatjaf** [comment]
I think this should be fixed in the newest code. Many things have changed in `LndRestWallet` so hopefully it is!

**Comment by fiatjaf** [comment]
Narrator: it wasn't.
