### ISSUE TITLE
LNbits funding source: paying lnurlp results in 500

### ISSUE THREAD

**Issue by cryptoteun** [lnbits/lnbits#852]
I run the current main branch via Docker (https://github.com/lnbits/lnbits-legend/commit/b83fb1d5d80aa75f024d883eadd39040b3ebf8cb)
I use legend.lnbits as my funding source (commit version 7fc13614753b55cbc35c7c6cc7c6850f50e9f7dd)

When I try to pay an lnurlp the amount can be retrieved, but when I pay I get a 500 error (with both WoS or Phoenix).

The logs shows the following error:

```
2022-08-07 12:24:06.44 | ERROR | lnbits.app:basic_error:182 | handled error
2022-08-07 12:24:06.44 | ERROR | lnbits.app:basic_error:183 | ERROR:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/gzip.py", line 24, in __call__
    await responder(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/gzip.py", line 43, in __call__
    await self.app(scope, receive, self.send_with_gzip)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/exceptions.py", line 93, in __call__
    raise exc
  File "/usr/local/lib/python3.9/site-packages/starlette/exceptions.py", line 82, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/usr/local/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 670, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 266, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 65, in app
    response = await func(request)
  File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 227, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 160, in run_endpoint_function
    return await dependant.call(**values)
  File "/app/lnbits/extensions/lnurlp/lnurl.py", line 86, in api_lnurl_callback
    payment_hash, payment_request = await create_invoice(
  File "/app/lnbits/core/services.py", line 71, in create_invoice
    raise InvoiceFailure(error_message or "unexpected backend error.")
lnbits.core.services.InvoiceFailure: 'utf-8' codec can't decode byte 0xca in position 1: invalid continuation byte
2022-08-07 12:24:06.44 | ERROR | Exception in ASGI application
```

**Comment by cryptoteun** [comment]
In the following situation I get the same result. But the error slightly differ.
- I run the current main branch via Docker
- I use a lnbits instance connected to my own CLN node as funding sourde. Both LNbits instances running against the (https://github.com/lnbits/lnbits-legend/commit/b83fb1d5d80aa75f024d883eadd39040b3ebf8cb)

```
2022-08-07 12:06:19.30 | ERROR | handled error
2022-08-07 12:06:19.30 | ERROR | ERROR:
Traceback (most recent call last):
  File "/opt/venv/lib/python3.7/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/opt/venv/lib/python3.7/site-packages/starlette/middleware/gzip.py", line 24, in __call__
    await responder(scope, receive, send)
  File "/opt/venv/lib/python3.7/site-packages/starlette/middleware/gzip.py", line 43, in __call__
    await self.app(scope, receive, self.send_with_gzip)
  File "/opt/venv/lib/python3.7/site-packages/starlette/middleware/cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "/opt/venv/lib/python3.7/site-packages/starlette/exceptions.py", line 93, in __call__
    raise exc
  File "/opt/venv/lib/python3.7/site-packages/starlette/exceptions.py", line 82, in __call__
    await self.app(scope, receive, sender)
  File "/opt/venv/lib/python3.7/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/opt/venv/lib/python3.7/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/opt/venv/lib/python3.7/site-packages/starlette/routing.py", line 670, in __call__
    await route.handle(scope, receive, send)
  File "/opt/venv/lib/python3.7/site-packages/starlette/routing.py", line 266, in handle
    await self.app(scope, receive, send)
  File "/opt/venv/lib/python3.7/site-packages/starlette/routing.py", line 65, in app
    response = await func(request)
  File "/opt/venv/lib/python3.7/site-packages/fastapi/routing.py", line 228, in app
    dependant=dependant, values=values, is_coroutine=is_coroutine
  File "/opt/venv/lib/python3.7/site-packages/fastapi/routing.py", line 160, in run_endpoint_function
    return await dependant.call(**values)
  File "./lnbits/extensions/lnurlp/lnurl.py", line 97, in api_lnurl_callback
    "extra": request.query_params.get("amount"),
  File "./lnbits/core/services.py", line 68, in create_invoice
    amount=amount, memo=invoice_memo, description_hash=description_hash
  File "./lnbits/wallets/lnbits.py", line 78, in create_invoice
    error_message = r.json()["detail"]
  File "/opt/venv/lib/python3.7/site-packages/httpx/_models.py", line 743, in json
    return jsonlib.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2022-08-07 12:06:19.30 | ERROR | Exception in ASGI application
```

**Comment by cryptoteun** [comment]
Issue doesn't seems to be present anymore, closed.
